# SWB Model irrigation example annotated control file
#
#--------------------------------------------------------------------------
# MODEL DOMAIN DEFINITION
#
# Definition of the model domain.  Units of meters are assumed.
# All subsequent input grids must match the specified model domain exactly.
#
#              Lower LH Corner     Upper  Grid
#            |_________________________|  Cell
#     NX  NY  X0            Y0            Size

#GRID 1070 900 1795350   1424350  100
#GRID 36  31  545300       432200     1000.0
#GRID  72  62  545300       432200      500.0
#GRID 1210  1048  545225.71773482       432152.74546081     30.0
GRID 400  346  545300         432200      90.0

#################################
INTERCEPTION_IS_PART_OF_ACTUAL_ET

BASE_PROJECTION_DEFINITION +proj=tmerc +lat_0=0.0 +lon_0=-90.0 +k=0.9996 +x_0=520000 +y_0=-4480000 +datum=NAD83 +units=m

GRID_LENGTH_UNITS METERS
SUPPRESS_SCREEN_OUTPUT
#SUPPRESS_INTEGRATED_OUTPUT
#SUPPRESS_DAILY_FILES
#SUPPRESS_DISLIN_MESSAGES

GROWING_SEASON 133 268 TRUE

ANSI_COLORS FALSE
RLE_MULTIPLIER 10000

PRECIPITATION NETCDF ../../../test_data/cs/prcp_Daymet_v3_%y.nc
PRECIPITATION_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
NETCDF_PRECIP_Z_VAR                       prcp
PRECIPITATION_SCALE_FACTOR          0.03937008
PRECIPITATION_MISSING_VALUES_CODE      -9999.0
PRECIPITATION_MISSING_VALUES_OPERATOR      <=
PRECIPITATION_MISSING_VALUES_ACTION       ZERO

TEMPERATURE NETCDF ../../../test_data/cs/tmax_Daymet_v3_%y.nc ../../../test_data/cs/tmin_Daymet_v3_%y.nc
TMAX_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
TMAX_SCALE_FACTOR                 1.8
TMAX_ADD_OFFSET                  32.0
TMAX_MISSING_VALUES_CODE      -9999.0
TMAX_MISSING_VALUES_OPERATOR      <=
TMAX_MISSING_VALUES_ACTION       MEAN

TMIN_GRID_PROJECTION_DEFINITION +proj=lcc +lat_1=25.0 +lat_2=60.0 +lat_0=42.5 +lon_0=-100.0 +x_0=0.0 +y_0=0.0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs
TMIN_SCALE_FACTOR                 1.8
TMIN_ADD_OFFSET                  32.0
TMIN_MISSING_VALUES_CODE      -9999.0
TMIN_MISSING_VALUES_OPERATOR      <=
TMIN_MISSING_VALUES_ACTION       MEAN

OUTPUT_GRID_SUFFIX asc

# set output paths to current directory
OUTPUT_PATH
OUTPUT_ANNUAL_PATH
OUTPUT_MONTHLY_PATH
OUTPUT_DAILY_PATH
OUTPUT_FUTURE_PATH

#set image output paths to current directory
IMAGE_PATH
IMAGE_ANNUAL_PATH
IMAGE_MONTHLY_PATH
IMAGE_DAILY_PATH

INITIAL_ABSTRACTION_METHOD HAWKINS

INITIAL_FROZEN_GROUND_INDEX CONSTANT 100.0
UPPER_LIMIT_CFGI 83.
LOWER_LIMIT_CFGI 55.

FLOW_DIRECTION ARC_GRID ../../../test_data/cs/d8_flow_direction.asc
FLOW_DIRECTION_PROJECTION_DEFINITION  +proj=tmerc +lat_0=0.0 +lon_0=-90.0 +k=0.9996 +x_0=520000 +y_0=-4480000 +datum=NAD83 +units=m

SOIL_GROUP ARC_GRID ../../../test_data/cs/hydrologic_soils_group.asc
SOIL_GROUP_PROJECTION_DEFINITION +proj=tmerc +lat_0=0.0 +lon_0=-90.0 +k=0.9996 +x_0=520000 +y_0=-4480000 +datum=NAD83 +units=m

LAND_USE ARC_GRID ../../../test_data/cs/landuse.asc
LANDUSE_PROJECTION_DEFINITION +proj=tmerc +lat_0=0.0 +lon_0=-90.0 +k=0.9996 +x_0=520000 +y_0=-4480000 +datum=NAD83 +units=m

OPEN_WATER_LAND_USE 111

LAND_USE_LOOKUP_TABLE ../../../test_data/tables/Landuse_lookup_SWB1.txt
IRRIGATION_LOOKUP_TABLE ../../../test_data/tables/Irrigation_lookup_SWB1.txt

WATER_CAPACITY ARC_GRID ../../../test_data/cs/available_water_capacity.asc
WATER_CAPACITY_PROJECTION_DEFINITION +proj=tmerc +lat_0=0.0 +lon_0=-90.0 +k=0.9996 +x_0=520000 +y_0=-4480000 +datum=NAD83 +units=m

IRRIGATED_LAND_MASK ARC_GRID ../../../test_data/cs/irrigation_mask_from_cdl.asc
IRRIGATED_LAND_MASK_PROJECTION_DEFINITION +proj=tmerc +lat_0=0.0 +lon_0=-90.0 +k=0.9996 +x_0=520000 +y_0=-4480000 +datum=NAD83 +units=m

SM T-M EQUATIONS

INITIAL_SOIL_MOISTURE CONSTANT 100
INITIAL_SNOW_COVER CONSTANT 2.0

#RUNOFF C-N DOWNHILL
RUNOFF C-N NONE
ET HARGREAVES 46.4 46.6

FAO56 CROP_COEFFICIENTS_TWO_FACTOR_NONSTANDARD
#ENABLE_IRRIGATION
IGNORE_MISSING_CLIMATE_DATA

#
#*******************************************************************
# PLOTTING CUSTOMIZATION
#
# This version of the SWB model allows very limited assignment of
# DISLIN plotting parameters for the generation of images.
# See http://www.mps.mpg.de/dislin/ for more information about this
# package.
#
# If no customizations are specified, default values will be used.
#
DISLIN_PARAMETERS IRRIGATION_FROM_GW
SET_Z_AXIS_RANGE DAILY 0 1.5 0.1
SET_Z_AXIS_RANGE MONTHLY 0 8. 1.0
SET_Z_AXIS_RANGE ANNUAL 0 16. 2.
Z_AXIS_TITLE IRRIGATION FROM GW, IN INCHES
#
DISLIN_PARAMETERS RECHARGE
SET_Z_AXIS_RANGE DAILY 0 1.5 0.1
SET_Z_AXIS_RANGE MONTHLY 0 7 1.0
SET_Z_AXIS_RANGE ANNUAL 0 20 2.
Z_AXIS_TITLE RECHARGE, IN INCHES
#
DISLIN_PARAMETERS GROSS_PRECIP
SET_Z_AXIS_RANGE DAILY 0 1.5 0.1
SET_Z_AXIS_RANGE MONTHLY 0 7 1.0
SET_Z_AXIS_RANGE ANNUAL 0 35. 5.
Z_AXIS_TITLE GROSS PRECIPITATION, IN INCHES
#
DISLIN_PARAMETERS SOIL_MOISTURE
SET_Z_AXIS_RANGE DAILY 0 10.0 1.0
SET_Z_AXIS_RANGE MONTHLY 0 10.0 1.0
SET_Z_AXIS_RANGE ANNUAL 0 10.0 1.
Z_AXIS_TITLE ROOT ZONE SOIL MOISTURE, IN INCHES
SET_COLOR_TABLE RRAIN
#
DISLIN_PARAMETERS ACT_ET
SET_Z_AXIS_RANGE DAILY 0 0.8 0.05
SET_Z_AXIS_RANGE MONTHLY 0 10. 0.5
SET_Z_AXIS_RANGE ANNUAL 0 40. 5.0
#SET_DEVICE PDF
#SET_FONT Helvetica-Bold
Z_AXIS_TITLE ACTUAL ET, IN INCHES
#
DISLIN_PARAMETERS REFERENCE_ET
SET_Z_AXIS_RANGE DAILY 0 0.8 0.05
SET_Z_AXIS_RANGE MONTHLY 0 10. 0.5
SET_Z_AXIS_RANGE ANNUAL 0 45. 5.
#SET_DEVICE WMF
#SET_FONT Courier New Italic
Z_AXIS_TITLE REFERENCE ET, IN INCHES
#
DISLIN_PARAMETERS RUNOFF_OUTSIDE
SET_Z_AXIS_RANGE DAILY 0 5. 0.5
SET_Z_AXIS_RANGE MONTHLY 0 12. 0.5
SET_Z_AXIS_RANGE ANNUAL 0 20. 2.
Z_AXIS_TITLE RUNOFF OUT OF GRID, IN INCHES
#
DISLIN_PARAMETERS REJECTED_RECHARGE
SET_Z_AXIS_RANGE DAILY 0 5. 0.5
SET_Z_AXIS_RANGE MONTHLY 0 12. 0.5
SET_Z_AXIS_RANGE ANNUAL 0 25. 5.
Z_AXIS_TITLE RUNOFF OUT OF GRID, IN INCHES

#DISLIN_PARAMETERS SNOWCOVER
#SET_Z_AXIS_RANGE DAILY 0 12. 0.5
#Z_AXIS_TITLE SNOW COVER, IN INCHES (WATER EQUIVALENT)
#
DISLIN_PARAMETERS SM_APWL
SET_Z_AXIS_RANGE DAILY -20. 0. 2.0
Z_AXIS_TITLE ACCUMULATED POTENTIAL WATER LOSS, IN INCHES
SET_COLOR_TABLE RRAIN
#*******************************************************************
# OUTPUT OPTIONS
#
# The SWB code can generate image and ARCGIS/Surfer output at the
# daily, monthly, or annual timescale. This section allows the user to
# specify exactly what output should be generated for each of 24
# internal variables at each of the three timescales.
#
# Format for specifying output options is:
# "OUTPUT_OPTIONS variable_name daily_opt monthly_opt annual_opt"
#
# where the possible values for each option are:
# NONE, GRAPH, GRID, or BOTH
#
OUTPUT_OPTIONS RECHARGE            NONE NONE BOTH
OUTPUT_OPTIONS GROSS_PRECIP        NONE NONE BOTH
#OUTPUT_OPTIONS SM_APWL             NONE NONE NONE
#OUTPUT_OPTIONS SOIL_MOISTURE       GRID GRID GRID
#OUTPUT_OPTIONS SNOWCOVER           NONE NONE NONE
OUTPUT_OPTIONS CROP_ET             NONE NONE BOTH
#OUTPUT_OPTIONS BARE_SOIL_EVAP      GRID GRID GRID
OUTPUT_OPTIONS IRRIGATION_FROM_GW  NONE NONE BOTH
#OUTPUT_OPTIONS IRRIGATION_FROM_SW  NONE NONE NONE
OUTPUT_OPTIONS INTERCEPTION        NONE NONE BOTH
OUTPUT_OPTIONS RUNOFF_OUTSIDE      NONE NONE BOTH
OUTPUT_OPTIONS INFLOW              NONE NONE BOTH
OUTPUT_OPTIONS NET_INFIL           NONE NONE BOTH
OUTPUT_OPTIONS ACT_ET              NONE NONE BOTH
OUTPUT_OPTIONS BARE_SOIL_EVAP      NONE NONE BOTH
#OUTPUT_OPTIONS REFERENCE_ET        GRID GRID GRID
#OUTPUT_OPTIONS REFERENCE_ET_ADJ    GRID GRID GRID
#OUTPUT_OPTIONS ROOTING_DEPTH       NONE NONE NONE
OUTPUT_OPTIONS REJECTED_RECHARGE   NONE NONE BOTH

# POTATOES
DUMP_VARIABLES COORDINATES 561167. 445224.

# RYE
DUMP_VARIABLES COORDINATES 546094., 438492.

# EVERGREEN FOREST
DUMP_VARIABLES COORDINATES 556791. 457569.

# WINTER WHEAT
DUMP_VARIABLES COORDINATES 568129. 458340.

# DEC FOREST
DUMP_VARIABLES COORDINATES 553927. 459454.

# SWEET CORN
DUMP_VARIABLES COORDINATES 555602. 434644.

# SOYBEANS
DUMP_VARIABLES COORDINATES 558663. 432949.

# SUGAR BEETS
DUMP_VARIABLES COORDINATES 570741. 445112.

#*******************************************************************
# Next line specifies output grid format: ARC_GRID or SURFER
#
OUTPUT_FORMAT ARC_GRID
#*******************************************************************
# BEGIN SOLUTION
#
SOLVE_NO_TS_FILE 2012 2013
EOJ
#
