program tests

  ! Driver program for FRUIT unit tests in:
  ! test_allocatable_string.F90

  ! Generated by FRUITPy.

  use fruit
  use test_allocatable_string

  implicit none

  call init_fruit

  call run_test_case(test_string_list_with_character,"[ LOCALS ]")

  call fruit_summary
  call fruit_finalize

end program tests