program tests

  ! Driver program for FRUIT unit tests in:
  ! test_timer.F90
  ! test_datetime.F90
  ! test_crop_coefficients__FAO56.F90
  ! test_gash.F90

  ! Generated by FRUITPy.

  use fruit
  use test_timer
  use test_datetime
  use test_crop_coefficients__FAO56
  use test__gash

  implicit none

  call init_fruit

  ! test_timer.F90:
  call run_test_case(test_timer_basic,"timer: test basic functionality - convert seconds to hms")
  call run_test_case(test_timer_split,"timer: test split and elapsed timer functionality")
  call run_test_case(test_timer_prettyprint,"timer: test ability to output in human-readable form")

  ! test_datetime.F90:
  call run_test_case(test_datetime_basic_dateparse,"datetime: parse with default mm/dd/yyyy date format")
  call run_test_case(test_datetime_basic_mangled_dateparse,"datetime: parse with default mm/dd/yyyy date format, missing '0' values in month and day")
  call run_test_case(test_datetime_custom_dateparse,"datetime: parse with custom yyyy-mm-dd date format")
  call run_test_case(test_datetime_addition,"datetime: add 5 to Julian day and return the correct Gregorian date")

  ! test_crop_coefficients__FAO56.F90:
  call setup_crop_coefficients__FAO56
  call run_test_case(test_crop_coefficients_parsing,"test_crop_coefficients_parsing")
  call run_test_case(test_crop_coefficients_basic,"test_crop_coefficients_basic")

  ! test_gash.F90:
  call run_test_case(test_gash_psat_calculation,"gash: test calculation of Gash PSat")
  call run_test_case(test_gash_calculation,"gash: calculate Gash interception for published case")

  call fruit_summary
  call fruit_finalize

end program tests