module test_gash
  !! Unit tests for the Gash interception model.
  !!
  !! Based on the analytical model of Gash (1979):
  !!   Gash, J.H.C., 1979, An analytical model of rainfall interception
  !!   by forests: Quarterly Journal of the Royal Meteorological Society,
  !!   v. 105, p. 43-55.
  !!
  !! See also: Gash, J.H.C., Lloyd, C.R., and Lachaud, G., 1995,
  !!   Estimating sparse forest rainfall interception with an analytical
  !!   model: Journal of Hydrology, v. 170, p. 79-86.
  !!
  !! Test values (rainfall timeseries and expected interception) were
  !! generated by an independent Python implementation of the Gash
  !! equations (see test_support/Calculate_Gash_interception.ipynb).
  !! The Fortran code is verified against these values.
  !!
  !! No environment setup needed — the Gash functions are pure calculations.

  use iso_c_binding, only: c_int, c_float
  use testdrive, only: check, error_type, new_unittest, unittest_type, test_failed
  use interception__gash, only: precipitation_at_saturation, interception_gash_calculate
  implicit none
  private

  public :: collect_gash

  ! --- Published test case parameters ---
  real(c_float), parameter :: EVAP_TO_RAINFALL_RATIO = 0.5
  real(c_float), parameter :: CANOPY_FRACTION        = 0.58
  real(c_float), parameter :: CANOPY_STORAGE         = 0.05
  real(c_float), parameter :: TRUNK_STORAGE          = 0.01
  real(c_float), parameter :: STEMFLOW_FRACTION      = 0.04
  real(c_float), parameter :: TOLERANCE              = 1.0e-4

  ! --- Published rainfall timeseries and expected interception ---
  real(c_float), parameter :: RAINFALL(20) = [ &
    0.0, 0.0057, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0189, 0.0057, 0.0214, &
    0.1121, 0.2172, 0.0082, 0.0, 0.0007, 0.0, 0.0007, 0.0, 0.0, 0.0 ]

  real(c_float), parameter :: EXPECTED_INTERCEPTION(20) = [ &
    0.0, 0.003306, 0.0, 0.0, 0.0, 0.0, 0.0, 0.010962, &
    0.003306, 0.01241, 0.0650, 0.1063, 0.004756, 0.0,  &
    0.000406, 0.0, 0.000406, 0.0, 0.0, 0.0 ]

contains

  !---------------------------------------------------------------------------
  !> @brief Register all Gash interception tests.
  !---------------------------------------------------------------------------
  subroutine collect_gash(testsuite)
    type(unittest_type), allocatable, intent(out) :: testsuite(:)

    testsuite = [ &
      new_unittest("psat_calculation", test_psat_calculation), &
      new_unittest("interception_published_case", test_interception_published_case) &
    ]
  end subroutine collect_gash

  !---------------------------------------------------------------------------
  !> @brief Precipitation at saturation matches expected value.
  !---------------------------------------------------------------------------
  subroutine test_psat_calculation(error)
    type(error_type), allocatable, intent(out) :: error
    real(c_float) :: psat

    psat = precipitation_at_saturation( &
             E_div_P=EVAP_TO_RAINFALL_RATIO, &
             canopy_storage_capacity=CANOPY_STORAGE, &
             canopy_cover_fraction=CANOPY_FRACTION)

    call check(error, abs(psat - 0.119508) < TOLERANCE, &
               "PSat mismatch: expected 0.119508")
  end subroutine test_psat_calculation

  !---------------------------------------------------------------------------
  !> @brief Daily interception values match published case for all 20 days.
  !!
  !! Uses table-driven accumulation pattern: loops over all days, collects
  !! all failures, reports them together at the end.
  !---------------------------------------------------------------------------
  subroutine test_interception_published_case(error)
    type(error_type), allocatable, intent(out) :: error

    real(c_float) :: psat, interception_value, fog(20)
    integer(c_int) :: day, num_failures
    character(len=1024) :: failure_msg
    character(len=80) :: line

    fog = 0.0

    psat = precipitation_at_saturation( &
             E_div_P=EVAP_TO_RAINFALL_RATIO, &
             canopy_storage_capacity=CANOPY_STORAGE, &
             canopy_cover_fraction=CANOPY_FRACTION)

    num_failures = 0
    failure_msg = ""

    do day = 1, 20
      call interception_gash_calculate( &
             fRainfall=RAINFALL(day), &
             fFog=fog(day), &
             fCanopy_Cover_Fraction=CANOPY_FRACTION, &
             fTrunk_Storage_Capacity=TRUNK_STORAGE, &
             fStemflow_Fraction=STEMFLOW_FRACTION, &
             fEvaporation_to_Rainfall_Ratio=EVAP_TO_RAINFALL_RATIO, &
             fPrecipitation_at_Saturation=psat, &
             fInterception=interception_value)

      if (abs(interception_value - EXPECTED_INTERCEPTION(day)) > TOLERANCE) then
        num_failures = num_failures + 1
        write(line, '("  Day ", i2, ": got ", f8.6, " expected ", f8.6, a)') &
          day, interception_value, EXPECTED_INTERCEPTION(day), new_line('a')
        failure_msg = trim(failure_msg) // trim(line)
      end if
    end do

    if (num_failures > 0) then
      call test_failed(error, trim(failure_msg))
    end if

  end subroutine test_interception_published_case

end module test_gash
