SWB 2.0: awc__gridded_values Module Reference
awc__gridded_values Module Reference
Populate available water content by reading in the available water content from a gridded data source.
Functions/Subroutines
subroutine, public awc_gridded_values_read ()
subroutine, public awc_gridded_values_initialize (lActive, fAWC)
Variables
type(data_catalog_entry_t), pointer, public pawc_grid
Detailed Description
Function/Subroutine Documentation
awc_gridded_values_read()
subroutine, public awc__gridded_values::awc_gridded_values_read ()
Definition at line 28 of file awc__gridded_values.F90.
References data_catalog::dat, pawc_grid, and exceptions::warn().
Referenced by model_domain::model_read_available_water_content_gridded().
awc_gridded_values_initialize()
subroutine, public awc__gridded_values::awc_gridded_values_initialize (logical (kind=c_bool), dimension(:,:), intent(in) lActive, real (kind=c_float), dimension(:), intent(inout) fAWC)
Definition at line 42 of file awc__gridded_values.F90.
References pawc_grid.
Referenced by model_domain::model_initialize_available_water_content_gridded().
Variable Documentation
pawc_grid
type (data_catalog_entry_t), pointer, public awc__gridded_values::pawc_grid
Definition at line 23 of file awc__gridded_values.F90.
Referenced by awc_gridded_values_initialize(), and awc_gridded_values_read().