SWB 2.0: output Module Reference
output Module Reference
Data Types
type netcdf_file_collection_t
type output_specs_t
Functions/Subroutines
subroutine, public set_output_latlon_option (output_includes_latlon_)
subroutine, public set_output_directory (output_dir_name)
subroutine, public set_output_prefix (output_prefix)
subroutine, public initialize_output (cells)
subroutine, public write_output (cells)
Variables
type(netcdf_file_collection_t), dimension(:), allocatable, public nc_out
integer(kind=c_int), parameter ncdf_num_outputs = 19
type(output_specs_t), dimension(ncdf_num_outputs) outspecs = [ OUTPUT_SPECS_T("gross_precipitation ", "inches_per_day ", 0.0, 60.0), OUTPUT_SPECS_T("rainfall ", "inches_per_day ", 0.0, 60.0), OUTPUT_SPECS_T("snowfall ", "inches_per_day ", 0.0, 60.0), OUTPUT_SPECS_T("interception ", "inches_per_day ", 0.0, 60.0), OUTPUT_SPECS_T("runon ", "inches_per_day ", 0.0, 10000.0), OUTPUT_SPECS_T("runoff ", "inches_per_day ", 0.0, 10000.0), OUTPUT_SPECS_T("snow_storage ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("soil_storage ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("reference_ET0 ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("actual_et ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("snowmelt ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("tmin ", "degrees_fahrenheit ", -100.0, 150.0), OUTPUT_SPECS_T("tmax ", "degrees_fahrenheit ", -100.0, 150.0), OUTPUT_SPECS_T("potential_recharge ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("rejected_potential_recharge", "inches_per_day ", 0.0, 5000.0), OUTPUT_SPECS_T("infiltration ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("irrigation ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("runoff_outside ", "inches_per_day ", 0.0, 10000.0), OUTPUT_SPECS_T("gdd ", "degree_day_fahrenheit", 0.0, 10000.0) ]
logical(kind=c_bool) output_includes_latlon = lTRUE
Function/Subroutine Documentation
subroutine, public output::set_output_latlon_option (logical (kind=c_bool) output_includes_latlon_)
Definition at line 68 of file output.F90.
References output_includes_latlon.
Referenced by model_initialize::initialize_program_options().
subroutine, public output::set_output_directory (character (len=*), intent(in) output_dir_name)
Definition at line 78 of file output.F90.
Referenced by model_initialize::initialize_all().
subroutine, public output::set_output_prefix (character (len=*), intent(in) output_prefix)
Definition at line 88 of file output.F90.
Referenced by model_initialize::initialize_all().
subroutine, public output::initialize_output (class (model_domain_t), intent(inout) cells)
Definition at line 98 of file output.F90.
References nc_out, ncdf_num_outputs, output_includes_latlon, and outspecs.
Referenced by model_initialize::initialize_all().
subroutine, public output::write_output (class (model_domain_t), intent(inout) cells)
Definition at line 166 of file output.F90.
References nc_out.
Referenced by model_iterate::iterate_over_simulation_days().
Variable Documentation
type (netcdf_file_collection_t), dimension(:), allocatable, public output::nc_out
Definition at line 20 of file output.F90.
Referenced by initialize_output(), and write_output().
integer (kind=c_int), parameter output::ncdf_num_outputs = 19 private
Definition at line 22 of file output.F90.
Referenced by initialize_output().
type (output_specs_t), dimension(ncdf_num_outputs) output::outspecs = [ OUTPUT_SPECS_T("gross_precipitation ", "inches_per_day ", 0.0, 60.0), OUTPUT_SPECS_T("rainfall ", "inches_per_day ", 0.0, 60.0), OUTPUT_SPECS_T("snowfall ", "inches_per_day ", 0.0, 60.0), OUTPUT_SPECS_T("interception ", "inches_per_day ", 0.0, 60.0), OUTPUT_SPECS_T("runon ", "inches_per_day ", 0.0, 10000.0), OUTPUT_SPECS_T("runoff ", "inches_per_day ", 0.0, 10000.0), OUTPUT_SPECS_T("snow_storage ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("soil_storage ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("reference_ET0 ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("actual_et ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("snowmelt ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("tmin ", "degrees_fahrenheit ", -100.0, 150.0), OUTPUT_SPECS_T("tmax ", "degrees_fahrenheit ", -100.0, 150.0), OUTPUT_SPECS_T("potential_recharge ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("rejected_potential_recharge", "inches_per_day ", 0.0, 5000.0), OUTPUT_SPECS_T("infiltration ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("irrigation ", "inches_per_day ", 0.0, 2000.0), OUTPUT_SPECS_T("runoff_outside ", "inches_per_day ", 0.0, 10000.0), OUTPUT_SPECS_T("gdd ", "degree_day_fahrenheit", 0.0, 10000.0) ] private
Definition at line 31 of file output.F90.
Referenced by initialize_output().
logical (kind=c_bool) output::output_includes_latlon = lTRUE private
Definition at line 63 of file output.F90.
Referenced by initialize_output(), and set_output_latlon_option().