SWB 2.0: interception__gash Module Reference
interception__gash Module Reference
Functions/Subroutines
subroutine, public interception_gash_initialize (lActive, fCanopy_Cover_Fraction, iLandUseIndex)
Initialize the Gash interception algorithm.
elemental real(kind=c_float) function, public precipitation_at_saturation (E_div_P, canopy_storage_capacity, canopy_cover_fraction)
elemental subroutine, public interception_gash_calculate (fRainfall, fFog, fCanopy_Cover_Fraction, fTrunk_Storage_Capacity, fStemflow_Fraction, fEvaporation_to_Rainfall_Ratio, fPrecipitation_at_Saturation, fInterception)
Variables
type(data_catalog_entry_t), pointer pevaporation_to_rainfall_ratio
real(kind=c_float), dimension(:), allocatable, public evaporation_to_rainfall_ratio
real(kind=c_float), dimension(:), allocatable, public canopy_storage_capacity_table_values
real(kind=c_float), dimension(:), allocatable, public trunk_storage_capacity_table_values
real(kind=c_float), dimension(:), allocatable, public stemflow_fraction_table_values
real(kind=c_float), dimension(:), allocatable, public p_sat
type(t_netcdf4_file), pointer pncfile
Function/Subroutine Documentation
subroutine, public interception__gash::interception_gash_initialize (logical (kind=c_bool), dimension(:,:), intent(in) lActive, real (kind=c_float), dimension(:), intent(in) fCanopy_Cover_Fraction, integer (kind=c_int), dimension(:), intent(in) iLandUseIndex)
Read in a canopy cover fraction and rainfall-to-evaporation ratio grids
Determine how many landuse codes are present
add more guard code here to QA incoming data
Definition at line 49 of file interception__gash.F90.
References canopy_storage_capacity_table_values, data_catalog::dat, exceptions::die(), evaporation_to_rainfall_ratio, grid::grid_writearcgrid(), p_sat, parameters::params, pevaporation_to_rainfall_ratio, precipitation_at_saturation(), stemflow_fraction_table_values, constants_and_conversions::true, trunk_storage_capacity_table_values, and exceptions::warn().
Referenced by model_domain::model_initialize_interception_gash().
elemental real (kind=c_float) function, public interception__gash::precipitation_at_saturation (real (kind=c_float), intent(in) E_div_P, real (kind=c_float), intent(in) canopy_storage_capacity, real (kind=c_float), intent(in) canopy_cover_fraction)
Definition at line 153 of file interception__gash.F90.
Referenced by interception_gash_initialize().
elemental subroutine, public interception__gash::interception_gash_calculate (real (kind=c_float), intent(in) fRainfall, real (kind=c_float), intent(in) fFog, real (kind=c_float), intent(in) fCanopy_Cover_Fraction, real (kind=c_float), intent(in) fTrunk_Storage_Capacity, real (kind=c_float), intent(in) fStemflow_Fraction, real (kind=c_float), intent(in) fEvaporation_to_Rainfall_Ratio, real (kind=c_float), intent(in) fPrecipitation_at_Saturation, real (kind=c_float), intent(inout) fInterception)
Definition at line 185 of file interception__gash.F90.
Referenced by model_domain::model_calculate_interception_gash().
Variable Documentation
type (data_catalog_entry_t), pointer interception__gash::pevaporation_to_rainfall_ratio private
Definition at line 30 of file interception__gash.F90.
Referenced by interception_gash_initialize().
real (kind=c_float), dimension(:), allocatable, public interception__gash::evaporation_to_rainfall_ratio
Definition at line 32 of file interception__gash.F90.
Referenced by interception_gash_initialize(), and model_domain::model_calculate_interception_gash().
real (kind=c_float), dimension(:), allocatable, public interception__gash::canopy_storage_capacity_table_values
Definition at line 34 of file interception__gash.F90.
Referenced by interception_gash_initialize().
real (kind=c_float), dimension(:), allocatable, public interception__gash::trunk_storage_capacity_table_values
Definition at line 35 of file interception__gash.F90.
Referenced by interception_gash_initialize(), and model_domain::model_calculate_interception_gash().
real (kind=c_float), dimension(:), allocatable, public interception__gash::stemflow_fraction_table_values
Definition at line 36 of file interception__gash.F90.
Referenced by interception_gash_initialize(), and model_domain::model_calculate_interception_gash().
real (kind=c_float), dimension(:), allocatable, public interception__gash::p_sat
Definition at line 38 of file interception__gash.F90.
Referenced by interception_gash_initialize(), and model_domain::model_calculate_interception_gash().
type (t_netcdf4_file), pointer interception__gash::pncfile private
Definition at line 40 of file interception__gash.F90.