SWB 2.0: crop_coefficients__fao56 Module Reference
crop_coefficients__fao56 Module Reference
Update crop coefficients for crop types in simulation.
Functions/Subroutines
subroutine, public crop_coefficients_fao56_initialize (fSoilStorage, iLanduseIndex, iSoilGroup, fAvailable_Water_Content, lActive)
elemental real(kind=c_float) function, public update_crop_coefficient_date_as_threshold (iLanduseIndex)
Update the current basal crop coefficient (Kcb) for a SINGLE irrigation table entry.
elemental real(kind=c_float) function, public update_crop_coefficient_gdd_as_threshold (iLanduseIndex, fGDD)
Update the current basal crop coefficient (Kcb), with GDD as the threhold.
subroutine, public crop_coefficients_fao56_update_growth_stage_dates ()
elemental real(kind=c_float) function calc_effective_root_depth (iLanduseIndex, fZr_max, fKCB)
Calculate the effective root zone depth.
elemental subroutine, public crop_coefficients_fao56_calculate (Kcb, GDD, landuse_index)
Variables
integer(kind=c_int), dimension(:), allocatable landuse_code
real(kind=c_float), dimension(:,:), allocatable rew
real(kind=c_float), dimension(:,:), allocatable tew
real(kind=c_float), dimension(:,:), allocatable kcb
integer(kind=c_int), dimension(:), allocatable kcb_method
real(kind=c_float), dimension(:,:), allocatable growth_stage_doy
real(kind=c_float), dimension(:,:), allocatable growth_stage_gdd
type(datetime_t), dimension(:,:), allocatable, public growth_stage_date
real(kind=c_float), dimension(:), allocatable mean_plant_height
integer(kind=c_int) lu_soils_csv
Detailed Description
Function/Subroutine Documentation
crop_coefficients_fao56_initialize()
subroutine, public crop_coefficients__fao56::crop_coefficients_fao56_initialize (real (kind=c_float), dimension(:), intent(inout) fSoilStorage, integer (kind=c_int), dimension(:), intent(in) iLanduseIndex, integer (kind=c_int), dimension(:), intent(in) iSoilGroup, real (kind=c_float), dimension(:), intent(in) fAvailable_Water_Content, logical (kind=c_bool), dimension(:,:), intent(in) lActive)
create string list that allows for alternate heading identifiers for the landuse code
Determine how many landuse codes are present
Todo:
Implement thorough input error checking: are all soils in grid included in table values? is soil suffix vector continuous?
What should happen if the TEW / REW header entries do not fall in a logical sequence of values? In other words, if the user has columns named REW_1, REW_3, REW_5, only the values associated with "REW_1" would be retrieved. Needless to say, this would be catastrophic.
Add more logic here to perform checks on the validity of this data.
Need to handle missing values. WHat do we do if an entire column of values is missing?
Definition at line 76 of file crop_coefficients__fao56.F90.
References growth_stage_date, growth_stage_doy, growth_stage_gdd, kcb, kcb_method, landuse_code, mean_plant_height, rew, and tew.
Referenced by model_domain::model_initialize_crop_coefficient_fao56().
update_crop_coefficient_date_as_threshold()
elemental real (kind=c_float) function, public crop_coefficients__fao56::update_crop_coefficient_date_as_threshold (integer (kind=c_int), intent(in) iLanduseIndex)
Parameters
[in,out] pIRRIGATION pointer to a single line of information in the irrigation file.
[in] iThreshold either the current day of year or the number of growing degree days.
Return values
rKcb Basal crop coefficient given the irrigation table entries and the current threshold values.
Definition at line 375 of file crop_coefficients__fao56.F90.
References growth_stage_date, kcb, and kcb_method.
Referenced by crop_coefficients_fao56_calculate().
update_crop_coefficient_gdd_as_threshold()
elemental real (kind=c_float) function, public crop_coefficients__fao56::update_crop_coefficient_gdd_as_threshold (integer (kind=c_int), intent(in) iLanduseIndex, real (kind=c_float), intent(in) fGDD)
Parameters
[in] fGDD current growing degree day value associated with the cell.
Return values
fKcb Basal crop coefficient given the irrigation table entries and the current threshold values.
Definition at line 449 of file crop_coefficients__fao56.F90.
References growth_stage_gdd, and kcb.
crop_coefficients_fao56_update_growth_stage_dates()
subroutine, public crop_coefficients__fao56::crop_coefficients_fao56_update_growth_stage_dates ()
Definition at line 506 of file crop_coefficients__fao56.F90.
References growth_stage_date, growth_stage_doy, kcb_method, and landuse_code.
Referenced by model_domain::model_update_crop_coefficient_fao56().
calc_effective_root_depth()
elemental real (kind=c_float) function crop_coefficients__fao56::calc_effective_root_depth (integer (kind=c_int), intent(in) iLanduseIndex, real (kind=c_float), intent(in) fZr_max, real (kind=c_float), intent(in) fKCB) private
Calculate the effective root zone depth given the current stage of plant growth, the soil type, and the crop type.
Parameters
[in] pIRRIGATION pointer to a specific line of the irrigation lookup data structure.
[in] rZr_max The maximum rooting depth for this crop; currently this is supplied to this function as the rooting depth associated with the landuse/soil type found in the landuse lookup table.
[in] iThreshold Numeric value (either the GDD or the DOY) defining the time that the crop is planted.
Return values
rZr_i current active rooting depth.
Note
Implemented as equation 8-1 (Annex 8), FAO-56, Allen and others.
Definition at line 582 of file crop_coefficients__fao56.F90.
References kcb, and kcb_method.
crop_coefficients_fao56_calculate()
elemental subroutine, public crop_coefficients__fao56::crop_coefficients_fao56_calculate (real (kind=c_float), intent(inout) Kcb, real (kind=c_float), intent(in) GDD, integer (kind=c_int), intent(in) landuse_index)
Definition at line 629 of file crop_coefficients__fao56.F90.
References kcb_method, and update_crop_coefficient_date_as_threshold().
Referenced by model_domain::model_update_crop_coefficient_fao56().
Variable Documentation
landuse_code
integer (kind=c_int), dimension(:), allocatable crop_coefficients__fao56::landuse_code private
Definition at line 58 of file crop_coefficients__fao56.F90.
Referenced by crop_coefficients_fao56_initialize(), and crop_coefficients_fao56_update_growth_stage_dates().
rew
real (kind=c_float), dimension(:,:), allocatable crop_coefficients__fao56::rew private
Definition at line 59 of file crop_coefficients__fao56.F90.
Referenced by crop_coefficients_fao56_initialize().
tew
real (kind=c_float), dimension(:,:), allocatable crop_coefficients__fao56::tew private
Definition at line 60 of file crop_coefficients__fao56.F90.
Referenced by crop_coefficients_fao56_initialize().
kcb
real (kind=c_float), dimension(:,:), allocatable crop_coefficients__fao56::kcb private
Definition at line 61 of file crop_coefficients__fao56.F90.
Referenced by calc_effective_root_depth(), crop_coefficients_fao56_initialize(), update_crop_coefficient_date_as_threshold(), and update_crop_coefficient_gdd_as_threshold().
kcb_method
integer (kind=c_int), dimension(:), allocatable crop_coefficients__fao56::kcb_method private
Definition at line 62 of file crop_coefficients__fao56.F90.
Referenced by calc_effective_root_depth(), crop_coefficients_fao56_calculate(), crop_coefficients_fao56_initialize(), crop_coefficients_fao56_update_growth_stage_dates(), and update_crop_coefficient_date_as_threshold().
growth_stage_doy
real (kind=c_float), dimension(:,:), allocatable crop_coefficients__fao56::growth_stage_doy private
Definition at line 63 of file crop_coefficients__fao56.F90.
Referenced by crop_coefficients_fao56_initialize(), and crop_coefficients_fao56_update_growth_stage_dates().
growth_stage_gdd
real (kind=c_float), dimension(:,:), allocatable crop_coefficients__fao56::growth_stage_gdd private
Definition at line 64 of file crop_coefficients__fao56.F90.
Referenced by crop_coefficients_fao56_initialize(), and update_crop_coefficient_gdd_as_threshold().
growth_stage_date
type (datetime_t), dimension(:,:), allocatable, public crop_coefficients__fao56::growth_stage_date
Definition at line 65 of file crop_coefficients__fao56.F90.
Referenced by crop_coefficients_fao56_initialize(), crop_coefficients_fao56_update_growth_stage_dates(), model_domain::model_update_crop_coefficient_fao56(), and update_crop_coefficient_date_as_threshold().
mean_plant_height
real (kind=c_float), dimension(:), allocatable crop_coefficients__fao56::mean_plant_height private
Definition at line 68 of file crop_coefficients__fao56.F90.
Referenced by crop_coefficients_fao56_initialize().
lu_soils_csv
integer (kind=c_int) crop_coefficients__fao56::lu_soils_csv private
Definition at line 70 of file crop_coefficients__fao56.F90.