SWB 2.0: maximum_potential_recharge__gridded_data Module Reference
maximum_potential_recharge__gridded_data Module Reference
Module maximum_potential_recharge__gridded_data provides support for adding miscellaneous source and sink terms.
Functions/Subroutines
subroutine, public maximum_potential_recharge_initialize (is_cell_active, landuse_index)
Initialize the routine to establish maximum potential recharge rates.
elemental subroutine, public maximum_potential_recharge_calculate (potential_recharge, rejected_potential_recharge, indx)
Variables
type(data_catalog_entry_t), pointer pmaximum_potential_recharge
real(kind=c_float), dimension(:), allocatable fmaximum_potential_recharge
real(kind=c_float), dimension(:,:), allocatable fmaximum_potential_recharge_array
real(kind=c_float), dimension(:,:), allocatable fmaximum_potential_recharge_table
type(datetime_t), pointer date_of_last_retrieval
Detailed Description
Function/Subroutine Documentation
maximum_potential_recharge_initialize()
subroutine, public maximum_potential_recharge__gridded_data::maximum_potential_recharge_initialize (logical (kind=c_bool), dimension(:,:), intent(in) is_cell_active, integer (kind=c_int), dimension(:), intent(in) landuse_index)
Open gridded data file. Open a NetCDF output file to hold variable output.
Parameters
[in] lActive 2D array of active cells within the model domain.
[in] iLanduseIndex 1D vector of indices corresponding to rows of the landuse lookup table(s).
Determine how many soil groups are present
Determine how many landuse codes are present
Definition at line 50 of file maximum_potential_recharge.F90.
References data_catalog::dat, constants_and_conversions::false, fmaximum_potential_recharge, fmaximum_potential_recharge_array, fmaximum_potential_recharge_table, constants_and_conversions::lfalse, logfiles::logs, parameters::params, pmaximum_potential_recharge, and simulation_datetime::sim_dt.
Referenced by model_domain::model_initialize_maximum_potential_recharge_gridded().
maximum_potential_recharge_calculate()
elemental subroutine, public maximum_potential_recharge__gridded_data::maximum_potential_recharge_calculate (real (kind=c_float), intent(inout) potential_recharge, real (kind=c_float), intent(inout) rejected_potential_recharge, integer (kind=c_int), intent(in) indx)
Definition at line 208 of file maximum_potential_recharge.F90.
References fmaximum_potential_recharge.
Referenced by model_domain::model_calculate_maximum_potential_recharge_gridded().
Variable Documentation
pmaximum_potential_recharge
type (data_catalog_entry_t), pointer maximum_potential_recharge__gridded_data::pmaximum_potential_recharge private
Definition at line 32 of file maximum_potential_recharge.F90.
Referenced by maximum_potential_recharge_initialize().
fmaximum_potential_recharge
real (kind=c_float), dimension(:), allocatable maximum_potential_recharge__gridded_data::fmaximum_potential_recharge private
Definition at line 33 of file maximum_potential_recharge.F90.
Referenced by maximum_potential_recharge_calculate(), and maximum_potential_recharge_initialize().
fmaximum_potential_recharge_array
real (kind=c_float), dimension(:,:), allocatable maximum_potential_recharge__gridded_data::fmaximum_potential_recharge_array private
Definition at line 34 of file maximum_potential_recharge.F90.
Referenced by maximum_potential_recharge_initialize().
fmaximum_potential_recharge_table
real (kind=c_float), dimension(:,:), allocatable maximum_potential_recharge__gridded_data::fmaximum_potential_recharge_table private
Definition at line 35 of file maximum_potential_recharge.F90.
Referenced by maximum_potential_recharge_initialize().
date_of_last_retrieval
type (datetime_t), pointer maximum_potential_recharge__gridded_data::date_of_last_retrieval private
Definition at line 36 of file maximum_potential_recharge.F90.