SWB 2.0: interception__bucket Module Reference
interception__bucket Module Reference
Functions/Subroutines
subroutine, public interception_bucket_initialize (active_cells)
elemental real(kind=c_float) function, public interception_bucket_calculate (iLanduseIndex, fPrecip, fFog, fCanopy_Cover_Fraction, it_is_growing_season)
Variables
integer(kind=c_int), dimension(:), allocatable ilandusecodes
real(kind=c_float), dimension(:), allocatable interception_a_value_growing_season
real(kind=c_float), dimension(:), allocatable interception_b_value_growing_season
real(kind=c_float), dimension(:), allocatable interception_n_value_growing_season
real(kind=c_float), dimension(:), allocatable interception_a_value_nongrowing_season
real(kind=c_float), dimension(:), allocatable interception_b_value_nongrowing_season
real(kind=c_float), dimension(:), allocatable interception_n_value_nongrowing_season
real(kind=c_float), dimension(:), allocatable first_day_of_growing_season
real(kind=c_float), dimension(:), allocatable last_day_of_growing_season
real(kind=c_float), dimension(:), allocatable gdd_first_day_of_growing_season
real(kind=c_float), dimension(:), allocatable killing_frost_temp_last_day_of_growing_season
character(len=2), parameter date_delims = "/-"
Form of the bucket interception: I = A + P*B^n.
real(kind=c_float), parameter nodata_value = -9999._c_float
Function/Subroutine Documentation
subroutine, public interception__bucket::interception_bucket_initialize (logical (kind=c_bool), dimension(:,:), intent(in) active_cells)
Determine how many landuse codes are present
retrieve growing season interception amount: 'a' term
retrieve growing season interception amount: 'b' term
retrieve growing season interception amount: 'n' term
retrieve nongrowing season interception amount: 'a' term
retrieve nongrowing season interception amount: 'b' term
retrieve nongrowing season interception amount: 'n' term
Definition at line 42 of file interception__bucket.F90.
References constants_and_conversions::false, constants_and_conversions::ftinyval, ilandusecodes, interception_a_value_growing_season, interception_a_value_nongrowing_season, interception_b_value_growing_season, interception_b_value_nongrowing_season, interception_n_value_growing_season, interception_n_value_nongrowing_season, parameters::params, constants_and_conversions::true, and exceptions::warn().
Referenced by model_domain::model_initialize_interception_bucket().
elemental real (kind=c_float) function, public interception__bucket::interception_bucket_calculate (integer (kind=c_int), intent(in) iLanduseIndex, real (kind=c_float), intent(in) fPrecip, real (kind=c_float), intent(in) fFog, real (kind=c_float), intent(in) fCanopy_Cover_Fraction, logical (kind=c_bool), intent(in) it_is_growing_season)
Definition at line 346 of file interception__bucket.F90.
References interception_a_value_growing_season, and interception_a_value_nongrowing_season.
Referenced by model_domain::model_calculate_interception_bucket().
Variable Documentation
integer (kind=c_int), dimension(:), allocatable interception__bucket::ilandusecodes private
Definition at line 20 of file interception__bucket.F90.
Referenced by interception_bucket_initialize().
real (kind=c_float), dimension(:), allocatable interception__bucket::interception_a_value_growing_season private
Definition at line 21 of file interception__bucket.F90.
Referenced by interception_bucket_calculate(), and interception_bucket_initialize().
real (kind=c_float), dimension(:), allocatable interception__bucket::interception_b_value_growing_season private
Definition at line 22 of file interception__bucket.F90.
Referenced by interception_bucket_initialize().
real (kind=c_float), dimension(:), allocatable interception__bucket::interception_n_value_growing_season private
Definition at line 23 of file interception__bucket.F90.
Referenced by interception_bucket_initialize().
real (kind=c_float), dimension(:), allocatable interception__bucket::interception_a_value_nongrowing_season private
Definition at line 24 of file interception__bucket.F90.
Referenced by interception_bucket_calculate(), and interception_bucket_initialize().
real (kind=c_float), dimension(:), allocatable interception__bucket::interception_b_value_nongrowing_season private
Definition at line 25 of file interception__bucket.F90.
Referenced by interception_bucket_initialize().
real (kind=c_float), dimension(:), allocatable interception__bucket::interception_n_value_nongrowing_season private
Definition at line 26 of file interception__bucket.F90.
Referenced by interception_bucket_initialize().
real (kind=c_float), dimension(:), allocatable interception__bucket::first_day_of_growing_season private
Definition at line 27 of file interception__bucket.F90.
real (kind=c_float), dimension(:), allocatable interception__bucket::last_day_of_growing_season private
Definition at line 28 of file interception__bucket.F90.
real (kind=c_float), dimension(:), allocatable interception__bucket::gdd_first_day_of_growing_season private
Definition at line 29 of file interception__bucket.F90.
real (kind=c_float), dimension(:), allocatable interception__bucket::killing_frost_temp_last_day_of_growing_season private
Definition at line 30 of file interception__bucket.F90.
character(len=2), parameter interception__bucket::date_delims = "/-" private
Definition at line 36 of file interception__bucket.F90.
real (kind=c_float), parameter interception__bucket::nodata_value = -9999._c_float private
Definition at line 37 of file interception__bucket.F90.