SWB 2.0: data_catalog Module Reference
data_catalog Module Reference
Manage, find, and retrieve data for all DATA_CATALOG_T entries created during the course of a SWB run.
Data Types
type data_catalog_t
Functions/Subroutines
subroutine catalog_set_all_start_year_sub (this, iStartYear)
subroutine catalog_set_all_end_year_sub (this, iEndYear)
subroutine catalog_set_all_proj4_string_sub (this, PROJ4_string)
subroutine catalog_add_entry_sub (this, key, data)
subroutine catalog_delete_entry_sub (this, key)
type(data_catalog_entry_t) function, pointer catalog_get_entry_at_index_fn (this, index)
type(data_catalog_entry_t) function, pointer catalog_find_key_fn (this, key)
type(data_catalog_entry_t) function, pointer catalog_find_next_key_fn (this, key)
subroutine catalog_print_sub (this)
Variables
type(data_catalog_t), public dat
Detailed Description
Function/Subroutine Documentation
subroutine data_catalog::catalog_set_all_start_year_sub (class (data_catalog_t) this, integer (kind=c_int), intent(in) iStartYear) private
Definition at line 62 of file data_catalog.F90.
subroutine data_catalog::catalog_set_all_end_year_sub (class (data_catalog_t) this, integer (kind=c_int), intent(in) iEndYear) private
Definition at line 89 of file data_catalog.F90.
subroutine data_catalog::catalog_set_all_proj4_string_sub (class (data_catalog_t) this, character (len=*), intent(in) PROJ4_string) private
Definition at line 116 of file data_catalog.F90.
subroutine data_catalog::catalog_add_entry_sub (class (data_catalog_t) this, character (len=*), intent(in) key, type (data_catalog_entry_t), pointer data) private
Definition at line 145 of file data_catalog.F90.
subroutine data_catalog::catalog_delete_entry_sub (class (data_catalog_t) this, character (len=*), intent(in) key) private
Definition at line 182 of file data_catalog.F90.
References catalog_find_key_fn().
type (data_catalog_entry_t) function, pointer data_catalog::catalog_get_entry_at_index_fn (class (data_catalog_t) this, integer (kind=c_int), intent(in) index) private
Definition at line 214 of file data_catalog.F90.
type (data_catalog_entry_t) function, pointer data_catalog::catalog_find_key_fn (class (data_catalog_t) this, character (len=*), intent(in) key) private
Definition at line 247 of file data_catalog.F90.
Referenced by catalog_delete_entry_sub().
type (data_catalog_entry_t) function, pointer data_catalog::catalog_find_next_key_fn (class (data_catalog_t) this, character (len=*), intent(in) key) private
Definition at line 275 of file data_catalog.F90.
subroutine data_catalog::catalog_print_sub (class (data_catalog_t) this) private
Definition at line 303 of file data_catalog.F90.
References logfiles::logs.
Variable Documentation
type (data_catalog_t), public data_catalog::dat
Definition at line 55 of file data_catalog.F90.
Referenced by awc__depth_integrated::awc_depth_integrated_read(), awc__gridded_values::awc_gridded_values_read(), model_initialize::create_rooting_depth_table(), direct_recharge__gridded_data::direct_recharge_initialize(), direct_soil_moisture__gridded_data::direct_soil_moisture_initialize(), et__gridded_values::et_gridded_values_initialize(), fog__monthly_grid::fog_monthly_grid_initialize(), model_initialize::initialize_all(), continuous_frozen_ground_index::initialize_continuous_frozen_ground_index(), model_initialize::initialize_generic_grid(), model_initialize::initialize_hydrologic_soil_groups(), model_initialize::initialize_landuse_codes(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), model_initialize::initialize_snow_storage(), model_initialize::initialize_soil_storage(), interception__gash::interception_gash_initialize(), maximum_potential_recharge__gridded_data::maximum_potential_recharge_initialize(), precipitation__method_of_fragments::precipitation_method_of_fragments_calculate(), precipitation__method_of_fragments::precipitation_method_of_fragments_initialize(), model_initialize::read_hydrologic_soil_groups(), model_initialize::read_landuse_codes(), model_initialize::read_polygon_id(), routing__d8::routing_d8_initialize(), runoff__gridded_values::runoff_gridded_values_initialize(), model_domain::set_inactive_cells_sub(), and data_catalog::data_catalog_t::set_startyear().