SWB 2.0: actual_et__thornthwaite_mather_eqns Module Reference
actual_et__thornthwaite_mather_eqns Module Reference
Functions/Subroutines
subroutine, public initialize_actual_et_thornthwaite_mather_eqns (soil_moisture, max_soil_moisture)
elemental subroutine thornthwaite_mather_soil_moisture (soil_moisture, max_soil_moisture, APWL)
Return the current soil moisture given the max soil-water-capacity and current APWL.
elemental subroutine thornthwaite_mather_apwl (APWL, max_soil_moisture, soil_moisture)
Return an updated APWL given the max soil-water-capacity and current soil storage.
subroutine, public calculate_actual_et_thornthwaite_mather_eqns (actual_et, soil_moisture, max_soil_moisture, precipitation, crop_etc, indx)
Variables
real(kind=c_float), parameter near_zero = 1.0e-9_c_float
real(kind=c_float), dimension(:), allocatable accumulated_potential_water_loss
real(kind=c_double), parameter tm_slope_term = 0.478769194198665_c_double
real(kind=c_double), parameter tm_exponent_term = -1.03678439421169_c_double
Function/Subroutine Documentation
subroutine, public actual_et__thornthwaite_mather_eqns::initialize_actual_et_thornthwaite_mather_eqns (real (kind=c_float), dimension(:), intent(in) soil_moisture, real (kind=c_float), dimension(:), intent(in) max_soil_moisture)
Definition at line 21 of file actual_et__thornthwaite_mather_eqns.F90.
References accumulated_potential_water_loss, and thornthwaite_mather_apwl().
Referenced by model_domain::model_initialize_actual_et_thornthwaite_mather_eqns().
elemental subroutine actual_et__thornthwaite_mather_eqns::thornthwaite_mather_soil_moisture (real (kind=c_float), intent(inout) soil_moisture, real (kind=c_float), intent(in) max_soil_moisture, real (kind=c_float), intent(in) APWL) private
Definition at line 41 of file actual_et__thornthwaite_mather_eqns.F90.
References tm_exponent_term, and tm_slope_term.
Referenced by calculate_actual_et_thornthwaite_mather_eqns().
elemental subroutine actual_et__thornthwaite_mather_eqns::thornthwaite_mather_apwl (real (kind=c_float), intent(inout) APWL, real (kind=c_float), intent(in) max_soil_moisture, real (kind=c_float), intent(in) soil_moisture) private
Definition at line 71 of file actual_et__thornthwaite_mather_eqns.F90.
References tm_exponent_term, and tm_slope_term.
Referenced by calculate_actual_et_thornthwaite_mather_eqns(), and initialize_actual_et_thornthwaite_mather_eqns().
subroutine, public actual_et__thornthwaite_mather_eqns::calculate_actual_et_thornthwaite_mather_eqns (real (kind=c_float), intent(inout) actual_et, real (kind=c_float), intent(in) soil_moisture, real (kind=c_float), intent(in) max_soil_moisture, real (kind=c_float), intent(in) precipitation, real (kind=c_float), intent(in) crop_etc, integer (kind=c_int), intent(in) indx)
Definition at line 103 of file actual_et__thornthwaite_mather_eqns.F90.
References accumulated_potential_water_loss, near_zero, thornthwaite_mather_apwl(), and thornthwaite_mather_soil_moisture().
Referenced by model_domain::model_calculate_actual_et_thornthwaite_mather_eqns().
Variable Documentation
real (kind=c_float), parameter actual_et__thornthwaite_mather_eqns::near_zero = 1.0e-9_c_float private
Definition at line 12 of file actual_et__thornthwaite_mather_eqns.F90.
Referenced by calculate_actual_et_thornthwaite_mather_eqns().
real (kind=c_float), dimension(:), allocatable actual_et__thornthwaite_mather_eqns::accumulated_potential_water_loss private
Definition at line 13 of file actual_et__thornthwaite_mather_eqns.F90.
Referenced by calculate_actual_et_thornthwaite_mather_eqns(), and initialize_actual_et_thornthwaite_mather_eqns().
real (kind=c_double), parameter actual_et__thornthwaite_mather_eqns::tm_slope_term = 0.478769194198665_c_double private
Definition at line 15 of file actual_et__thornthwaite_mather_eqns.F90.
Referenced by thornthwaite_mather_apwl(), and thornthwaite_mather_soil_moisture().
real (kind=c_double), parameter actual_et__thornthwaite_mather_eqns::tm_exponent_term = -1.03678439421169_c_double private
Definition at line 16 of file actual_et__thornthwaite_mather_eqns.F90.
Referenced by thornthwaite_mather_apwl(), and thornthwaite_mather_soil_moisture().