SWB 2.0: string_list Module Reference
string_list Module Reference
Data Types
interface assignment(=)
interface create_list
type string_list_element_t
type string_list_t
Functions/Subroutines
subroutine list_append_int_sub (this, iValue)
subroutine list_set_auto_cleanup_sub (this, autocleanup)
subroutine assign_string_list_to_string_list_sub (slList2, slList1)
subroutine list_append_string_sub (this, sText)
character(len=:) function, allocatable list_get_value_at_index_fn (this, iIndex)
character(len=:) function, allocatable list_get_values_in_range_fn (this, iStartIndex, iEndIndex)
Iterate over a range of indices; return a space-delimited string comprised of the values.
subroutine list_print_sub (this, iLU)
character(len=:) function, allocatable list_all_fn (this)
character(len=:) function, allocatable list_all_delimited_fn (this, delimiter)
real(kind=c_float) function, dimension(:), allocatable list_return_all_as_float_fn (this)
character(len=64) function, dimension(:), allocatable list_return_all_as_character_fn (this, null_terminated)
integer(kind=c_int) function, dimension(:), allocatable list_return_all_as_int_fn (this)
logical(kind=c_bool) function, dimension(:), allocatable list_return_all_as_logical_fn (this)
type(string_list_t) function list_from_delimited_string_fn (sText1)
logical(kind=c_bool) function list_is_string_in_list_fn (this, sChar)
integer(kind=c_int) function list_return_count_of_matching_string_fn (this, sChar)
integer(kind=c_int) function, dimension(:), allocatable list_return_position_of_matching_string_fn (this, sChar)
type(string_list_t) function list_subset_partial_matches_fn (this, sChar)
subroutine list_finalize_sub (this)
subroutine list_items_deallocate_all_sub (this)
Function/Subroutine Documentation
subroutine string_list::list_append_int_sub (class (string_list_t), intent(inout) this, integer (kind=c_int), intent(in) iValue) private
Definition at line 82 of file string_list.F90.
subroutine string_list::list_set_auto_cleanup_sub (class (string_list_t), intent(inout) this, logical (kind=c_bool), intent(in) autocleanup) private
Definition at line 93 of file string_list.F90.
subroutine string_list::assign_string_list_to_string_list_sub (type (string_list_t), intent(out) slList2, type (string_list_t), intent(in) slList1) private
Definition at line 104 of file string_list.F90.
subroutine string_list::list_append_string_sub (class (string_list_t), intent(inout) this, character (len=*), intent(in) sText) private
Definition at line 126 of file string_list.F90.
References exceptions::die().
character (len=:) function, allocatable string_list::list_get_value_at_index_fn (class (string_list_t), intent(in) this, integer (kind=c_int), intent(in) iIndex) private
Definition at line 168 of file string_list.F90.
character (len=:) function, allocatable string_list::list_get_values_in_range_fn (class (string_list_t), intent(in) this, integer (kind=c_int), intent(in) iStartIndex, integer (kind=c_int), intent(in) iEndIndex) private
Definition at line 208 of file string_list.F90.
subroutine string_list::list_print_sub (class (string_list_t), intent(in) this, integer (kind=c_int), optional iLU) private
Definition at line 250 of file string_list.F90.
character (len=:) function, allocatable string_list::list_all_fn (class (string_list_t), intent(in) this)
Definition at line 285 of file string_list.F90.
character (len=:) function, allocatable string_list::list_all_delimited_fn (class (string_list_t), intent(in) this, character (len=*), intent(in) delimiter)
Definition at line 319 of file string_list.F90.
real (kind=c_float) function, dimension(:), allocatable string_list::list_return_all_as_float_fn (class (string_list_t), intent(in) this)
Definition at line 366 of file string_list.F90.
References exceptions::die().
character (len=64) function, dimension(:), allocatable string_list::list_return_all_as_character_fn (class (string_list_t), intent(in) this, logical (kind=c_bool), optional null_terminated) private
Definition at line 395 of file string_list.F90.
References exceptions::die(), and constants_and_conversions::false.
integer (kind=c_int) function, dimension(:), allocatable string_list::list_return_all_as_int_fn (class (string_list_t), intent(in) this) private
Definition at line 437 of file string_list.F90.
References exceptions::die().
logical (kind=c_bool) function, dimension(:), allocatable string_list::list_return_all_as_logical_fn (class (string_list_t), intent(in) this) private
Definition at line 467 of file string_list.F90.
References exceptions::die().
type (string_list_t) function string_list::list_from_delimited_string_fn (character (len=*), intent(in) sText1) private
Definition at line 497 of file string_list.F90.
logical (kind=c_bool) function string_list::list_is_string_in_list_fn (class (string_list_t), intent(in) this, character (len=*), intent(in) sChar) private
Definition at line 524 of file string_list.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
integer (kind=c_int) function string_list::list_return_count_of_matching_string_fn (class (string_list_t), intent(in) this, character (len=*), intent(in) sChar) private
Definition at line 547 of file string_list.F90.
integer (kind=c_int) function, dimension(:), allocatable string_list::list_return_position_of_matching_string_fn (class (string_list_t), intent(in) this, character (len=*), intent(in) sChar) private
Definition at line 582 of file string_list.F90.
References exceptions::die().
type (string_list_t) function string_list::list_subset_partial_matches_fn (class (string_list_t), intent(in) this, character (len=*), intent(in) sChar) private
Definition at line 634 of file string_list.F90.
subroutine string_list::list_finalize_sub (type (string_list_t) this) private
Definition at line 670 of file string_list.F90.
Referenced by string_list::string_list_t::list_finalize_sub().
subroutine string_list::list_items_deallocate_all_sub (class (string_list_t), intent(inout) this) private
Definition at line 680 of file string_list.F90.