SWB 2.0: simulation_datetime Module Reference
simulation_datetime Module Reference
Data Types
type date_range_t
Functions/Subroutines
real(kind=c_float) function percent_complete_fn (this)
subroutine increment_by_one_day_sub (this)
Variables
type(date_range_t), public sim_dt
Function/Subroutine Documentation
real (kind=c_float) function simulation_datetime::percent_complete_fn (class (date_range_t), intent(inout) this) private
Definition at line 34 of file simulation_datetime.F90.
subroutine simulation_datetime::increment_by_one_day_sub (class (date_range_t), intent(inout) this) private
Definition at line 44 of file simulation_datetime.F90.
References datetime::day_of_year().
Variable Documentation
type (date_range_t), public simulation_datetime::sim_dt
Definition at line 29 of file simulation_datetime.F90.
Referenced by direct_recharge__gridded_data::direct_recharge_calculate(), direct_soil_moisture__gridded_data::direct_soil_moisture_calculate(), et__gridded_values::et_gridded_values_calculate(), fog__monthly_grid::fog_monthly_grid_calculate(), fog__monthly_grid::fog_monthly_grid_initialize(), model_domain::get_climate_data(), growing_degree_day::growing_degree_day_calculate(), growing_season::growing_season_update(), model_initialize::initialize_start_and_end_dates(), model_iterate::iterate_over_simulation_days(), maximum_potential_recharge__gridded_data::maximum_potential_recharge_initialize(), polygon_summarize::perform_polygon_summarize(), precipitation__method_of_fragments::precipitation_method_of_fragments_calculate(), runoff__gridded_values::runoff_gridded_values_update_ratios(), precipitation__method_of_fragments::update_fragments(), runoff__curve_number::update_previous_5_day_rainfall(), and precipitation__method_of_fragments::update_random_values().