SWB 2.0: model_initialize Module Reference
model_initialize Module Reference
Data Types
type gridded_datasets_t
type methods_list_t
Functions/Subroutines
subroutine, public initialize_all (output_prefix, output_dirname, data_dirname)
subroutine initialize_soils_landuse_awc_flowdir_values ()
Initialize soils, landuse, and available water content values.
subroutine initialize_ancillary_values ()
subroutine set_data_directory (data_dirname)
subroutine initialize_snow_storage ()
subroutine initialize_soil_storage ()
subroutine initialize_percent_pervious ()
subroutine initialize_percent_canopy_cover
subroutine create_rooting_depth_table
subroutine initialize_hydrologic_soil_groups
subroutine read_hydrologic_soil_groups
subroutine read_polygon_id ()
subroutine read_landuse_codes
subroutine, public write_control_file (sFilename, sGridSpecification, slExtraDirectives)
subroutine, public read_control_file (sFilename)
subroutine initialize_generic_grid (sKey, lOptional, iDataType)
Generic routine to handle intake of gridded data.
subroutine initialize_grid_options ()
subroutine initialize_start_and_end_dates ()
subroutine initialize_parameter_tables ()
Find any parameter tables specified in the control file; process and store contents.
subroutine initialize_generic_method (sKey, lOptional)
subroutine initialize_latitude ()
subroutine initialize_landuse_codes ()
Match landuse codes from table with those contained in the gridded landuse.
subroutine initialize_surface_storage_max ()
Variables
integer(kind=c_int), parameter number_of_known_grids = 40
integer(kind=c_int), parameter number_of_known_methods = 14
type(gridded_datasets_t), dimension(number_of_known_grids), parameter known_grids = [ GRIDDED_DATASETS_T("PRECIPITATION ", lFALSE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("TMIN ", lFALSE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("TMAX ", lFALSE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("AVAILABLE_WATER_CONTENT ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("POTENTIAL_ET ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("SOLAR_RADIATION ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("WIND_SPEED ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("RAINFALL_ZONE ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("FLOW_DIRECTION ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("FOG_RATIO ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("LAND_USE ", lFALSE, DATATYPE_INT), GRIDDED_DATASETS_T("SOILS_CODE ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("HYDROLOGIC_SOILS_GROUP ", lFALSE, DATATYPE_INT), GRIDDED_DATASETS_T("INITIAL_PERCENT_SOIL_MOISTURE ", lFALSE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("INITIAL_SNOW_COVER_STORAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("INITIAL_CONTINUOUS_FROZEN_GROUND_INDEX", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("PERCENT_CANOPY_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("PERCENT_PERVIOUS_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("PERCENT_IMPERVIOUS_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("FRACTION_CANOPY_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("FRACTION_PERVIOUS_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("FRACTION_IMPERVIOUS_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("STEMFLOW_FRACTION ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("EVAPORATION_TO_RAINFALL_RATIO ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("RAINFALL_ADJUST_FACTOR ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("CESSPOOL_LEAKAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("STORM_DRAIN_LEAKAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("WATER_BODY_LEAKAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("WATER_MAIN_LEAKAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("DISPOSAL_WELL_DISCHARGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("ANNUAL_DIRECT_RECHARGE_RATE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("ANNUAL_SEPTIC_DISCHARGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("SEPTIC_DISCHARGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("RUNOFF_ZONE ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("POLYGON_ID ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("SOIL_STORAGE_MAX ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("PLANT_AVAILABLE_WATER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("MAXIMUM_POTENTIAL_RECHARGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("IRRIGATION_MASK ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("RELATIVE_HUMIDITY ", lTRUE, DATATYPE_FLOAT) ]
type(methods_list_t), dimension(number_of_known_methods), parameter known_methods = [ METHODS_LIST_T("INTERCEPTION ", lFALSE), METHODS_LIST_T("EVAPOTRANSPIRATION ", lFALSE), METHODS_LIST_T("RUNOFF ", lFALSE), METHODS_LIST_T("PRECIPITATION ", lFALSE), METHODS_LIST_T("FOG ", lTRUE), METHODS_LIST_T("AVAILABLE_WATER_CONTENT", lTRUE), METHODS_LIST_T("SOIL_STORAGE_MAX ", lTRUE), METHODS_LIST_T("SOIL_MOISTURE ", lFALSE), METHODS_LIST_T("IRRIGATION ", lTRUE), METHODS_LIST_T("CROP_COEFFICIENT ", lTRUE), METHODS_LIST_T("DIRECT_RECHARGE ", lTRUE), METHODS_LIST_T("DIRECT_SOIL_MOISTURE ", lTRUE), METHODS_LIST_T("FLOW_ROUTING ", lFALSE), METHODS_LIST_T("DUMP_VARIABLES ", lTRUE) ]
type(general_grid_t), pointer pcoord_grd
Function/Subroutine Documentation
initialize_all()
subroutine, public model_initialize::initialize_all (character (len=*), intent(in) output_prefix, character (len=*), intent(in) output_dirname, character (len=*), intent(in) data_dirname)
Definition at line 109 of file model_initialize.F90.
References dictionary::cf_dict, exceptions::check_for_fatal_warnings(), data_catalog::dat, grid::grid_set_output_directory_name(), initialize_ancillary_values(), initialize_generic_grid(), initialize_generic_method(), initialize_grid_options(), output::initialize_output(), initialize_parameter_tables(), initialize_soils_landuse_awc_flowdir_values(), initialize_start_and_end_dates(), known_grids, known_methods, model_domain::model, set_data_directory(), output::set_output_directory(), and output::set_output_prefix().
Referenced by main().
initialize_soils_landuse_awc_flowdir_values()
subroutine model_initialize::initialize_soils_landuse_awc_flowdir_values () private
Rather than read the raw values and initialize the SWB variables in one step, we have two steps:
read raw;
initialize SWB variables.
Two steps are needed because the call to "set_inactive_cells" requires access to the "raw" values, not the SWB variables. Basically any cell with negative values found in the landuse, soils groups, or awc grids results in that cell being inactivated. Once the complete collection of active cells is found, the SWB variables can be initialized.
Definition at line 201 of file model_initialize.F90.
References create_rooting_depth_table(), initialize_hydrologic_soil_groups(), initialize_landuse_codes(), read_hydrologic_soil_groups(), read_landuse_codes(), and model_domain::rooting_depth_max.
Referenced by initialize_all().
initialize_ancillary_values()
subroutine model_initialize::initialize_ancillary_values ()
Definition at line 245 of file model_initialize.F90.
References initialize_latitude(), initialize_percent_canopy_cover(), initialize_percent_pervious(), initialize_snow_storage(), initialize_soil_storage(), initialize_surface_storage_max(), model_domain::model, and storm_drain_capture::storm_drain_capture_initialize().
Referenced by initialize_all().
set_data_directory()
subroutine model_initialize::set_data_directory (character(len=*), intent(in) data_dirname) private
Definition at line 269 of file model_initialize.F90.
References constants_and_conversions::data_directory_name.
Referenced by initialize_all().
initialize_snow_storage()
subroutine model_initialize::initialize_snow_storage () private
Definition at line 280 of file model_initialize.F90.
References data_catalog::dat, constants_and_conversions::fzero, constants_and_conversions::lfalse, constants_and_conversions::ltrue, model_domain::model, and exceptions::warn().
Referenced by initialize_ancillary_values().
initialize_soil_storage()
subroutine model_initialize::initialize_soil_storage () private
Definition at line 320 of file model_initialize.F90.
References data_catalog::dat, constants_and_conversions::fzero, constants_and_conversions::ltrue, model_domain::model, and exceptions::warn().
Referenced by initialize_ancillary_values().
initialize_percent_pervious()
subroutine model_initialize::initialize_percent_pervious () private
Definition at line 357 of file model_initialize.F90.
References data_catalog::dat, exceptions::die(), constants_and_conversions::fzero, grid::grid_datatype_real, grid::grid_destroy(), grid::grid_writearcgrid(), constants_and_conversions::ltrue, model_domain::model, data_catalog_entry::pgrd, and exceptions::warn().
Referenced by initialize_ancillary_values().
initialize_percent_canopy_cover()
subroutine model_initialize::initialize_percent_canopy_cover () private
Definition at line 444 of file model_initialize.F90.
References data_catalog::dat, exceptions::die(), constants_and_conversions::fzero, grid::grid_datatype_real, grid::grid_destroy(), grid::grid_writearcgrid(), constants_and_conversions::ltrue, model_domain::model, data_catalog_entry::pgrd, and exceptions::warn().
Referenced by initialize_ancillary_values().
create_rooting_depth_table()
subroutine model_initialize::create_rooting_depth_table () private
Determine how many soil groups are present
Determine how many landuse codes are present
Definition at line 510 of file model_initialize.F90.
References data_catalog::dat, grid::grid_datatype_real, grid::grid_destroy(), grid::grid_writearcgrid(), constants_and_conversions::lfalse, logfiles::logs, parameters::params, model_domain::rooting_depth_max, and constants_and_conversions::true.
Referenced by initialize_soils_landuse_awc_flowdir_values().
initialize_hydrologic_soil_groups()
subroutine model_initialize::initialize_hydrologic_soil_groups ()
Definition at line 628 of file model_initialize.F90.
References data_catalog::dat, exceptions::die(), logfiles::logs, and model_domain::model.
Referenced by initialize_soils_landuse_awc_flowdir_values().
read_hydrologic_soil_groups()
subroutine model_initialize::read_hydrologic_soil_groups () private
Definition at line 667 of file model_initialize.F90.
References data_catalog::dat, grid::grid_writearcgrid(), constants_and_conversions::ltrue, and exceptions::warn().
Referenced by initialize_soils_landuse_awc_flowdir_values().
read_polygon_id()
subroutine model_initialize::read_polygon_id () private
Definition at line 692 of file model_initialize.F90.
References data_catalog::dat, grid::grid_datatype_real, grid::grid_destroy(), grid::grid_writearcgrid(), constants_and_conversions::ltrue, and model_domain::model.
read_landuse_codes()
subroutine model_initialize::read_landuse_codes () private
Definition at line 807 of file model_initialize.F90.
References data_catalog::dat, grid::grid_writearcgrid(), constants_and_conversions::ltrue, and exceptions::warn().
Referenced by initialize_soils_landuse_awc_flowdir_values().
write_control_file()
subroutine, public model_initialize::write_control_file (character (len=*), intent(in) sFilename, character (len=*), intent(in), optional sGridSpecification, type (string_list_t), intent(in), optional slExtraDirectives)
Definition at line 832 of file model_initialize.F90.
References dictionary::cf_dict.
read_control_file()
subroutine, public model_initialize::read_control_file (character (len=*), intent(in) sFilename)
Definition at line 890 of file model_initialize.F90.
References dictionary::cf_dict, dictionary::cf_entry, and constants_and_conversions::false.
Referenced by main().
initialize_generic_grid()
subroutine model_initialize::initialize_generic_grid (character (len=*), intent(in) sKey, logical (kind=c_bool), intent(in) lOptional, integer (kind=c_int), intent(in) iDataType) private
Parameters
[in] sKey Name for the data type being processed.
[in] lOptional If lOptional is TRUE, kill model run eventually IF sKey does not match a known data type.
[in] iDataType Datatype as defined in constants_and-conversion.F90
This routine accepts a data grid type, for example, "PRECIPITATION", and attempts to handle all related control file directives associated with MODEL data type. In MODEL way, a new gridded data type may be added simply by extending the list of known data types to the list defined in the module variable KNOWN_TYPES.
Definition at line 969 of file model_initialize.F90.
References dictionary::cf_dict, data_catalog::dat, constants_and_conversions::datatype_float, constants_and_conversions::datatype_int, exceptions::die(), data_catalog_entry::file_template_capitalized_monthname, data_catalog_entry::file_template_lowercase_monthname, data_catalog_entry::file_template_uppercase_monthname, constants_and_conversions::lfalse, logfiles::logs, constants_and_conversions::ltrue, data_catalog_entry::missing_values_replace_with_mean, data_catalog_entry::missing_values_zero_out, and exceptions::warn().
Referenced by initialize_all().
initialize_grid_options()
subroutine model_initialize::initialize_grid_options () private
Definition at line 1240 of file model_initialize.F90.
References constants_and_conversions::bnds, dictionary::cf_dict, exceptions::die(), logfiles::logs, constants_and_conversions::ltrue, model_domain::model, and exceptions::warn().
Referenced by initialize_all().
initialize_start_and_end_dates()
subroutine model_initialize::initialize_start_and_end_dates () private
Definition at line 1327 of file model_initialize.F90.
References dictionary::cf_dict, datetime::day_of_year(), constants_and_conversions::lfalse, logfiles::logs, constants_and_conversions::ltrue, simulation_datetime::sim_dt, and exceptions::warn().
Referenced by initialize_all().
initialize_parameter_tables()
subroutine model_initialize::initialize_parameter_tables () private
Any control file entry that contains the text "LOOKUP_TABLE" is assumed to specify a parameter table that needs to be read in and processed.
Note
The entries given in the files are implicitly assumed to be in sorted order. For example, if the parameters pertain to landuse codes, it is assumed that all table values are given in order from lowest to highest landuse code.
Definition at line 1432 of file model_initialize.F90.
References dictionary::cf_dict, constants_and_conversions::lfalse, logfiles::logs, constants_and_conversions::ltrue, parameters::params, parameters::params_dict, and exceptions::warn().
Referenced by initialize_all().
initialize_generic_method()
subroutine model_initialize::initialize_generic_method (character (len=*), intent(in) sKey, logical (kind=c_bool), intent(in) lOptional) private
Definition at line 1510 of file model_initialize.F90.
References dictionary::cf_dict, constants_and_conversions::lfalse, logfiles::logs, constants_and_conversions::ltrue, model_domain::model, and exceptions::warn().
Referenced by initialize_all().
initialize_latitude()
subroutine model_initialize::initialize_latitude () private
Definition at line 1587 of file model_initialize.F90.
References grid::grid_datatype_real, grid::grid_destroy(), grid::grid_populatexy(), grid::grid_transform(), grid::grid_writearcgrid(), model_domain::model, pcoord_grd, and data_catalog_entry::pgrd.
Referenced by initialize_ancillary_values().
initialize_landuse_codes()
subroutine model_initialize::initialize_landuse_codes () private
This routine loops through all known
Determine how many landuse codes are present
Definition at line 1630 of file model_initialize.F90.
References data_catalog::dat, exceptions::die(), constants_and_conversions::lfalse, logfiles::logs, constants_and_conversions::ltrue, model_domain::model, parameters::params, constants_and_conversions::true, and exceptions::warn().
Referenced by initialize_soils_landuse_awc_flowdir_values().
initialize_surface_storage_max()
subroutine model_initialize::initialize_surface_storage_max () private
Determine how many landuse codes are present
Definition at line 1711 of file model_initialize.F90.
References constants_and_conversions::false, model_domain::model, and parameters::params.
Referenced by initialize_ancillary_values().
Variable Documentation
number_of_known_grids
integer (kind=c_int), parameter model_initialize::number_of_known_grids = 40 private
Definition at line 40 of file model_initialize.F90.
number_of_known_methods
integer (kind=c_int), parameter model_initialize::number_of_known_methods = 14 private
Definition at line 41 of file model_initialize.F90.
known_grids
type (gridded_datasets_t), dimension(number_of_known_grids), parameter model_initialize::known_grids = [ GRIDDED_DATASETS_T("PRECIPITATION ", lFALSE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("TMIN ", lFALSE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("TMAX ", lFALSE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("AVAILABLE_WATER_CONTENT ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("POTENTIAL_ET ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("SOLAR_RADIATION ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("WIND_SPEED ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("RAINFALL_ZONE ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("FLOW_DIRECTION ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("FOG_RATIO ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("LAND_USE ", lFALSE, DATATYPE_INT), GRIDDED_DATASETS_T("SOILS_CODE ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("HYDROLOGIC_SOILS_GROUP ", lFALSE, DATATYPE_INT), GRIDDED_DATASETS_T("INITIAL_PERCENT_SOIL_MOISTURE ", lFALSE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("INITIAL_SNOW_COVER_STORAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("INITIAL_CONTINUOUS_FROZEN_GROUND_INDEX", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("PERCENT_CANOPY_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("PERCENT_PERVIOUS_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("PERCENT_IMPERVIOUS_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("FRACTION_CANOPY_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("FRACTION_PERVIOUS_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("FRACTION_IMPERVIOUS_COVER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("STEMFLOW_FRACTION ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("EVAPORATION_TO_RAINFALL_RATIO ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("RAINFALL_ADJUST_FACTOR ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("CESSPOOL_LEAKAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("STORM_DRAIN_LEAKAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("WATER_BODY_LEAKAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("WATER_MAIN_LEAKAGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("DISPOSAL_WELL_DISCHARGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("ANNUAL_DIRECT_RECHARGE_RATE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("ANNUAL_SEPTIC_DISCHARGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("SEPTIC_DISCHARGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("RUNOFF_ZONE ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("POLYGON_ID ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("SOIL_STORAGE_MAX ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("PLANT_AVAILABLE_WATER ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("MAXIMUM_POTENTIAL_RECHARGE ", lTRUE, DATATYPE_FLOAT), GRIDDED_DATASETS_T("IRRIGATION_MASK ", lTRUE, DATATYPE_INT), GRIDDED_DATASETS_T("RELATIVE_HUMIDITY ", lTRUE, DATATYPE_FLOAT) ] private
Definition at line 43 of file model_initialize.F90.
Referenced by initialize_all().
known_methods
type (methods_list_t), dimension(number_of_known_methods), parameter model_initialize::known_methods = [ METHODS_LIST_T("INTERCEPTION ", lFALSE), METHODS_LIST_T("EVAPOTRANSPIRATION ", lFALSE), METHODS_LIST_T("RUNOFF ", lFALSE), METHODS_LIST_T("PRECIPITATION ", lFALSE), METHODS_LIST_T("FOG ", lTRUE), METHODS_LIST_T("AVAILABLE_WATER_CONTENT", lTRUE), METHODS_LIST_T("SOIL_STORAGE_MAX ", lTRUE), METHODS_LIST_T("SOIL_MOISTURE ", lFALSE), METHODS_LIST_T("IRRIGATION ", lTRUE), METHODS_LIST_T("CROP_COEFFICIENT ", lTRUE), METHODS_LIST_T("DIRECT_RECHARGE ", lTRUE), METHODS_LIST_T("DIRECT_SOIL_MOISTURE ", lTRUE), METHODS_LIST_T("FLOW_ROUTING ", lFALSE), METHODS_LIST_T("DUMP_VARIABLES ", lTRUE) ] private
Definition at line 86 of file model_initialize.F90.
Referenced by initialize_all().
pcoord_grd
type (general_grid_t), pointer model_initialize::pcoord_grd private
Definition at line 104 of file model_initialize.F90.
Referenced by initialize_latitude().