SWB 2.0: continuous_frozen_ground_index Module Reference
continuous_frozen_ground_index Module Reference
Functions/Subroutines
subroutine, public initialize_continuous_frozen_ground_index (cfgi, active_cells)
elemental subroutine, public update_continuous_frozen_ground_index (fCFGI, fTMax_F, fTMin_F, fSnowCover)
Update the continuous frozen ground index (CFGI) for a cell.
Variables
real(kind=c_float), public cfgi_ll = 55.
: make these into user-accessible variables
real(kind=c_float), public cfgi_ul = 83.
Function/Subroutine Documentation
subroutine, public continuous_frozen_ground_index::initialize_continuous_frozen_ground_index (real (kind=c_float), dimension(:), intent(inout) cfgi, logical (kind=c_bool), dimension(:,:), intent(in) active_cells)
Definition at line 24 of file continuous_frozen_ground_index.F90.
References data_catalog::dat, constants_and_conversions::fzero, constants_and_conversions::lfalse, constants_and_conversions::ltrue, and exceptions::warn().
Referenced by model_domain::model_initialize_continuous_frozen_ground_index().
elemental subroutine, public continuous_frozen_ground_index::update_continuous_frozen_ground_index (real (kind=c_float), intent(inout) fCFGI, real (kind=c_float), intent(in) fTMax_F, real (kind=c_float), intent(in) fTMin_F, real (kind=c_float), intent(in) fSnowCover)
Computes the continuous frozen ground index
Parameters
[in,out] rCFGI Continuous frozen ground index to be updated.
[in] rTAvg_F Mean daily air temperature, in
Note
Implemented as per Molnau and Bissel (1983).
Molnau, M. and Bissell, V.C., 1983, A continuous frozen ground index for flood forecasting: In Proceedings 51st Annual Meeting Western Snow Conference, 109–119, Canadian Water Resources Assoc. Cambridge, Ont.
Definition at line 71 of file continuous_frozen_ground_index.F90.
Referenced by model_domain::model_calculate_continuous_frozen_ground_index().
Variable Documentation
real (kind=c_float), public continuous_frozen_ground_index::cfgi_ll = 55.
Definition at line 18 of file continuous_frozen_ground_index.F90.
Referenced by runoff__curve_number::prob_runoff_enhancement(), and runoff__curve_number::update_curve_number_fn().
real (kind=c_float), public continuous_frozen_ground_index::cfgi_ul = 83.
Definition at line 19 of file continuous_frozen_ground_index.F90.
Referenced by runoff__curve_number::prob_runoff_enhancement().