SWB 2.0: precipitation__method_of_fragments Module Reference
precipitation__method_of_fragments Module Reference
Module precipitation__method_of_fragments provides support for creating synthetic daily precipitation given grids of monthly sum precipitation and a "fragments" file.
Data Types
type fragments_sequence_t
Data structure to hold static (pre-calculated) fragment selection numbers.
type fragments_set_t
Data structure to hold the current active rainfall fragments for a particular rain gage zone.
type fragments_t
Data structure that holds a single line of data from the input rainfall fragments file.
type ptr_fragments_t
Pointer to a rainfall fragments data structure.
Functions/Subroutines
subroutine, public precipitation_method_of_fragments_initialize (lActive)
Initialize method of fragments.
subroutine process_fragment_sets ()
subroutine, public read_daily_fragments (sFilename)
subroutine read_fragments_sequence (sFilename)
subroutine update_fragments (lShuffle)
Update rainfall fragments on daily basis.
subroutine update_random_values ()
subroutine, public precipitation_method_of_fragments_calculate (lActive)
Variables
integer(kind=c_int), dimension(:), allocatable, public rain_gage_id
Module variable that holds the rainfall gage (zone) number.
real(kind=c_float), dimension(:), allocatable, public fragment_value
Module variable that holds the current day's rainfall fragment value.
integer(kind=c_int), public simulation_number = 1
Module variable indicating which "simulation number" is active Only has meaning if the rainfall fragments are being applied via a predetermined sequence file.
real(kind=c_float), dimension(:), allocatable, public rainfall_adjust_factor
Module variable that holds the rainfall adjustment factor.
real(kind=c_float), dimension(:), allocatable random_values
Module variable that holds a sequence of random numbers associated with the selection of the fragment set to use.
logical(kind=c_bool), dimension(:), allocatable sequence_selection
Module level variable used to create subsets of the FRAGMENT_SEQUENCES file.
logical(kind=c_bool) random_fragment_sequences = .true._c_bool
Module variable detemining whether fragment sequences are chosen at random or selected from an external file.
type(fragments_t), dimension(:), allocatable, target, public fragments
Array of all fragments read in from the rainfall fragments file.
type(ptr_fragments_t), dimension(:), allocatable current_fragments
Subset of rainfall fragments file pointing to the currently active fragments.
type(fragments_set_t), dimension(:), allocatable, public fragments_sets
Array of fragments sets; fragments sets include indices to the start record associated with the fragment for each month.
type(fragments_sequence_t), pointer pfragments_sequence
Pointer to all or some of the FRAGMENTS_SEQUENCE array.
type(fragments_sequence_t), dimension(:), allocatable, public fragments_sequence
Array of fragment sequence sets.
type(data_catalog_entry_t), pointer prainfall_adjust_factor
integer(kind=c_int) lu_fragments_echo
Detailed Description
The fragments file is generated from observations at discrete locations, the values of which range from 0 to 1, and the sum of which is 1. The fragment value is simply the daily observed precipitation value divided by the monthly sum of all observed precipitation values for that station.
In addition, this routine accepts another set of rainfall adjustment grids, needed in order to ensure the resulting precipitation totals fall in line with other published values, in the development case, the Rainfall Atlas of Hawaii.
Function/Subroutine Documentation
subroutine, public precipitation__method_of_fragments::precipitation_method_of_fragments_initialize (logical (kind=c_bool), dimension(:,:), intent(in) lActive)
This routine accesses the "RAINFALL_ZONE" gridded data object and calls the routine to read in the rainfall fragments file. Values of RAINFALL_ZONE are stored in a module variable RAIN_GAGE_ID for future reference.
[in] lActive 2-D boolean array defining active and inactive cells
Now the fragments file is in memory. Create an ancillary data structure to keep track of which records correspond to various rain zones
Definition at line 127 of file precipitation__method_of_fragments.F90.
References dictionary::cf_dict, current_fragments, data_catalog::dat, exceptions::die(), fragment_value, fragments, fragments_sequence, fragments_sets, lu_fragments_echo, process_fragment_sets(), rain_gage_id, rainfall_adjust_factor, random_fragment_sequences, random_values, read_daily_fragments(), read_fragments_sequence(), sequence_selection, and simulation_number.
Referenced by model_domain::model_initialize_precip_method_of_fragments().
subroutine precipitation__method_of_fragments::process_fragment_sets () private
Definition at line 205 of file precipitation__method_of_fragments.F90.
References fragments, fragments_sets, constants_and_conversions::lfalse, and logfiles::logs.
Referenced by precipitation_method_of_fragments_initialize().
subroutine, public precipitation__method_of_fragments::read_daily_fragments (character (len=*), intent(in) sFilename)
Definition at line 278 of file precipitation__method_of_fragments.F90.
References exceptions::die(), fragments, and logfiles::logs.
Referenced by precipitation_method_of_fragments_initialize().
subroutine precipitation__method_of_fragments::read_fragments_sequence (character (len=*), intent(in) sFilename) private
Definition at line 379 of file precipitation__method_of_fragments.F90.
References exceptions::die(), fragments_sequence, constants_and_conversions::lfalse, and logfiles::logs.
Referenced by precipitation_method_of_fragments_initialize().
subroutine precipitation__method_of_fragments::update_fragments (logical (kind=c_bool), intent(in) lShuffle) private
If called when lShuffle is TRUE: 1) update random values 2) random values are used to select the next active fragment set for the current RainGageZone
Each time the routine is called, the appropriate fragment is selected from the current active fragement set and is assigned to all cells that share a common RainGageZone
Definition at line 523 of file precipitation__method_of_fragments.F90.
References current_fragments, exceptions::die(), fragment_value, fragments, fragments_sets, constants_and_conversions::lfalse, logfiles::logs, lu_fragments_echo, rain_gage_id, random_values, simulation_datetime::sim_dt, and update_random_values().
Referenced by precipitation_method_of_fragments_calculate().
subroutine precipitation__method_of_fragments::update_random_values () private
Definition at line 628 of file precipitation__method_of_fragments.F90.
References fragments_sequence, random_fragment_sequences, random_values, simulation_datetime::sim_dt, and simulation_number.
Referenced by update_fragments().
subroutine, public precipitation__method_of_fragments::precipitation_method_of_fragments_calculate (logical (kind=c_bool), dimension(:,:), intent(in) lActive)
Definition at line 669 of file precipitation__method_of_fragments.F90.
References data_catalog::dat, exceptions::die(), fragments, constants_and_conversions::lfalse, constants_and_conversions::ltrue, prainfall_adjust_factor, rainfall_adjust_factor, simulation_datetime::sim_dt, and update_fragments().
Variable Documentation
integer (kind=c_int), dimension(:), allocatable, public precipitation__method_of_fragments::rain_gage_id
Definition at line 41 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), and update_fragments().
real (kind=c_float), dimension(:), allocatable, public precipitation__method_of_fragments::fragment_value
Definition at line 44 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), and update_fragments().
integer (kind=c_int), public precipitation__method_of_fragments::simulation_number = 1
Definition at line 49 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), and update_random_values().
real (kind=c_float), dimension(:), allocatable, public precipitation__method_of_fragments::rainfall_adjust_factor
Definition at line 52 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_calculate(), and precipitation_method_of_fragments_initialize().
real (kind=c_float), dimension(:), allocatable precipitation__method_of_fragments::random_values private
Definition at line 56 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), update_fragments(), and update_random_values().
logical (kind=c_bool), dimension(:), allocatable precipitation__method_of_fragments::sequence_selection private
Definition at line 59 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize().
logical (kind=c_bool) precipitation__method_of_fragments::random_fragment_sequences = .true._c_bool private
Definition at line 63 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), and update_random_values().
type (fragments_t), dimension(:), allocatable, target, public precipitation__method_of_fragments::fragments
Definition at line 87 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_calculate(), precipitation_method_of_fragments_initialize(), process_fragment_sets(), read_daily_fragments(), and update_fragments().
type (ptr_fragments_t), dimension(:), allocatable precipitation__method_of_fragments::current_fragments private
Definition at line 90 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), and update_fragments().
type (fragments_set_t), dimension(:), allocatable, public precipitation__method_of_fragments::fragments_sets
Definition at line 94 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), process_fragment_sets(), and update_fragments().
type (fragments_sequence_t), pointer precipitation__method_of_fragments::pfragments_sequence
Definition at line 107 of file precipitation__method_of_fragments.F90.
type (fragments_sequence_t), dimension(:), allocatable, public precipitation__method_of_fragments::fragments_sequence
Definition at line 110 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), read_fragments_sequence(), and update_random_values().
type (data_catalog_entry_t), pointer precipitation__method_of_fragments::prainfall_adjust_factor private
Definition at line 112 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_calculate().
integer (kind=c_int) precipitation__method_of_fragments::lu_fragments_echo private
Definition at line 114 of file precipitation__method_of_fragments.F90.
Referenced by precipitation_method_of_fragments_initialize(), and update_fragments().