SWB 2.0: et__gridded_values Module Reference
et__gridded_values Module Reference
Populate potential evapotranspiration by substituting in the daily average ET from a gridded data source.
Functions/Subroutines
subroutine, public et_gridded_values_initialize (lActive)
subroutine, public et_gridded_values_calculate ()
Variables
type(data_catalog_entry_t), pointer, public pet_grid
Detailed Description
Function/Subroutine Documentation
et_gridded_values_initialize()
subroutine, public et__gridded_values::et_gridded_values_initialize (logical (kind=c_bool), dimension(:,:), intent(in) lActive)
Definition at line 31 of file et__gridded_values.F90.
References data_catalog::dat, exceptions::die(), and pet_grid.
Referenced by model_domain::model_initialize_et_daily_grid(), and model_domain::model_initialize_et_monthly_grid().
et_gridded_values_calculate()
subroutine, public et__gridded_values::et_gridded_values_calculate ()
Definition at line 55 of file et__gridded_values.F90.
References pet_grid, and simulation_datetime::sim_dt.
Referenced by model_domain::model_calculate_et_daily_grid(), and model_domain::model_calculate_et_monthly_grid().
Variable Documentation
pet_grid
type (data_catalog_entry_t), pointer, public et__gridded_values::pet_grid
Definition at line 26 of file et__gridded_values.F90.
Referenced by et_gridded_values_calculate(), et_gridded_values_initialize(), model_domain::model_calculate_et_daily_grid(), and model_domain::model_calculate_et_monthly_grid().