SWB 2.0: irrigation Module Reference
irrigation Module Reference
Provides support for assessing the effect of irrigation on recharge values by estimating the irrigation required to maintain soil moisture levels for specific crop types.
Functions/Subroutines
subroutine, public irrigation__initialize (irrigation_mask, is_active)
Estimate the irrigation water required to sustain plant growth.
integer(kind=c_int) function, dimension(31), public irrigation__output_schedule_values (landuse_index)
elemental subroutine, public irrigation__calculate (irrigation_amount, landuse_index, soil_storage, soil_storage_max, rainfall, runoff, crop_etc, irrigation_mask, num_days_since_planting, monthly_rainfall, monthly_runoff)
Variables
character(len=35), dimension(0:4), parameter app_option_name = [ "Apply nothing ", "Apply to field capacity ", "Apply to specified deficit fraction", "Apply constant amount ", "Apply proportional to (PE + RO - R)" ]
real(kind=c_float), dimension(:), allocatable maximum_allowable_depletion_fraction
real(kind=c_float), dimension(:), allocatable irrigation_from_groundwater
real(kind=c_float), dimension(:), allocatable irrigation_from_surface_water
real(kind=c_float), dimension(:), allocatable fraction_of_irrigation_from_gw
real(kind=c_float), dimension(:), allocatable irrigation_efficiency
integer(kind=c_int), dimension(:), allocatable num_days_of_irrigation
integer(kind=c_int), dimension(:), allocatable first_day_of_irrigation
integer(kind=c_int), dimension(:), allocatable last_day_of_irrigation
integer(kind=c_int), dimension(:), allocatable application_method_code
integer(kind=c_short), dimension(:,:), allocatable monthly_irrigation_schedule
real(kind=c_float), dimension(:), allocatable application_amount
type(data_catalog_entry_t), pointer pirrigation_mask
real(kind=c_float), dimension(:), allocatable irrigation_mask
Detailed Description
Function/Subroutine Documentation
subroutine, public irrigation::irrigation__initialize (real (kind=c_float), dimension(:), intent(inout) irrigation_mask, logical (kind=c_bool), dimension(:,:), intent(in) is_active)
Estimate the irrigation water required in order to keep soil moisture values above the maximum allowable depletion (MAD) for each gridcell.
Parameters
[in,out] pGrd Pointer to the model grid object
[in] pConfig Pointer to the configuration data structure (type T_CONFIG).
determine how many landuse codes are present
determine how many landuse codes are present
retrieve list of fraction of irrigation from groundwater
retrieve maximum allowable depletion
retrieve length (in days since planting) of irrigation
retrieve first day of irrigation
retrieve last day of irrigation
retrieve irrigation efficiency
check: number of irrigation efficiency values == number of landuse codes?
process first day of irrigation. retrieved as a list of strings; must convert the strings from mm/dd to DOY
process last day of irrigation. retrieved as a list of strings; must convert the strings from mm/dd to DOY
process number of days of irrigation. retrieved as a list of strings; must convert the strings from mm/dd to DOY
retrieve application option (i.e. to field capacity, to defined deficit amount, as constant amount)
retrieve application amount. not used if "field capacity" option is active. value represents deficit fraction or constant amount depending on application option active.
basic checks to see whether the number of parameters equals the number of lu codes
Definition at line 69 of file irrigation.F90.
References app_option_name, application_amount, application_method_code, first_day_of_irrigation, fraction_of_irrigation_from_gw, irrigation_efficiency, irrigation_from_groundwater, irrigation_from_surface_water, last_day_of_irrigation, maximum_allowable_depletion_fraction, monthly_irrigation_schedule, num_days_of_irrigation, and pirrigation_mask.
Referenced by model_domain::model_initialize_irrigation().
integer (kind=c_int) function, dimension(31), public irrigation::irrigation__output_schedule_values (integer (kind=c_int), intent(in) landuse_index)
Definition at line 380 of file irrigation.F90.
References irrigation_mask, and monthly_irrigation_schedule.
elemental subroutine, public irrigation::irrigation__calculate (real (kind=c_float), intent(inout) irrigation_amount, integer (kind=c_int), intent(in) landuse_index, real (kind=c_float), intent(in) soil_storage, real (kind=c_float), intent(in) soil_storage_max, real (kind=c_float), intent(in) rainfall, real (kind=c_float), intent(in) runoff, real (kind=c_float), intent(in) crop_etc, real (kind=c_float), intent(in) irrigation_mask, integer (kind=c_int), intent(in) num_days_since_planting, real (kind=c_float), intent(in), optional monthly_rainfall, real (kind=c_float), intent(in), optional monthly_runoff)
Definition at line 402 of file irrigation.F90.
References application_amount, application_method_code, first_day_of_irrigation, irrigation_efficiency, irrigation_mask, last_day_of_irrigation, maximum_allowable_depletion_fraction, monthly_irrigation_schedule, and num_days_of_irrigation.
Referenced by model_domain::model_calculate_irrigation().
Variable Documentation
character (len=35), dimension(0:4), parameter irrigation::app_option_name = [ "Apply nothing ", "Apply to field capacity ", "Apply to specified deficit fraction", "Apply constant amount ", "Apply proportional to (PE + RO - R)" ] private
Definition at line 33 of file irrigation.F90.
Referenced by irrigation__initialize().
real (kind=c_float), dimension(:), allocatable irrigation::maximum_allowable_depletion_fraction private
Definition at line 40 of file irrigation.F90.
Referenced by irrigation__calculate(), and irrigation__initialize().
real (kind=c_float), dimension(:), allocatable irrigation::irrigation_from_groundwater private
Definition at line 41 of file irrigation.F90.
Referenced by irrigation__initialize().
real (kind=c_float), dimension(:), allocatable irrigation::irrigation_from_surface_water private
Definition at line 42 of file irrigation.F90.
Referenced by irrigation__initialize().
real (kind=c_float), dimension(:), allocatable irrigation::fraction_of_irrigation_from_gw private
Definition at line 44 of file irrigation.F90.
Referenced by irrigation__initialize().
real (kind=c_float), dimension(:), allocatable irrigation::irrigation_efficiency private
Definition at line 45 of file irrigation.F90.
Referenced by irrigation__calculate(), and irrigation__initialize().
integer (kind=c_int), dimension(:), allocatable irrigation::num_days_of_irrigation private
Definition at line 46 of file irrigation.F90.
Referenced by irrigation__calculate(), and irrigation__initialize().
integer (kind=c_int), dimension(:), allocatable irrigation::first_day_of_irrigation private
Definition at line 47 of file irrigation.F90.
Referenced by irrigation__calculate(), and irrigation__initialize().
integer (kind=c_int), dimension(:), allocatable irrigation::last_day_of_irrigation private
Definition at line 48 of file irrigation.F90.
Referenced by irrigation__calculate(), and irrigation__initialize().
integer (kind=c_int), dimension(:), allocatable irrigation::application_method_code private
Definition at line 49 of file irrigation.F90.
Referenced by irrigation__calculate(), and irrigation__initialize().
integer (kind=c_short), dimension(:,:), allocatable irrigation::monthly_irrigation_schedule private
Definition at line 50 of file irrigation.F90.
Referenced by irrigation__calculate(), irrigation__initialize(), and irrigation__output_schedule_values().
real (kind=c_float), dimension(:), allocatable irrigation::application_amount private
Definition at line 51 of file irrigation.F90.
Referenced by irrigation__calculate(), and irrigation__initialize().
type (data_catalog_entry_t), pointer irrigation::pirrigation_mask private
Definition at line 53 of file irrigation.F90.
Referenced by irrigation__initialize().
real (kind=c_float), dimension(:), allocatable irrigation::irrigation_mask private
Definition at line 54 of file irrigation.F90.
Referenced by irrigation__calculate(), irrigation__output_schedule_values(), and model_domain::model_calculate_irrigation().