SWB 2.0: polygon_summarize Module Reference
polygon_summarize Module Reference
Functions/Subroutines
subroutine initialize_polygon_summarize ()
subroutine perform_polygon_summarize (cells)
integer(kind=c_int) function most_common_value (int_vector, belongs_to_poly)
real(kind=c_float) function mean (float_vector, belongs_to_poly)
Variables
integer(kind=c_int), dimension(5), parameter poly_id = [ 185678, 152055, 149096, 113173, 106237 ]
integer(kind=c_int), dimension(4) lu
character(len=1), parameter tab = achar(9)
Function/Subroutine Documentation
initialize_polygon_summarize()
subroutine polygon_summarize::initialize_polygon_summarize ()
Definition at line 23 of file polygon_summarize.F90.
References lu, poly_id, and tab.
perform_polygon_summarize()
subroutine polygon_summarize::perform_polygon_summarize (type (model_domain_t), intent(in) cells)
Definition at line 48 of file polygon_summarize.F90.
References lu, mean(), most_common_value(), poly_id, simulation_datetime::sim_dt, and tab.
most_common_value()
integer (kind=c_int) function polygon_summarize::most_common_value (integer (kind=c_int), dimension(:) int_vector, logical, dimension(:) belongs_to_poly)
Definition at line 106 of file polygon_summarize.F90.
Referenced by perform_polygon_summarize().
mean()
real (kind=c_float) function polygon_summarize::mean (real (kind=c_float), dimension(:) float_vector, logical, dimension(:) belongs_to_poly)
Definition at line 157 of file polygon_summarize.F90.
Referenced by perform_polygon_summarize().
Variable Documentation
poly_id
integer (kind=c_int), dimension(5), parameter polygon_summarize::poly_id = [ 185678, 152055, 149096, 113173, 106237 ]
Definition at line 11 of file polygon_summarize.F90.
Referenced by initialize_polygon_summarize(), and perform_polygon_summarize().
lu
integer (kind=c_int), dimension(4) polygon_summarize::lu
Definition at line 17 of file polygon_summarize.F90.
Referenced by initialize_polygon_summarize(), and perform_polygon_summarize().
tab
character (len=1), parameter polygon_summarize::tab = achar(9)
Definition at line 18 of file polygon_summarize.F90.
Referenced by initialize_polygon_summarize(), and perform_polygon_summarize().