SWB 2.0: storm_drain_capture Module Reference
storm_drain_capture Module Reference
Functions/Subroutines
subroutine, public storm_drain_capture_initialize ()
elemental real(kind=c_float) function, public storm_drain_capture_calculate (landuse_index)
Variables
real(kind=c_float), dimension(:), allocatable, public storm_drain_capture_fraction
Function/Subroutine Documentation
subroutine, public storm_drain_capture::storm_drain_capture_initialize ()
Determine how many landuse codes are present
Determine how many storm_drain_capture codes are present
check: number of STORM_DRAIN_CAPTURE_FRACTION values == number of landuse codes?
Definition at line 24 of file storm_drain_capture.F90.
References constants_and_conversions::false, parameters::params, storm_drain_capture_fraction, and exceptions::warn().
Referenced by model_initialize::initialize_ancillary_values().
elemental real (kind=c_float) function, public storm_drain_capture::storm_drain_capture_calculate (integer (kind=c_int), intent(in) landuse_index)
Definition at line 78 of file storm_drain_capture.F90.
References storm_drain_capture_fraction.
Variable Documentation
real (kind=c_float), dimension(:), allocatable, public storm_drain_capture::storm_drain_capture_fraction
Definition at line 19 of file storm_drain_capture.F90.
Referenced by daily_calculation::perform_daily_calculation(), storm_drain_capture_calculate(), and storm_drain_capture_initialize().