SWB 2.0: dictionary Module Reference
dictionary Module Reference
Data Types
type dict_entry_t
type dict_t
Functions/Subroutines
subroutine add_key_sub (this, sKey)
subroutine add_string_sub (this, sValue)
subroutine add_float_sub (this, fValue)
subroutine add_integer_sub (this, iValue)
subroutine add_double_sub (this, dValue)
subroutine add_logical_sub (this, lValue)
type(dict_entry_t) function, pointer get_entry_by_key_fn (this, sKey)
type(dict_entry_t) function, pointer get_entry_by_index_fn (this, iIndex)
type(dict_entry_t) function, pointer get_next_entry_by_key_fn (this, sKey)
type(dict_entry_t) function, pointer get_next_entry_fn (this)
type(string_list_t) function grep_dictionary_key_names_fn (this, sKey)
subroutine add_entry_to_dict_sub (this, dict_entry)
subroutine delete_entry_by_key_sub (this, sKey)
subroutine get_values_as_int_sub (this, sKey, iValues)
subroutine get_values_as_logical_sub (this, sKey, lValues)
subroutine get_values_as_logical_given_list_of_keys_sub (this, slKeys, lValues)
Search through keys for a match; return logical values.
subroutine get_values_as_string_list_given_list_of_keys_sub (this, slKeys, slString)
subroutine get_value_as_string_sub (this, sText, sKey, iIndex)
subroutine get_values_as_string_list_sub (this, sKey, slString)
subroutine get_values_as_int_given_list_of_keys_sub (this, slKeys, iValues)
Search through keys for a match; return integer values.
subroutine get_values_as_float_given_list_of_keys_sub (this, slKeys, fValues)
Search through keys for a match; return float values.
subroutine get_values_as_float_sub (this, sKey, fValues)
subroutine print_all_dictionary_entries_sub (this, iLogLevel, lEcho)
Variables
type(dict_t), public cf_dict
type(dict_entry_t), pointer, public cf_entry
Function/Subroutine Documentation
add_key_sub()
subroutine dictionary::add_key_sub (class (dict_entry_t) this, character (len=*), intent(in) sKey) private
Definition at line 105 of file dictionary.F90.
add_string_sub()
subroutine dictionary::add_string_sub (class (dict_entry_t) this, character (len=*), intent(in) sValue) private
Definition at line 116 of file dictionary.F90.
add_float_sub()
subroutine dictionary::add_float_sub (class (dict_entry_t) this, real (kind=c_float), intent(in) fValue) private
Definition at line 127 of file dictionary.F90.
add_integer_sub()
subroutine dictionary::add_integer_sub (class (dict_entry_t) this, integer (kind=c_int), intent(in) iValue) private
Definition at line 138 of file dictionary.F90.
add_double_sub()
subroutine dictionary::add_double_sub (class (dict_entry_t) this, real (kind=c_double), intent(in) dValue) private
Definition at line 149 of file dictionary.F90.
add_logical_sub()
subroutine dictionary::add_logical_sub (class (dict_entry_t) this, logical (kind=c_bool), intent(in) lValue) private
Definition at line 160 of file dictionary.F90.
get_entry_by_key_fn()
type (dict_entry_t) function, pointer dictionary::get_entry_by_key_fn (class (dict_t) this, character (len=*), intent(in) sKey) private
Definition at line 176 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
get_entry_by_index_fn()
type (dict_entry_t) function, pointer dictionary::get_entry_by_index_fn (class (dict_t) this, integer (kind=c_int), intent(in) iIndex) private
Definition at line 202 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
get_next_entry_by_key_fn()
type (dict_entry_t) function, pointer dictionary::get_next_entry_by_key_fn (class (dict_t) this, character (len=*), intent(in) sKey) private
Definition at line 238 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
get_next_entry_fn()
type (dict_entry_t) function, pointer dictionary::get_next_entry_fn (class (dict_t) this) private
Definition at line 266 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
grep_dictionary_key_names_fn()
type (string_list_t) function dictionary::grep_dictionary_key_names_fn (class (dict_t) this, character (len=*), intent(in) sKey) private
Definition at line 289 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
add_entry_to_dict_sub()
subroutine dictionary::add_entry_to_dict_sub (class (dict_t) this, type (dict_entry_t), pointer dict_entry) private
Definition at line 318 of file dictionary.F90.
References exceptions::warn().
delete_entry_by_key_sub()
subroutine dictionary::delete_entry_by_key_sub (class (dict_t) this, character (len=*), intent(in) sKey) private
Definition at line 358 of file dictionary.F90.
get_values_as_int_sub()
subroutine dictionary::get_values_as_int_sub (class (dict_t) this, character (len=*), intent(in) sKey, integer (kind=c_int), dimension(:), intent(out), allocatable iValues) private
Definition at line 397 of file dictionary.F90.
References constants_and_conversions::itinyval, constants_and_conversions::lfalse, and exceptions::warn().
get_values_as_logical_sub()
subroutine dictionary::get_values_as_logical_sub (class (dict_t) this, character (len=*), intent(in) sKey, logical (kind=c_bool), dimension(:), intent(out), allocatable lValues) private
Definition at line 431 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
get_values_as_logical_given_list_of_keys_sub()
subroutine dictionary::get_values_as_logical_given_list_of_keys_sub (class (dict_t) this, type (string_list_t), intent(inout) slKeys, logical (kind=c_bool), dimension(:), intent(out), allocatable lValues) private
THis routine allows for multiple header values to be supplied in the search for the appropriate column.
Parameters
[in] this Object of DICT_T class.
[in] slKeys String list containing one or more possible key values to search for.
[out] iValues Integer vector of values associated with one of the provided keys.
Definition at line 473 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
get_values_as_string_list_given_list_of_keys_sub()
subroutine dictionary::get_values_as_string_list_given_list_of_keys_sub (class (dict_t) this, type (string_list_t), intent(inout) slKeys, type (string_list_t), intent(out) slString) private
Definition at line 520 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
get_value_as_string_sub()
subroutine dictionary::get_value_as_string_sub (class (dict_t) this, character(len=:), intent(out), allocatable sText, character (len=*), intent(in), optional sKey, integer (kind=c_int), intent(in), optional iIndex) private
Definition at line 562 of file dictionary.F90.
get_values_as_string_list_sub()
subroutine dictionary::get_values_as_string_list_sub (class (dict_t) this, character (len=*), intent(in) sKey, type (string_list_t), intent(out) slString) private
Definition at line 591 of file dictionary.F90.
References constants_and_conversions::lfalse, and exceptions::warn().
get_values_as_int_given_list_of_keys_sub()
subroutine dictionary::get_values_as_int_given_list_of_keys_sub (class (dict_t) this, type (string_list_t), intent(inout) slKeys, integer (kind=c_int), dimension(:), intent(out), allocatable iValues) private
THis routine allows for multiple header values to be supplied in the search for the appropriate column.
Parameters
[in] this Object of DICT_T class.
[in] slKeys String list containing one or more possible key values to search for.
[out] iValues Integer vector of values associated with one of the provided keys.
Definition at line 629 of file dictionary.F90.
References constants_and_conversions::itinyval, constants_and_conversions::lfalse, and exceptions::warn().
get_values_as_float_given_list_of_keys_sub()
subroutine dictionary::get_values_as_float_given_list_of_keys_sub (class (dict_t) this, type (string_list_t), intent(inout) slKeys, real (kind=c_float), dimension(:), intent(out), allocatable fValues) private
THis routine allows for multiple header values to be supplied in the search for the appropriate column.
Parameters
[in] this Object of DICT_T class.
[in] slKeys String list containing one or more possible key values to search for.
[out] fValues Float vector of values associated with one of the provided keys.
Definition at line 686 of file dictionary.F90.
References constants_and_conversions::ftinyval, constants_and_conversions::lfalse, and exceptions::warn().
get_values_as_float_sub()
subroutine dictionary::get_values_as_float_sub (class (dict_t) this, character (len=*), intent(in) sKey, real (kind=c_float), dimension(:), intent(out), allocatable fValues) private
Definition at line 735 of file dictionary.F90.
References constants_and_conversions::ftinyval, constants_and_conversions::lfalse, and exceptions::warn().
print_all_dictionary_entries_sub()
subroutine dictionary::print_all_dictionary_entries_sub (class (dict_t) this, integer (kind=c_int), intent(in), optional iLogLevel, logical (kind=c_bool), intent(in), optional lEcho) private
Definition at line 768 of file dictionary.F90.
References constants_and_conversions::lfalse, and logfiles::logs.
Variable Documentation
cf_dict
type (dict_t), public dictionary::cf_dict
Definition at line 95 of file dictionary.F90.
Referenced by model_initialize::initialize_all(), model_initialize::initialize_generic_grid(), model_initialize::initialize_generic_method(), model_initialize::initialize_grid_options(), model_initialize::initialize_parameter_tables(), model_initialize::initialize_start_and_end_dates(), precipitation__method_of_fragments::precipitation_method_of_fragments_initialize(), model_initialize::read_control_file(), runoff__gridded_values::runoff_gridded_values_initialize(), and model_initialize::write_control_file().
cf_entry
type (dict_entry_t), pointer, public dictionary::cf_entry
Definition at line 96 of file dictionary.F90.
Referenced by model_initialize::read_control_file().