SWB 2.0: growing_degree_day Module Reference
growing_degree_day Module Reference
Functions/Subroutines
subroutine, public growing_degree_day_initialize (is_cell_active, landuse_index)
elemental subroutine, public growing_degree_day_calculate (gdd, tmean, order)
Variables
real(kind=c_float), dimension(:), allocatable, public gdd_base
real(kind=c_float), dimension(:), allocatable, public gdd_max
integer(kind=c_int), dimension(:), allocatable, public gdd_reset_date
type(t_netcdf4_file), pointer pncfile
Function/Subroutine Documentation
growing_degree_day_initialize()
subroutine, public growing_degree_day::growing_degree_day_initialize (logical (kind=c_bool), dimension(:,:), intent(in) is_cell_active, integer (kind=c_int), dimension(:), intent(in) landuse_index)
create string list that allows for alternate heading identifiers for the landuse code
Determine how many landuse codes are present
Definition at line 28 of file growing_degree_day.F90.
References gdd_base, gdd_max, gdd_reset_date, datetime::mmdd2doy(), and parameters::params.
Referenced by model_domain::model_initialize_gdd().
growing_degree_day_calculate()
elemental subroutine, public growing_degree_day::growing_degree_day_calculate (real (kind=c_float), intent(inout) gdd, real (kind=c_float), intent(in) tmean, integer (kind=c_int), intent(in) order)
Definition at line 135 of file growing_degree_day.F90.
References gdd_base, gdd_max, gdd_reset_date, and simulation_datetime::sim_dt.
Referenced by model_domain::model_calculate_gdd().
Variable Documentation
gdd_base
real (kind=c_float), dimension(:), allocatable, public growing_degree_day::gdd_base
Definition at line 20 of file growing_degree_day.F90.
Referenced by growing_degree_day_calculate(), and growing_degree_day_initialize().
gdd_max
real (kind=c_float), dimension(:), allocatable, public growing_degree_day::gdd_max
Definition at line 21 of file growing_degree_day.F90.
Referenced by growing_degree_day_calculate(), and growing_degree_day_initialize().
gdd_reset_date
integer (kind=c_int), dimension(:), allocatable, public growing_degree_day::gdd_reset_date
Definition at line 22 of file growing_degree_day.F90.
Referenced by growing_degree_day_calculate(), and growing_degree_day_initialize().
pncfile
type (t_netcdf4_file), pointer growing_degree_day::pncfile private
Definition at line 23 of file growing_degree_day.F90.