SWB 2.0: netcdf4_support Module Reference
netcdf4_support Module Reference
Provide support for use of NetCDF files as input for time-varying, gridded meteorlogic data, or output for any SWB-generated variable.
Data Types
type t_netcdf4_file
type t_netcdf_attribute
type t_netcdf_dimension
type t_netcdf_variable
Functions/Subroutines
logical(kind=c_bool) function, public netcdf_date_within_range (NCFILE, iJulianDay)
integer(kind=c_int) function nf_julian_day_to_index (NCFILE, rJulianDay)
This was so clear the other day.
real(kind=c_double) function nf_index_to_dayvalue (NCFILE, iIndex)
real(kind=c_double) function nf_dayvalue_to_julian_day (NCFILE, rDayValue)
integer(kind=c_size_t) function nf_julian_day_to_index_adj (NCFILE, rJulianDay)
integer(kind=c_int) function nf_return_varid (NCFILE, iVarIndex)
integer(kind=c_int) function nf_return_dimid (NCFILE, iDimIndex)
integer(kind=c_int) function nf_return_varindex (NCFILE, iVarID)
character(len=256) function nf_return_attvalue (NCFILE, iVarIndex, sAttName)
integer(kind=c_int) function nf_return_dimindex (NCFILE, iDimID)
integer(kind=c_size_t) function nf_return_dimsize (NCFILE, iDimID)
subroutine, public netcdf_open_and_prepare_for_merging (NCFILE, sFilename)
subroutine, public netcdf_open_and_prepare_as_input (NCFILE, sFilename, lFlipHorizontal, lFlipVertical, sVariableOrder, sVarName_x, sVarName_y, sVarName_z, sVarName_time, tGridBounds, iLU)
subroutine, public netcdf_open_and_prepare_as_output_archive (NCFILE, NCFILE_ARCHIVE, iOriginMonth, iOriginDay, iOriginYear, iStartYear, iEndYear)
subroutine, public netcdf_open_and_prepare_as_output (NCFILE, sVariableName, sVariableUnits, iNX, iNY, fX, fY, StartDate, EndDate, PROJ4_string, history_list, executable_name, dpLat, dpLon, fValidMin, fValidMax)
subroutine nf_set_z_variable_name (NCFILE, sVarName_z)
subroutine nf_set_iteration_bounds (NCFILE)
subroutine nf_set_start_count_stride (NCFILE)
subroutine nf_return_native_coord_bounds (NCFILE)
subroutine nf_get_time_vals (NCFILE)
subroutine nf_get_x_and_y (NCFILE)
subroutine nf_open_file (NCFILE, sFilename, iLU)
subroutine, public netcdf_open_file (NCFILE, sFilename, iLU)
subroutine nf_trap (iResultCode, sFilename, iLineNumber)
subroutine, public netcdf_close_file (NCFILE)
subroutine, public netcdf_deallocate_data_struct (NCFILE)
subroutine, public netcdf_nullify_data_struct (NCFILE)
subroutine nf_populate_dimension_struct (NCFILE)
subroutine nf_populate_variable_struct (NCFILE)
subroutine nf_populate_attribute_struct (NCFILE, pNC_ATT, iNC_VarID, iAttNum)
subroutine, public netcdf_get_variable_id_for_variable (NCFILE, variable_name, variable_id)
subroutine, public netcdf_get_attribute_list_for_variable (NCFILE, variable_name, attribute_name_list, attribute_value_list)
subroutine, public netcdf_get_variable_list (NCFILE, variable_list)
logical(kind=c_bool) function, public netcdf_update_time_starting_index (NCFILE, iJulianDay)
subroutine, public netcdf_get_variable_slice (NCFILE, rValues, iValues)
subroutine nf_get_variable_slice_short (NCFILE, rValues)
subroutine nf_get_variable_slice_int (NCFILE, rValues)
subroutine nf_get_variable_slice_float (NCFILE, rValues)
subroutine nf_get_variable_vector_short (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, iNC_Vars)
subroutine nf_get_variable_array_short (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, iNC_Vars)
subroutine nf_get_variable_array_as_vector_short (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, iNC_Vars)
subroutine nf_get_variable_array_as_vector_int (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, iNC_Vars)
subroutine nf_get_variable_vector_int (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, iNC_Vars)
subroutine nf_get_variable_vector_double (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, dpNC_Vars)
subroutine nf_get_variable_array_double (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, dpNC_Vars)
subroutine nf_get_variable_array_as_vector_double (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, dpNC_Vars)
subroutine nf_get_variable_vector_float (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, rNC_Vars)
subroutine nf_get_variable_array_float (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, rNC_Vars)
subroutine nf_get_variable_array_as_vector_float (NCFILE, iNC_VarID, iNC_Start, iNC_Count, iNC_Stride, rNC_Vars)
subroutine, public netcdf_dump_cdl (NCFILE, iLU)
real(kind=c_double) function, dimension(0:1) nf_get_first_and_last (NCFILE, iVarIndex)
subroutine nf_calculate_time_range (NCFILE)
subroutine nf_get_time_units (NCFILE)
subroutine nf_get_xyz_units (NCFILE)
subroutine nf_get_scale_and_offset (NCFILE)
subroutine nf_get_variable_id_and_type (NCFILE, strict_asserts)
integer(kind=c_int) function nf_return_index_double (rValues, rTargetValue)
integer(kind=c_size_t) function, dimension(2), public netcdf_coord_to_col_row (NCFILE, rX, rY)
integer(kind=c_int) function nf_get_varid (NCFILE, sVariableName)
subroutine nf_create (NCFILE, sFilename, iLU)
subroutine nf_define_deflate (NCFILE, iVarID, iShuffle, iDeflate, iDeflate_level)
subroutine nf_enddef (NCFILE)
integer(kind=c_int) function nf_define_dimension (NCFILE, sDimensionName, iDimensionSize)
subroutine nf_define_dimensions (NCFILE)
subroutine nf_set_standard_dimensions (NCFILE, iNX, iNY)
subroutine nf_set_standard_variables (NCFILE, sVarName_z, lLatLon)
subroutine nf_set_global_attributes (NCFILE, sDataType, executable_name, history_list, sSourceFile)
subroutine nf_set_standard_attributes (NCFILE, sOriginText, PROJ4_string, lLatLon, fValidMin, fValidMax)
subroutine nf_put_x_and_y (NCFILE, dpX, dpY)
subroutine nf_put_lat_and_lon (NCFILE, dpLat, dpLon)
integer(kind=c_int) function nf_define_variable (NCFILE, sVariableName, iVariableType, iNumberOfDimensions, iDimIDs)
subroutine nf_define_variables (NCFILE)
subroutine nf_put_attribute (NCFILE, iVarID, sAttributeName, sAttributeValue, iAttributeValue, rAttributeValue, dpAttributeValue)
subroutine nf_put_attributes (NCFILE)
subroutine, public netcdf_put_variable_array (NCFILE, iVarID, iStart, iCount, iStride, iValues, i2Values, rValues, dpValues)
subroutine, public netcdf_put_packed_variable_array (NCFILE, iVarID, iStart, iCount, iStride, lMask, iValues, iField, i2Values, i2Field, rValues, rField, dpValues, dpField)
subroutine, public netcdf_put_variable_vector (NCFILE, iVarID, iStart, iCount, iStride, iValues, i2Values, rValues, dpValues)
Variables
integer(kind=c_int), public nc_readonly = 0
integer(kind=c_int), public nc_readwrite = 1
integer(kind=c_int), parameter nc_nat = 0
integer(kind=c_int), parameter nc_byte = 1
integer(kind=c_int), parameter nc_char = 2
integer(kind=c_int), parameter nc_short = 3
integer(kind=c_int), parameter nc_int = 4
integer(kind=c_int), parameter, public nc_float = 5
integer(kind=c_int), parameter nc_double = 6
integer(kind=c_int), parameter nc_fill_char = 0
integer(kind=c_int), parameter nc_fill_byte = -127
integer(kind=c_int), parameter nc_fill_short = -32767
integer(kind=c_int), parameter, public nc_fill_int = -2147483647
real(kind=c_float), parameter, public nc_fill_float = -9.9e-20_c_float
real(kind=c_double), parameter nc_fill_double = -9.9e-20_c_double
integer(kind=c_int), parameter nc_nowrite = 0
integer(kind=c_int), parameter nc_write = 1
integer(kind=c_int), parameter nc_clobber = 0
integer(kind=c_int), parameter nc_noclobber = 4
integer(kind=c_int), parameter nc_fill = 0
integer(kind=c_int), parameter nc_nofill = 256
integer(kind=c_int), parameter nc_lock = 1024
integer(kind=c_int), parameter nc_share = 2048
integer(kind=c_int), parameter nc_strict_nc3 = 8
integer(kind=c_int), parameter nc_64bit_offset = 512
integer(kind=c_int), parameter nc_sizehint_default = 0
integer(kind=c_int), parameter nc_align_chunk = -1
integer(kind=c_int), parameter nc_format_classic = 1
integer(kind=c_int), parameter nc_format_64bit = 2
integer(kind=c_int), parameter nc_format_netcdf4 = 3
integer(kind=c_int), parameter nc_format_netcdf4_classic = 4
integer(kind=c_int), parameter nc_max_dims = 1024
integer(kind=c_int), parameter nc_max_attrs = 8192
integer(kind=c_int), parameter nc_max_vars = 8192
integer(kind=c_int), parameter nc_max_name = 256
integer(kind=c_int), parameter nc_shuffle_yes = 1
integer(kind=c_int), parameter nc_shuffle_no = 0
integer(kind=c_int), parameter nc_deflate_yes = 1
integer(kind=c_int), parameter nc_deflate_no = 0
integer(kind=c_int), parameter nc_netcdf4 = 4096
integer(kind=c_int), parameter nc_classic_model = 256
integer(kind=c_int), parameter nc_unlimited = 0
integer(kind=c_int), parameter nc_global = -1
integer(c_int), parameter, public nc_time = 0
integer(c_int), parameter, public nc_y = 1
integer(c_int), parameter, public nc_x = 2
integer(c_int), parameter, public nc_z = 3
integer(c_int), parameter, public nc_crs = 4
integer(c_int), parameter, public nc_lat = 5
integer(c_int), parameter, public nc_lon = 6
integer(kind=c_int), parameter nc_first = 0
integer(kind=c_int), parameter nc_last = 1
integer(kind=c_int), parameter nc_by = 2
integer(kind=c_int), parameter, public nc_left = 0
integer(kind=c_int), parameter, public nc_right = 1
integer(kind=c_int), parameter, public nc_top = 0
integer(kind=c_int), parameter, public nc_bottom = 1
integer(kind=c_int), parameter column = 1
integer(kind=c_int), parameter row = 2
character(len=25), dimension(4), parameter netcdf_format_string = ["NC_FORMAT_CLASSIC ", "NC_FORMAT_64BIT ", "NC_FORMAT_NETCDF4 ", "NC_FORMAT_NETCDF4_CLASSIC" ]
character(len=6), dimension(0:6), parameter netcdf_data_type = ["nat ", "byte ", "char ", "short ", "int ", "float ", "double" ]
Detailed Description
Function/Subroutine Documentation
netcdf_date_within_range()
logical (kind=c_bool) function, public netcdf4_support::netcdf_date_within_range (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iJulianDay)
Definition at line 270 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub().
nf_julian_day_to_index()
integer (kind=c_int) function netcdf4_support::nf_julian_day_to_index (type (t_netcdf4_file) NCFILE, real (kind=c_double) rJulianDay) private
Basically, I think we need two functions to convert from index to timeval, and timeval to JD; note that timeval refers to the number of days from the origin of the NetCDF file return the day value (number of days since origin
Definition at line 298 of file netcdf4_support.F90.
Referenced by nf_julian_day_to_index_adj().
nf_index_to_dayvalue()
real (kind=c_double) function netcdf4_support::nf_index_to_dayvalue (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iIndex) private
Definition at line 309 of file netcdf4_support.F90.
nf_dayvalue_to_julian_day()
real (kind=c_double) function netcdf4_support::nf_dayvalue_to_julian_day (type (t_netcdf4_file) NCFILE, real (kind=c_double) rDayValue) private
Definition at line 323 of file netcdf4_support.F90.
Referenced by nf_julian_day_to_index_adj().
nf_julian_day_to_index_adj()
integer (kind=c_size_t) function netcdf4_support::nf_julian_day_to_index_adj (type (t_netcdf4_file) NCFILE, real (kind=c_double) rJulianDay) private
First guess at what the appropriate index value should be. Current JD minus the Origin JD is a good guess.
calculate the range of INDEX values to search over
Definition at line 338 of file netcdf4_support.F90.
References constants_and_conversions::ibigval, constants_and_conversions::lfalse, constants_and_conversions::ltrue, nf_dayvalue_to_julian_day(), and nf_julian_day_to_index().
Referenced by netcdf_update_time_starting_index().
nf_return_varid()
integer (kind=c_int) function netcdf4_support::nf_return_varid (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarIndex) private
Definition at line 400 of file netcdf4_support.F90.
nf_return_dimid()
integer (kind=c_int) function netcdf4_support::nf_return_dimid (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iDimIndex) private
Definition at line 416 of file netcdf4_support.F90.
nf_return_varindex()
integer (kind=c_int) function netcdf4_support::nf_return_varindex (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarID) private
Definition at line 432 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
Referenced by nf_get_variable_slice_float(), nf_get_variable_slice_int(), and nf_get_variable_slice_short().
nf_return_attvalue()
character (len=256) function netcdf4_support::nf_return_attvalue (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarIndex, character (len=*) sAttName) private
Definition at line 465 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
nf_return_dimindex()
integer (kind=c_int) function netcdf4_support::nf_return_dimindex (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iDimID) private
Definition at line 518 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
nf_return_dimsize()
integer (kind=c_size_t) function netcdf4_support::nf_return_dimsize (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iDimID) private
Definition at line 551 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
Referenced by nf_get_first_and_last().
netcdf_open_and_prepare_for_merging()
subroutine, public netcdf4_support::netcdf_open_and_prepare_for_merging (type (t_netcdf4_file) NCFILE, character (len=*) sFilename)
look for and process the "days since MM-D-YYYY" attribute
retrieve the time values as included in the NetCDF file
retrieve the X and Y coordinates from the NetCDF file...
define the entire grid area as the AOI
based on the subset of the NetCDF file as determined above, set the start, count, and stride parameters for use in all further data retrievals
establish the bounds to iterate over; this can enable horiz or vert flipping
now that we have (possibly) created a subset, need to get the NATIVE coordinate bounds so that the intermediate grid file can be created
Definition at line 584 of file netcdf4_support.F90.
References constants_and_conversions::false, nc_bottom, nc_left, nc_right, nc_time, nc_top, nf_calculate_time_range(), nf_get_first_and_last(), nf_get_time_units(), nf_get_time_vals(), nf_get_variable_id_and_type(), nf_get_x_and_y(), nf_open_file(), nf_populate_dimension_struct(), nf_populate_variable_struct(), nf_return_native_coord_bounds(), nf_set_iteration_bounds(), and nf_set_start_count_stride().
netcdf_open_and_prepare_as_input()
subroutine, public netcdf4_support::netcdf_open_and_prepare_as_input (type (t_netcdf4_file) NCFILE, character (len=*) sFilename, logical (kind=c_bool), optional lFlipHorizontal, logical (kind=c_bool), optional lFlipVertical, character (len=*), optional sVariableOrder, character (len=*), optional sVarName_x, character (len=*), optional sVarName_y, character (len=*), optional sVarName_z, character (len=*), optional sVarName_time, type (grid_bounds_t), optional tGridBounds, integer (kind=c_int), optional iLU)
look for and process the "days since MM-D-YYYY" attribute
retrieve the time values as included in the NetCDF file
establish scale_factor and add_offset values, if present
retrieve the X and Y coordinates from the NetCDF file...
define a subset of the grid as the AOI need all four corner points since it is likely that the AOI rectangle is rotated relative to the base projection
define the entire grid area as the AOI
based on the subset of the NetCDF file as determined above, set the start, count, and stride parameters for use in all further data retrievals
establish the bounds to iterate over; this can enable horiz or vert flipping
now that we have (possibly) created a subset, need to get the NATIVE coordinate bounds so that the intermediate grid file can be created
Definition at line 652 of file netcdf4_support.F90.
References grid::column, nc_bottom, nc_left, nc_right, nc_time, nc_top, nc_x, nc_y, nc_z, netcdf_coord_to_col_row(), netcdf_dump_cdl(), nf_calculate_time_range(), nf_get_first_and_last(), nf_get_scale_and_offset(), nf_get_time_units(), nf_get_time_vals(), nf_get_variable_id_and_type(), nf_get_x_and_y(), nf_get_xyz_units(), nf_open_file(), nf_populate_dimension_struct(), nf_populate_variable_struct(), nf_return_native_coord_bounds(), nf_set_iteration_bounds(), nf_set_start_count_stride(), and grid::row.
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub(), and data_catalog_entry::getvalues_static_netcdf_sub().
netcdf_open_and_prepare_as_output_archive()
subroutine, public netcdf4_support::netcdf_open_and_prepare_as_output_archive (type (t_netcdf4_file) NCFILE, type (t_netcdf4_file) NCFILE_ARCHIVE, integer (kind=c_int) iOriginMonth, integer (kind=c_int) iOriginDay, integer (kind=c_int) iOriginYear, integer (kind=c_int) iStartYear, integer (kind=c_int) iEndYear)
set dimension values in the NCFILE struct
transfer dimension values to NetCDF file
set variable values in the NCFILE struct
transfer variable values to NetCDF file
enable a low level of data compression for the variable of interest
Definition at line 817 of file netcdf4_support.F90.
References nc_deflate_yes, nc_shuffle_yes, nc_x, nc_y, nc_z, nf_create(), nf_define_deflate(), nf_define_dimensions(), nf_define_variables(), nf_enddef(), nf_get_variable_id_and_type(), nf_put_attributes(), nf_put_x_and_y(), nf_set_global_attributes(), nf_set_standard_attributes(), nf_set_standard_dimensions(), and nf_set_standard_variables().
Referenced by data_catalog_entry::put_values_to_local_netcdf_sub().
netcdf_open_and_prepare_as_output()
subroutine, public netcdf4_support::netcdf_open_and_prepare_as_output (type (t_netcdf4_file), pointer NCFILE, character (len=*), intent(in) sVariableName, character (len=*), intent(in) sVariableUnits, integer (kind=c_int), intent(in) iNX, integer (kind=c_int), intent(in) iNY, real (kind=c_double), dimension(:), intent(in) fX, real (kind=c_double), dimension(:), intent(in) fY, type (datetime_t), intent(in) StartDate, type (datetime_t), intent(in) EndDate, character (len=*), intent(in) PROJ4_string, type (string_list_t), intent(in), optional, pointer history_list, character (len=*), intent(in), optional executable_name, real (kind=c_double), dimension(:,:), intent(in), optional dpLat, real (kind=c_double), dimension(:,:), intent(in), optional dpLon, real (kind=c_float), intent(in), optional fValidMin, real (kind=c_float), intent(in), optional fValidMax)
set dimension values in the NCFILE struct
Todo:
implement more flexible method of assigning units
transfer dimension values to NetCDF file
set variable values in the NCFILE struct
transfer variable values to NetCDF file
enable a low level of data compression for the variable of interest
Definition at line 915 of file netcdf4_support.F90.
References constants_and_conversions::false, logfiles::logs, constants_and_conversions::ltrue, nc_deflate_yes, nc_shuffle_yes, nc_z, nf_create(), nf_define_deflate(), nf_define_dimensions(), nf_define_variables(), nf_enddef(), nf_get_variable_id_and_type(), nf_put_attributes(), nf_put_lat_and_lon(), nf_put_x_and_y(), nf_set_global_attributes(), nf_set_standard_attributes(), nf_set_standard_dimensions(), nf_set_standard_variables(), constants_and_conversions::output_directory_name, and constants_and_conversions::output_prefix_name.
Referenced by fog__monthly_grid::fog_monthly_grid_initialize().
nf_set_z_variable_name()
subroutine netcdf4_support::nf_set_z_variable_name (type (t_netcdf4_file) NCFILE, character (len=*) sVarName_z) private
Definition at line 1034 of file netcdf4_support.F90.
References nc_z.
nf_set_iteration_bounds()
subroutine netcdf4_support::nf_set_iteration_bounds (type (t_netcdf4_file) NCFILE) private
Definition at line 1045 of file netcdf4_support.F90.
References nc_by, nc_first, and nc_last.
Referenced by netcdf_open_and_prepare_as_input(), and netcdf_open_and_prepare_for_merging().
nf_set_start_count_stride()
subroutine netcdf4_support::nf_set_start_count_stride (type (t_netcdf4_file) NCFILE) private
need to subtract 1 from the start index: we're using the NetCDF C API, in which index values are relative to zero
note: this assumes that the row numbers increase from top to bottom, while the Y coordinates decrease top to bottom
count must be set to the number of values! maxval minus minval results in a diagonal pattern in the input as we read in the incorrect number of results
Definition at line 1073 of file netcdf4_support.F90.
References nc_time, nc_x, and nc_y.
Referenced by netcdf_open_and_prepare_as_input(), and netcdf_open_and_prepare_for_merging().
nf_return_native_coord_bounds()
subroutine netcdf4_support::nf_return_native_coord_bounds (type (t_netcdf4_file) NCFILE) private
find the (x,y) associated with the column and row number bounds
Definition at line 1127 of file netcdf4_support.F90.
References nc_bottom, nc_left, nc_right, and nc_top.
Referenced by netcdf_open_and_prepare_as_input(), and netcdf_open_and_prepare_for_merging().
nf_get_time_vals()
subroutine netcdf4_support::nf_get_time_vals (type (t_netcdf4_file) NCFILE) private
Todo:
allow time to be read in as float, short, or int as well
Definition at line 1165 of file netcdf4_support.F90.
References nc_time, and nf_get_variable_vector_double().
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and netcdf_open_file().
nf_get_x_and_y()
subroutine netcdf4_support::nf_get_x_and_y (type (t_netcdf4_file) NCFILE) private
Definition at line 1207 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, constants_and_conversions::ltrue, nc_x, nc_y, and nf_get_variable_vector_double().
Referenced by netcdf_open_and_prepare_as_input(), and netcdf_open_and_prepare_for_merging().
nf_open_file()
subroutine netcdf4_support::nf_open_file (type (t_netcdf4_file) NCFILE, character (len=*) sFilename, integer (kind=c_int), optional iLU) private
Definition at line 1300 of file netcdf4_support.F90.
References logfiles::logs, nc_readonly, netcdf_dump_cdl(), netcdf_format_string, and nf_trap().
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and netcdf_open_file().
netcdf_open_file()
subroutine, public netcdf4_support::netcdf_open_file (type (t_netcdf4_file) NCFILE, character (len=*) sFilename, integer (kind=c_int), optional iLU)
Similarly, the structure of the file may be slightly different from the previous file
CANNOT ASSUME THAT THIS WILL REMAIN CONSTANT ACROSS FILES FROM THE SAME PROVIDER!! MUST UPDATE TO ENSURE THAT THE INDICES ARE STILL RELEVANT
retrieve the origin for the time units associated with this file
retrieve the time value specific to this file
establish scale_factor and add_offset values, if present
Definition at line 1332 of file netcdf4_support.F90.
References nc_time, nf_calculate_time_range(), nf_get_first_and_last(), nf_get_scale_and_offset(), nf_get_time_units(), nf_get_time_vals(), nf_get_variable_id_and_type(), nf_open_file(), nf_populate_dimension_struct(), and nf_populate_variable_struct().
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub(), and data_catalog_entry::getvalues_static_netcdf_sub().
nf_trap()
subroutine netcdf4_support::nf_trap (integer (kind=c_int) iResultCode, character (len=*), optional sFilename, integer (kind=c_int), optional iLineNumber) private
Definition at line 1384 of file netcdf4_support.F90.
References constants_and_conversions::char_ptr_to_fortran_string(), constants_and_conversions::lfalse, and logfiles::logs.
Referenced by netcdf_close_file(), netcdf_put_packed_variable_array(), netcdf_put_variable_array(), netcdf_put_variable_vector(), nf_create(), nf_define_deflate(), nf_define_dimension(), nf_define_dimensions(), nf_define_variable(), nf_define_variables(), nf_enddef(), nf_get_variable_array_as_vector_double(), nf_get_variable_array_as_vector_float(), nf_get_variable_array_as_vector_int(), nf_get_variable_array_as_vector_short(), nf_get_variable_array_double(), nf_get_variable_array_float(), nf_get_variable_array_short(), nf_get_variable_vector_double(), nf_get_variable_vector_float(), nf_get_variable_vector_int(), nf_get_variable_vector_short(), nf_open_file(), nf_populate_attribute_struct(), nf_populate_dimension_struct(), nf_populate_variable_struct(), and nf_put_attribute().
netcdf_close_file()
subroutine, public netcdf4_support::netcdf_close_file (type (t_netcdf4_file) NCFILE)
Definition at line 1425 of file netcdf4_support.F90.
References logfiles::logs, and nf_trap().
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub().
netcdf_deallocate_data_struct()
subroutine, public netcdf4_support::netcdf_deallocate_data_struct (type (t_netcdf4_file) NCFILE)
Definition at line 1438 of file netcdf4_support.F90.
netcdf_nullify_data_struct()
subroutine, public netcdf4_support::netcdf_nullify_data_struct (type (t_netcdf4_file) NCFILE)
Definition at line 1469 of file netcdf4_support.F90.
Referenced by data_catalog_entry::nullify_pointers_sub().
nf_populate_dimension_struct()
subroutine netcdf4_support::nf_populate_dimension_struct (type (t_netcdf4_file) NCFILE) private
Definition at line 1483 of file netcdf4_support.F90.
References constants_and_conversions::c_to_fortran_string(), and nf_trap().
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and netcdf_open_file().
nf_populate_variable_struct()
subroutine netcdf4_support::nf_populate_variable_struct (type (t_netcdf4_file) NCFILE) private
Definition at line 1522 of file netcdf4_support.F90.
References constants_and_conversions::c_to_fortran_string(), nc_global, nf_populate_attribute_struct(), and nf_trap().
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and netcdf_open_file().
nf_populate_attribute_struct()
subroutine netcdf4_support::nf_populate_attribute_struct (type (t_netcdf4_file), intent(inout) NCFILE, type (t_netcdf_attribute), pointer pNC_ATT, integer (kind=c_int) iNC_VarID, integer (kind=c_int) iAttNum) private
Definition at line 1611 of file netcdf4_support.F90.
References constants_and_conversions::c_to_fortran_string(), nc_char, nc_double, nc_float, nc_int, nc_short, and nf_trap().
Referenced by nf_populate_variable_struct().
netcdf_get_variable_id_for_variable()
subroutine, public netcdf4_support::netcdf_get_variable_id_for_variable (type (t_netcdf4_file), intent(inout) NCFILE, character (len=*), intent(in) variable_name, integer (kind=c_int), intent(out) variable_id)
Definition at line 1721 of file netcdf4_support.F90.
References constants_and_conversions::false, and constants_and_conversions::true.
netcdf_get_attribute_list_for_variable()
subroutine, public netcdf4_support::netcdf_get_attribute_list_for_variable (type (t_netcdf4_file), intent(inout) NCFILE, character (len=*), intent(in) variable_name, type (string_list_t), intent(out) attribute_name_list, type (string_list_t), intent(out) attribute_value_list)
Definition at line 1761 of file netcdf4_support.F90.
References constants_and_conversions::false, nc_char, nc_double, nc_float, nc_int, nc_short, and constants_and_conversions::true.
netcdf_get_variable_list()
subroutine, public netcdf4_support::netcdf_get_variable_list (type (t_netcdf4_file) NCFILE, type (string_list_t) variable_list)
Definition at line 1841 of file netcdf4_support.F90.
netcdf_update_time_starting_index()
logical (kind=c_bool) function, public netcdf4_support::netcdf_update_time_starting_index (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iJulianDay)
Definition at line 1862 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, constants_and_conversions::ltrue, nc_time, and nf_julian_day_to_index_adj().
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub().
netcdf_get_variable_slice()
subroutine, public netcdf4_support::netcdf_get_variable_slice (type (t_netcdf4_file) NCFILE, real (kind=c_float), dimension(:,:), optional rValues, integer (kind=c_int), dimension(:,:), optional iValues)
Todo:
expand this to cover more variable types
Definition at line 1885 of file netcdf4_support.F90.
References nc_float, nc_int, nc_short, nc_z, nf_get_variable_slice_float(), nf_get_variable_slice_int(), nf_get_variable_slice_short(), and exceptions::warn().
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub(), and data_catalog_entry::getvalues_static_netcdf_sub().
nf_get_variable_slice_short()
subroutine netcdf4_support::nf_get_variable_slice_short (type (t_netcdf4_file) NCFILE, real (kind=c_float), dimension(:,:) rValues) private
Definition at line 1915 of file netcdf4_support.F90.
References nc_by, nc_first, nc_last, nc_time, nc_x, nc_y, nc_z, nf_get_variable_array_as_vector_short(), nf_return_varindex(), and exceptions::warn().
Referenced by netcdf_get_variable_slice().
nf_get_variable_slice_int()
subroutine netcdf4_support::nf_get_variable_slice_int (type (t_netcdf4_file) NCFILE, real (kind=c_float), dimension(:,:) rValues) private
Definition at line 1987 of file netcdf4_support.F90.
References nc_by, nc_first, nc_last, nc_time, nc_x, nc_y, nc_z, nf_get_variable_array_as_vector_int(), nf_return_varindex(), and exceptions::warn().
Referenced by netcdf_get_variable_slice().
nf_get_variable_slice_float()
subroutine netcdf4_support::nf_get_variable_slice_float (type (t_netcdf4_file) NCFILE, real (kind=c_float), dimension(:,:) rValues) private
Definition at line 2060 of file netcdf4_support.F90.
References nc_by, nc_first, nc_last, nc_time, nc_x, nc_y, nc_z, nf_get_variable_array_as_vector_float(), nf_return_varindex(), and exceptions::warn().
Referenced by netcdf_get_variable_slice().
nf_get_variable_vector_short()
subroutine netcdf4_support::nf_get_variable_vector_short (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t) iNC_Start, integer (kind=c_size_t) iNC_Count, integer (kind=c_ptrdiff_t) iNC_Stride, integer (kind=c_short), dimension(:) iNC_Vars) private
Definition at line 2130 of file netcdf4_support.F90.
References nf_trap().
Referenced by nf_get_first_and_last().
nf_get_variable_array_short()
subroutine netcdf4_support::nf_get_variable_array_short (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t), dimension(:) iNC_Start, integer (kind=c_size_t), dimension(:) iNC_Count, integer (kind=c_size_t), dimension(:) iNC_Stride, integer (kind=c_short), dimension(:,:) iNC_Vars) private
Definition at line 2151 of file netcdf4_support.F90.
References nf_trap().
nf_get_variable_array_as_vector_short()
subroutine netcdf4_support::nf_get_variable_array_as_vector_short (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t), dimension(:) iNC_Start, integer (kind=c_size_t), dimension(:) iNC_Count, integer (kind=c_ptrdiff_t), dimension(:) iNC_Stride, integer (kind=c_short), dimension(:) iNC_Vars) private
Definition at line 2172 of file netcdf4_support.F90.
References nf_trap().
Referenced by nf_get_variable_slice_short().
nf_get_variable_array_as_vector_int()
subroutine netcdf4_support::nf_get_variable_array_as_vector_int (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t), dimension(:) iNC_Start, integer (kind=c_size_t), dimension(:) iNC_Count, integer (kind=c_ptrdiff_t), dimension(:) iNC_Stride, integer (kind=c_int), dimension(:) iNC_Vars) private
Definition at line 2193 of file netcdf4_support.F90.
References nf_trap().
Referenced by nf_get_variable_slice_int().
nf_get_variable_vector_int()
subroutine netcdf4_support::nf_get_variable_vector_int (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t) iNC_Start, integer (kind=c_size_t) iNC_Count, integer (kind=c_ptrdiff_t) iNC_Stride, integer (kind=c_int), dimension(:) iNC_Vars) private
Definition at line 2214 of file netcdf4_support.F90.
References nf_trap().
Referenced by nf_get_first_and_last().
nf_get_variable_vector_double()
subroutine netcdf4_support::nf_get_variable_vector_double (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t) iNC_Start, integer (kind=c_size_t) iNC_Count, integer (kind=c_size_t) iNC_Stride, real (kind=c_double), dimension(:) dpNC_Vars) private
Definition at line 2235 of file netcdf4_support.F90.
References nf_trap().
Referenced by nf_get_first_and_last(), nf_get_time_vals(), and nf_get_x_and_y().
nf_get_variable_array_double()
subroutine netcdf4_support::nf_get_variable_array_double (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t), dimension(:) iNC_Start, integer (kind=c_size_t), dimension(:) iNC_Count, integer (kind=c_size_t), dimension(:) iNC_Stride, real (kind=c_double), dimension(:,:) dpNC_Vars) private
Definition at line 2256 of file netcdf4_support.F90.
References nf_trap().
nf_get_variable_array_as_vector_double()
subroutine netcdf4_support::nf_get_variable_array_as_vector_double (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t), dimension(:) iNC_Start, integer (kind=c_size_t), dimension(:) iNC_Count, integer (kind=c_ptrdiff_t), dimension(:) iNC_Stride, real (kind=c_double), dimension(:) dpNC_Vars) private
Definition at line 2277 of file netcdf4_support.F90.
References nf_trap().
nf_get_variable_vector_float()
subroutine netcdf4_support::nf_get_variable_vector_float (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t) iNC_Start, integer (kind=c_size_t) iNC_Count, integer (kind=c_ptrdiff_t) iNC_Stride, real (kind=c_float), dimension(:) rNC_Vars) private
Definition at line 2298 of file netcdf4_support.F90.
References nf_trap().
Referenced by nf_get_first_and_last().
nf_get_variable_array_float()
subroutine netcdf4_support::nf_get_variable_array_float (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t), dimension(:) iNC_Start, integer (kind=c_size_t), dimension(:) iNC_Count, integer (kind=c_ptrdiff_t), dimension(:) iNC_Stride, real (kind=c_float), dimension(:,:) rNC_Vars) private
Definition at line 2319 of file netcdf4_support.F90.
References nf_trap().
nf_get_variable_array_as_vector_float()
subroutine netcdf4_support::nf_get_variable_array_as_vector_float (type (t_netcdf4_file), intent(inout) NCFILE, integer (kind=c_int) iNC_VarID, integer (kind=c_size_t), dimension(:) iNC_Start, integer (kind=c_size_t), dimension(:) iNC_Count, integer (kind=c_ptrdiff_t), dimension(:) iNC_Stride, real (kind=c_float), dimension(:) rNC_Vars) private
Definition at line 2340 of file netcdf4_support.F90.
References nf_trap().
Referenced by nf_get_variable_slice_float().
netcdf_dump_cdl()
subroutine, public netcdf4_support::netcdf_dump_cdl (type (t_netcdf4_file) NCFILE, integer iLU)
Definition at line 2360 of file netcdf4_support.F90.
References netcdf_data_type.
Referenced by netcdf_open_and_prepare_as_input(), and nf_open_file().
nf_get_first_and_last()
real (kind=c_double) function, dimension(0:1) netcdf4_support::nf_get_first_and_last (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarIndex) private
if there is only one day of data in this NetCDF file, the first day equals the last day
Definition at line 2472 of file netcdf4_support.F90.
References nc_double, nc_first, nc_float, nc_int, nc_last, nc_short, nf_get_variable_vector_double(), nf_get_variable_vector_float(), nf_get_variable_vector_int(), nf_get_variable_vector_short(), nf_return_dimsize(), and exceptions::warn().
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and netcdf_open_file().
nf_calculate_time_range()
subroutine netcdf4_support::nf_calculate_time_range (type (t_netcdf4_file), intent(inout) NCFILE) private
Definition at line 2564 of file netcdf4_support.F90.
References datetime::julian_day(), nc_first, and nc_last.
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and netcdf_open_file().
nf_get_time_units()
subroutine netcdf4_support::nf_get_time_units (type (t_netcdf4_file), intent(inout) NCFILE) private
should be "days"
should be "since"
Todo:
this does not appear to have the fix that was applied to the master swb branch to deal with cases where no time values are given at all
Definition at line 2578 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, constants_and_conversions::ltrue, and nc_time.
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and netcdf_open_file().
nf_get_xyz_units()
subroutine netcdf4_support::nf_get_xyz_units (type (t_netcdf4_file), intent(inout) NCFILE) private
Definition at line 2639 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, constants_and_conversions::ltrue, nc_y, and nc_z.
Referenced by netcdf_open_and_prepare_as_input().
nf_get_scale_and_offset()
subroutine netcdf4_support::nf_get_scale_and_offset (type (t_netcdf4_file), intent(inout) NCFILE) private
Now repeat the process for "add_offset" attribute
Definition at line 2678 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, constants_and_conversions::ltrue, and nc_z.
Referenced by netcdf_open_and_prepare_as_input(), and netcdf_open_file().
nf_get_variable_id_and_type()
subroutine netcdf4_support::nf_get_variable_id_and_type (type (t_netcdf4_file), intent(inout) NCFILE, logical (kind=c_bool), intent(in), optional strict_asserts) private
Definition at line 2728 of file netcdf4_support.F90.
References nc_time, nc_x, nc_y, nc_z, constants_and_conversions::true, and exceptions::warn().
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_as_output(), netcdf_open_and_prepare_as_output_archive(), netcdf_open_and_prepare_for_merging(), and netcdf_open_file().
nf_return_index_double()
integer (kind=c_int) function netcdf4_support::nf_return_index_double (real (kind=c_double), dimension(:) rValues, real (kind=c_double) rTargetValue) private
Definition at line 2800 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, logfiles::logs, and constants_and_conversions::ltrue.
Referenced by netcdf_coord_to_col_row().
netcdf_coord_to_col_row()
integer (kind=c_size_t) function, dimension(2), public netcdf4_support::netcdf_coord_to_col_row (type (t_netcdf4_file) NCFILE, real (kind=c_double) rX, real (kind=c_double) rY)
Definition at line 2835 of file netcdf4_support.F90.
References grid::column, exceptions::die(), nf_return_index_double(), and grid::row.
Referenced by netcdf_open_and_prepare_as_input().
nf_get_varid()
integer (kind=c_int) function netcdf4_support::nf_get_varid (type (t_netcdf4_file) NCFILE, character (len=*) sVariableName) private
Definition at line 2878 of file netcdf4_support.F90.
nf_create()
subroutine netcdf4_support::nf_create (type (t_netcdf4_file) NCFILE, character (len=*) sFilename, integer (kind=c_int), optional iLU) private
Definition at line 2906 of file netcdf4_support.F90.
References constants_and_conversions::fortran_to_c_string(), logfiles::logs, nc_format_netcdf4, nc_netcdf4, and nf_trap().
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_define_deflate()
subroutine netcdf4_support::nf_define_deflate (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarID, integer (kind=c_int) iShuffle, integer (kind=c_int) iDeflate, integer (kind=c_int) iDeflate_level) private
Definition at line 2946 of file netcdf4_support.F90.
References nf_trap().
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_enddef()
subroutine netcdf4_support::nf_enddef (type (t_netcdf4_file) NCFILE) private
Definition at line 2965 of file netcdf4_support.F90.
References nf_trap().
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_define_dimension()
integer (kind=c_int) function netcdf4_support::nf_define_dimension (type (t_netcdf4_file) NCFILE, character (len=*) sDimensionName, integer (kind=c_int) iDimensionSize) private
Definition at line 2977 of file netcdf4_support.F90.
References nf_trap().
nf_define_dimensions()
subroutine netcdf4_support::nf_define_dimensions (type (t_netcdf4_file) NCFILE) private
Definition at line 2998 of file netcdf4_support.F90.
References nf_trap().
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_set_standard_dimensions()
subroutine netcdf4_support::nf_set_standard_dimensions (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iNX, integer (kind=c_int) iNY) private
define the time dimension;
define the y dimension;
define the x dimension;
Definition at line 3024 of file netcdf4_support.F90.
References nc_time, nc_unlimited, nc_x, and nc_y.
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_set_standard_variables()
subroutine netcdf4_support::nf_set_standard_variables (type (t_netcdf4_file) NCFILE, character (len=*) sVarName_z, logical (kind=c_bool), optional lLatLon) private
Definition at line 3061 of file netcdf4_support.F90.
References constants_and_conversions::lfalse, nc_crs, nc_double, nc_float, nc_int, nc_lat, nc_lon, nc_time, nc_x, nc_y, and nc_z.
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_set_global_attributes()
subroutine netcdf4_support::nf_set_global_attributes (type (t_netcdf4_file) NCFILE, character (len=*), intent(in) sDataType, character (len=*), intent(in), optional executable_name, type (string_list_t), intent(in), optional, pointer history_list, character (len=*), intent(in), optional sSourceFile) private
Definition at line 3141 of file netcdf4_support.F90.
References nc_char.
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_set_standard_attributes()
subroutine netcdf4_support::nf_set_standard_attributes (type (t_netcdf4_file) NCFILE, character (len=*) sOriginText, character (len=*), optional PROJ4_string, logical (kind=c_bool), optional lLatLon, real (kind=c_float), optional fValidMin, real (kind=c_float), optional fValidMax) private
Definition at line 3238 of file netcdf4_support.F90.
References nc_char, nc_crs, nc_fill_float, nc_float, nc_int, nc_lat, nc_lon, nc_time, nc_x, nc_y, and nc_z.
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_put_x_and_y()
subroutine netcdf4_support::nf_put_x_and_y (type (t_netcdf4_file) NCFILE, real (kind=c_double), dimension(:) dpX, real (kind=c_double), dimension(:) dpY) private
Definition at line 3581 of file netcdf4_support.F90.
References nc_x, nc_y, and netcdf_put_variable_vector().
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_put_lat_and_lon()
subroutine netcdf4_support::nf_put_lat_and_lon (type (t_netcdf4_file) NCFILE, real (kind=c_double), dimension(:,:) dpLat, real (kind=c_double), dimension(:,:) dpLon) private
Definition at line 3613 of file netcdf4_support.F90.
References nc_lat, nc_lon, and netcdf_put_variable_array().
Referenced by netcdf_open_and_prepare_as_output().
nf_define_variable()
integer (kind=c_int) function netcdf4_support::nf_define_variable (type (t_netcdf4_file) NCFILE, character (len=*) sVariableName, integer (kind=c_int) iVariableType, integer (kind=c_int) iNumberOfDimensions, integer (kind=c_int), dimension(:) iDimIDs) private
Definition at line 3645 of file netcdf4_support.F90.
References nf_trap().
nf_define_variables()
subroutine netcdf4_support::nf_define_variables (type (t_netcdf4_file) NCFILE) private
Definition at line 3668 of file netcdf4_support.F90.
References nf_trap().
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nf_put_attribute()
subroutine netcdf4_support::nf_put_attribute (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarID, character (len=*) sAttributeName, character (len=*), dimension(:), optional sAttributeValue, integer (kind=c_int), dimension(:), optional iAttributeValue, real (kind=c_float), dimension(:), optional rAttributeValue, real (kind=c_double), dimension(:), optional dpAttributeValue) private
Definition at line 3700 of file netcdf4_support.F90.
References nc_double, nc_float, nc_int, and nf_trap().
Referenced by nf_put_attributes().
nf_put_attributes()
subroutine netcdf4_support::nf_put_attributes (type (t_netcdf4_file) NCFILE) private
Definition at line 3768 of file netcdf4_support.F90.
References nc_char, nc_double, nc_float, nc_global, nc_int, and nf_put_attribute().
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
netcdf_put_variable_array()
subroutine, public netcdf4_support::netcdf_put_variable_array (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarID, integer (kind=c_size_t), dimension(:) iStart, integer (kind=c_size_t), dimension(:) iCount, integer (kind=c_ptrdiff_t), dimension(:) iStride, integer (kind=c_int), dimension(:,:), optional iValues, integer (kind=c_short), dimension(:,:), optional i2Values, real (kind=c_float), dimension(:,:), optional rValues, real (kind=c_double), dimension(:,:), optional dpValues)
Definition at line 3919 of file netcdf4_support.F90.
References nf_trap().
Referenced by nf_put_lat_and_lon(), and data_catalog_entry::put_values_to_local_netcdf_sub().
netcdf_put_packed_variable_array()
subroutine, public netcdf4_support::netcdf_put_packed_variable_array (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarID, integer (kind=c_size_t), dimension(:) iStart, integer (kind=c_size_t), dimension(:) iCount, integer (kind=c_ptrdiff_t), dimension(:) iStride, logical (kind=c_bool), dimension(:,:) lMask, integer (kind=c_int), dimension(:), optional iValues, integer (kind=c_int), dimension(:,:), optional iField, integer (kind=c_short), dimension(:), optional i2Values, integer (kind=c_short), dimension(:,:), optional i2Field, real (kind=c_float), dimension(:), optional rValues, real (kind=c_float), dimension(:,:), optional rField, real (kind=c_double), dimension(:), optional dpValues, real (kind=c_double), dimension(:,:), optional dpField)
Definition at line 3978 of file netcdf4_support.F90.
References nf_trap().
Referenced by fog__monthly_grid::fog_monthly_grid_calculate().
netcdf_put_variable_vector()
subroutine, public netcdf4_support::netcdf_put_variable_vector (type (t_netcdf4_file) NCFILE, integer (kind=c_int) iVarID, integer (kind=c_size_t), dimension(:) iStart, integer (kind=c_size_t), dimension(:) iCount, integer (kind=c_ptrdiff_t), dimension(:) iStride, integer (kind=c_int), dimension(:), optional iValues, integer (kind=c_short), dimension(:), optional i2Values, real (kind=c_float), dimension(:), optional rValues, real (kind=c_double), dimension(:), optional dpValues)
Definition at line 4041 of file netcdf4_support.F90.
References nf_trap().
Referenced by fog__monthly_grid::fog_monthly_grid_calculate(), nf_put_x_and_y(), and data_catalog_entry::put_values_to_local_netcdf_sub().
Variable Documentation
nc_readonly
integer(kind=c_int), public netcdf4_support::nc_readonly = 0
Definition at line 52 of file netcdf4_support.F90.
Referenced by nf_open_file().
nc_readwrite
integer(kind=c_int), public netcdf4_support::nc_readwrite = 1
Definition at line 53 of file netcdf4_support.F90.
nc_nat
integer(kind=c_int), parameter netcdf4_support::nc_nat = 0 private
Definition at line 55 of file netcdf4_support.F90.
nc_byte
integer(kind=c_int), parameter netcdf4_support::nc_byte = 1 private
Definition at line 56 of file netcdf4_support.F90.
nc_char
integer(kind=c_int), parameter netcdf4_support::nc_char = 2 private
Definition at line 57 of file netcdf4_support.F90.
Referenced by netcdf_get_attribute_list_for_variable(), nf_populate_attribute_struct(), nf_put_attributes(), nf_set_global_attributes(), and nf_set_standard_attributes().
nc_short
integer(kind=c_int), parameter netcdf4_support::nc_short = 3 private
Definition at line 58 of file netcdf4_support.F90.
Referenced by netcdf_get_attribute_list_for_variable(), netcdf_get_variable_slice(), nf_get_first_and_last(), and nf_populate_attribute_struct().
nc_int
integer(kind=c_int), parameter netcdf4_support::nc_int = 4 private
Definition at line 59 of file netcdf4_support.F90.
Referenced by netcdf_get_attribute_list_for_variable(), netcdf_get_variable_slice(), nf_get_first_and_last(), nf_populate_attribute_struct(), nf_put_attribute(), nf_put_attributes(), nf_set_standard_attributes(), and nf_set_standard_variables().
nc_float
integer(kind=c_int), parameter, public netcdf4_support::nc_float = 5
Definition at line 60 of file netcdf4_support.F90.
Referenced by netcdf_get_attribute_list_for_variable(), netcdf_get_variable_slice(), nf_get_first_and_last(), nf_populate_attribute_struct(), nf_put_attribute(), nf_put_attributes(), nf_set_standard_attributes(), and nf_set_standard_variables().
nc_double
integer(kind=c_int), parameter netcdf4_support::nc_double = 6 private
Definition at line 61 of file netcdf4_support.F90.
Referenced by netcdf_get_attribute_list_for_variable(), nf_get_first_and_last(), nf_populate_attribute_struct(), nf_put_attribute(), nf_put_attributes(), and nf_set_standard_variables().
nc_fill_char
integer(kind=c_int), parameter netcdf4_support::nc_fill_char = 0 private
Definition at line 63 of file netcdf4_support.F90.
nc_fill_byte
integer(kind=c_int), parameter netcdf4_support::nc_fill_byte = -127 private
Definition at line 64 of file netcdf4_support.F90.
nc_fill_short
integer(kind=c_int), parameter netcdf4_support::nc_fill_short = -32767 private
Definition at line 65 of file netcdf4_support.F90.
nc_fill_int
integer(kind=c_int), parameter, public netcdf4_support::nc_fill_int = -2147483647
Definition at line 66 of file netcdf4_support.F90.
nc_fill_float
real(kind=c_float), parameter, public netcdf4_support::nc_fill_float = -9.9e-20_c_float
Definition at line 68 of file netcdf4_support.F90.
Referenced by nf_set_standard_attributes().
nc_fill_double
real(kind=c_double), parameter netcdf4_support::nc_fill_double = -9.9e-20_c_double private
Definition at line 69 of file netcdf4_support.F90.
nc_nowrite
integer(kind=c_int), parameter netcdf4_support::nc_nowrite = 0 private
Definition at line 74 of file netcdf4_support.F90.
nc_write
integer(kind=c_int), parameter netcdf4_support::nc_write = 1 private
Definition at line 75 of file netcdf4_support.F90.
nc_clobber
integer(kind=c_int), parameter netcdf4_support::nc_clobber = 0 private
Definition at line 76 of file netcdf4_support.F90.
nc_noclobber
integer(kind=c_int), parameter netcdf4_support::nc_noclobber = 4 private
Definition at line 77 of file netcdf4_support.F90.
nc_fill
integer(kind=c_int), parameter netcdf4_support::nc_fill = 0 private
Definition at line 78 of file netcdf4_support.F90.
nc_nofill
integer(kind=c_int), parameter netcdf4_support::nc_nofill = 256 private
Definition at line 79 of file netcdf4_support.F90.
nc_lock
integer(kind=c_int), parameter netcdf4_support::nc_lock = 1024 private
Definition at line 80 of file netcdf4_support.F90.
nc_share
integer(kind=c_int), parameter netcdf4_support::nc_share = 2048 private
Definition at line 81 of file netcdf4_support.F90.
nc_strict_nc3
integer(kind=c_int), parameter netcdf4_support::nc_strict_nc3 = 8 private
Definition at line 82 of file netcdf4_support.F90.
nc_64bit_offset
integer(kind=c_int), parameter netcdf4_support::nc_64bit_offset = 512 private
Definition at line 83 of file netcdf4_support.F90.
nc_sizehint_default
integer(kind=c_int), parameter netcdf4_support::nc_sizehint_default = 0 private
Definition at line 84 of file netcdf4_support.F90.
nc_align_chunk
integer(kind=c_int), parameter netcdf4_support::nc_align_chunk = -1 private
Definition at line 85 of file netcdf4_support.F90.
nc_format_classic
integer(kind=c_int), parameter netcdf4_support::nc_format_classic = 1 private
Definition at line 86 of file netcdf4_support.F90.
nc_format_64bit
integer(kind=c_int), parameter netcdf4_support::nc_format_64bit = 2 private
Definition at line 87 of file netcdf4_support.F90.
nc_format_netcdf4
integer(kind=c_int), parameter netcdf4_support::nc_format_netcdf4 = 3 private
Definition at line 88 of file netcdf4_support.F90.
Referenced by nf_create().
nc_format_netcdf4_classic
integer(kind=c_int), parameter netcdf4_support::nc_format_netcdf4_classic = 4 private
Definition at line 89 of file netcdf4_support.F90.
nc_max_dims
integer(kind=c_int), parameter netcdf4_support::nc_max_dims = 1024 private
Definition at line 92 of file netcdf4_support.F90.
nc_max_attrs
integer(kind=c_int), parameter netcdf4_support::nc_max_attrs = 8192 private
Definition at line 93 of file netcdf4_support.F90.
nc_max_vars
integer(kind=c_int), parameter netcdf4_support::nc_max_vars = 8192 private
Definition at line 94 of file netcdf4_support.F90.
nc_max_name
integer(kind=c_int), parameter netcdf4_support::nc_max_name = 256 private
Definition at line 95 of file netcdf4_support.F90.
nc_shuffle_yes
integer (kind=c_int), parameter netcdf4_support::nc_shuffle_yes = 1 private
Definition at line 97 of file netcdf4_support.F90.
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nc_shuffle_no
integer (kind=c_int), parameter netcdf4_support::nc_shuffle_no = 0 private
Definition at line 98 of file netcdf4_support.F90.
nc_deflate_yes
integer (kind=c_int), parameter netcdf4_support::nc_deflate_yes = 1 private
Definition at line 99 of file netcdf4_support.F90.
Referenced by netcdf_open_and_prepare_as_output(), and netcdf_open_and_prepare_as_output_archive().
nc_deflate_no
integer (kind=c_int), parameter netcdf4_support::nc_deflate_no = 0 private
Definition at line 100 of file netcdf4_support.F90.
nc_netcdf4
integer(kind=c_int), parameter netcdf4_support::nc_netcdf4 = 4096 private
Definition at line 102 of file netcdf4_support.F90.
Referenced by nf_create().
nc_classic_model
integer(kind=c_int), parameter netcdf4_support::nc_classic_model = 256 private
Definition at line 103 of file netcdf4_support.F90.
nc_unlimited
integer(kind=c_int), parameter netcdf4_support::nc_unlimited = 0 private
Definition at line 106 of file netcdf4_support.F90.
Referenced by nf_set_standard_dimensions().
nc_global
integer(kind=c_int), parameter netcdf4_support::nc_global = -1 private
Definition at line 107 of file netcdf4_support.F90.
Referenced by nf_populate_variable_struct(), and nf_put_attributes().
nc_time
integer (c_int), parameter, public netcdf4_support::nc_time = 0
Definition at line 109 of file netcdf4_support.F90.
Referenced by fog__monthly_grid::fog_monthly_grid_calculate(), netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), netcdf_open_file(), netcdf_update_time_starting_index(), nf_get_time_units(), nf_get_time_vals(), nf_get_variable_id_and_type(), nf_get_variable_slice_float(), nf_get_variable_slice_int(), nf_get_variable_slice_short(), nf_set_standard_attributes(), nf_set_standard_dimensions(), nf_set_standard_variables(), nf_set_start_count_stride(), and data_catalog_entry::put_values_to_local_netcdf_sub().
nc_y
integer (c_int), parameter, public netcdf4_support::nc_y = 1
Definition at line 110 of file netcdf4_support.F90.
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_as_output_archive(), nf_get_variable_id_and_type(), nf_get_variable_slice_float(), nf_get_variable_slice_int(), nf_get_variable_slice_short(), nf_get_x_and_y(), nf_get_xyz_units(), nf_put_x_and_y(), nf_set_standard_attributes(), nf_set_standard_dimensions(), nf_set_standard_variables(), and nf_set_start_count_stride().
nc_x
integer (c_int), parameter, public netcdf4_support::nc_x = 2
Definition at line 111 of file netcdf4_support.F90.
Referenced by netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_as_output_archive(), nf_get_variable_id_and_type(), nf_get_variable_slice_float(), nf_get_variable_slice_int(), nf_get_variable_slice_short(), nf_get_x_and_y(), nf_put_x_and_y(), nf_set_standard_attributes(), nf_set_standard_dimensions(), nf_set_standard_variables(), and nf_set_start_count_stride().
nc_z
integer (c_int), parameter, public netcdf4_support::nc_z = 3
Definition at line 112 of file netcdf4_support.F90.
Referenced by fog__monthly_grid::fog_monthly_grid_calculate(), data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_static_netcdf_sub(), netcdf_get_variable_slice(), netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_as_output(), netcdf_open_and_prepare_as_output_archive(), nf_get_scale_and_offset(), nf_get_variable_id_and_type(), nf_get_variable_slice_float(), nf_get_variable_slice_int(), nf_get_variable_slice_short(), nf_get_xyz_units(), nf_set_standard_attributes(), nf_set_standard_variables(), nf_set_z_variable_name(), and data_catalog_entry::put_values_to_local_netcdf_sub().
nc_crs
integer (c_int), parameter, public netcdf4_support::nc_crs = 4
Definition at line 113 of file netcdf4_support.F90.
Referenced by nf_set_standard_attributes(), and nf_set_standard_variables().
nc_lat
integer (c_int), parameter, public netcdf4_support::nc_lat = 5
Definition at line 114 of file netcdf4_support.F90.
Referenced by nf_put_lat_and_lon(), nf_set_standard_attributes(), and nf_set_standard_variables().
nc_lon
integer (c_int), parameter, public netcdf4_support::nc_lon = 6
Definition at line 115 of file netcdf4_support.F90.
Referenced by nf_put_lat_and_lon(), nf_set_standard_attributes(), and nf_set_standard_variables().
nc_first
integer (kind=c_int), parameter netcdf4_support::nc_first = 0 private
Definition at line 117 of file netcdf4_support.F90.
Referenced by nf_calculate_time_range(), nf_get_first_and_last(), nf_get_variable_slice_float(), nf_get_variable_slice_int(), nf_get_variable_slice_short(), and nf_set_iteration_bounds().
nc_last
integer (kind=c_int), parameter netcdf4_support::nc_last = 1 private
Definition at line 118 of file netcdf4_support.F90.
Referenced by nf_calculate_time_range(), nf_get_first_and_last(), nf_get_variable_slice_float(), nf_get_variable_slice_int(), nf_get_variable_slice_short(), and nf_set_iteration_bounds().
nc_by
integer (kind=c_int), parameter netcdf4_support::nc_by = 2 private
Definition at line 119 of file netcdf4_support.F90.
Referenced by nf_get_variable_slice_float(), nf_get_variable_slice_int(), nf_get_variable_slice_short(), and nf_set_iteration_bounds().
nc_left
integer (kind=c_int), parameter, public netcdf4_support::nc_left = 0
Definition at line 121 of file netcdf4_support.F90.
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_static_netcdf_sub(), netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and nf_return_native_coord_bounds().
nc_right
integer (kind=c_int), parameter, public netcdf4_support::nc_right = 1
Definition at line 122 of file netcdf4_support.F90.
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_static_netcdf_sub(), netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and nf_return_native_coord_bounds().
nc_top
integer (kind=c_int), parameter, public netcdf4_support::nc_top = 0
Definition at line 123 of file netcdf4_support.F90.
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_static_netcdf_sub(), netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and nf_return_native_coord_bounds().
nc_bottom
integer (kind=c_int), parameter, public netcdf4_support::nc_bottom = 1
Definition at line 124 of file netcdf4_support.F90.
Referenced by data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_static_netcdf_sub(), netcdf_open_and_prepare_as_input(), netcdf_open_and_prepare_for_merging(), and nf_return_native_coord_bounds().
column
integer (kind=c_int), parameter netcdf4_support::column = 1 private
Definition at line 126 of file netcdf4_support.F90.
row
integer (kind=c_int), parameter netcdf4_support::row = 2 private
Definition at line 127 of file netcdf4_support.F90.
netcdf_format_string
character (len=25), dimension(4), parameter netcdf4_support::netcdf_format_string = ["NC_FORMAT_CLASSIC ", "NC_FORMAT_64BIT ", "NC_FORMAT_NETCDF4 ", "NC_FORMAT_NETCDF4_CLASSIC" ] private
Definition at line 129 of file netcdf4_support.F90.
Referenced by nf_open_file().
netcdf_data_type
character (len=6), dimension(0:6), parameter netcdf4_support::netcdf_data_type = ["nat ", "byte ", "char ", "short ", "int ", "float ", "double" ] private
Definition at line 135 of file netcdf4_support.F90.
Referenced by netcdf_dump_cdl().