SWB 2.0: model_domain Module Reference
model_domain Module Reference
Data Types
interface array_method
type cell_col_row_t
interface index_method
interface minmaxmean
type model_domain_t
Functions/Subroutines
subroutine set_output_directory_sub (this, output_dir_name)
subroutine initialize_grid_sub (this, iNumCols, iNumRows, dX_ll, dY_ll, dGridCellSize)
subroutine initialize_arrays_sub (this)
subroutine initialize_row_column_indices_sub (this)
integer(kind=c_int) function row_column_to_index_fn (this, col_num, row_num)
subroutine initialize_methods_sub (this)
subroutine set_inactive_cells_sub (this)
subroutine get_climate_data (this)
subroutine preflight_check_method_pointers (this)
subroutine set_method_pointers_sub (this, sCmdText, argv_list)
subroutine model_initialize_interception_bucket (this)
subroutine model_calculate_interception_bucket (this)
subroutine model_initialize_interception_gash (this)
subroutine model_calculate_interception_gash (this)
subroutine model_initialize_routing_none (this)
subroutine model_calculate_routing_none (this, indx)
subroutine model_initialize_routing_d8 (this)
subroutine model_calculate_routing_d8 (this, indx)
subroutine model_initialize_continuous_frozen_ground_index (this)
subroutine model_calculate_continuous_frozen_ground_index (this)
subroutine model_initialize_snowfall_original (this)
subroutine model_calculate_snowfall_original (this)
subroutine model_initialize_snowfall_prms (this)
subroutine model_calculate_snowfall_prms (this)
subroutine model_initialize_snowmelt_original (this)
subroutine model_calculate_snowmelt_original (this)
subroutine model_initialize_snowmelt_prms (this)
subroutine model_calculate_snowmelt_prms (this)
subroutine model_initialize_et_hargreaves (this)
subroutine model_calculate_et_hargreaves (this)
subroutine model_initialize_et_daily_grid (this)
subroutine model_calculate_et_daily_grid (this)
subroutine model_initialize_et_monthly_grid (this)
subroutine model_calculate_et_monthly_grid (this)
subroutine model_initialize_et_jensen_haise (this)
subroutine model_calculate_et_jensen_haise (this)
subroutine model_initialize_runoff_curve_number (this)
subroutine model_calculate_runoff_curve_number (this, indx)
subroutine model_initialize_runoff_gridded_values (this)
subroutine model_calculate_runoff_gridded_values (this, indx)
subroutine model_initialize_soil_storage_max_internally_calculated (this)
subroutine model_initialize_soil_storage_max_gridded (this)
subroutine model_initialize_irrigation_none (this)
subroutine model_calculate_irrigation_none (this)
subroutine model_output_irrigation_none (this)
subroutine model_initialize_irrigation (this)
subroutine model_calculate_irrigation (this)
subroutine model_initialize_growing_season (this)
subroutine model_update_growing_season (this)
subroutine model_read_available_water_content_gridded (this)
subroutine model_initialize_available_water_content_gridded (this)
subroutine model_read_available_water_content_depth_integrated (this)
subroutine model_initialize_available_water_content_depth_integrated (this)
subroutine model_initialize_gdd_none (this)
subroutine model_calculate_gdd_none (this)
subroutine model_initialize_gdd (this)
subroutine model_calculate_gdd (this)
subroutine model_dump_variables_none (this)
subroutine model_dump_variables_by_cell (this)
subroutine model_dump_variables (this, unitnum, indx)
subroutine model_initialize_actual_et_thornthwaite_mather_eqns (this)
subroutine model_calculate_actual_et_thornthwaite_mather_eqns (this, indx)
subroutine model_initialize_actual_et_thornthwaite_mather (this)
subroutine model_calculate_actual_et_thornthwaite_mather (this, indx)
subroutine model_initialize_actual_et_fao56 (this)
subroutine model_calculate_actual_et_fao56 (this, indx)
subroutine model_initialize_direct_recharge_none (this)
subroutine model_calculate_direct_recharge_none (this, indx)
subroutine model_initialize_direct_recharge_gridded (this)
subroutine model_calculate_direct_recharge_gridded (this, indx)
subroutine model_initialize_direct_soil_moisture_none (this)
subroutine model_calculate_direct_soil_moisture_none (this, indx)
subroutine model_initialize_direct_soil_moisture_gridded (this)
subroutine model_calculate_direct_soil_moisture_gridded (this, indx)
subroutine model_initialize_maximum_potential_recharge_none (this)
subroutine model_calculate_maximum_potential_recharge_none (this, indx)
subroutine model_initialize_maximum_potential_recharge_gridded (this)
subroutine model_calculate_maximum_potential_recharge_gridded (this, indx)
subroutine model_initialize_crop_coefficient_none (this)
subroutine model_update_crop_coefficient_none (this)
subroutine model_initialize_crop_coefficient_fao56 (this)
subroutine model_update_crop_coefficient_fao56 (this)
subroutine model_initialize_fog_none (this)
subroutine model_initialize_fog_monthly_grid (this)
subroutine model_initialize_precip_normal (this)
subroutine model_calculate_fog_none (this)
subroutine model_calculate_fog_monthly_grid (this)
subroutine model_calculate_mean_air_temperature (this)
subroutine model_get_maximum_air_temperature_normal (this)
subroutine model_get_minimum_air_temperature_normal (this)
subroutine model_get_precip_normal (this)
subroutine model_initialize_precip_method_of_fragments (this)
subroutine model_get_precip_method_of_fragments (this)
subroutine minmaxmean_float (variable, varname, active_cells)
subroutine minmaxmean_int (variable, varname, active_cells)
subroutine summarize_state_variables_sub (this)
Variables
type(cell_col_row_t), dimension(5) dump
type(model_domain_t), public model
real(kind=c_float), dimension(:,:), allocatable, public rooting_depth_max
type(general_grid_t), pointer prooting_depth
Function/Subroutine Documentation
subroutine model_domain::set_output_directory_sub (class (model_domain_t), intent(inout) this, character (len=*), intent(in) output_dir_name) private
Definition at line 310 of file model_domain.F90.
subroutine model_domain::initialize_grid_sub (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) iNumCols, integer (kind=c_int), intent(in) iNumRows, real (kind=c_double), intent(in) dX_ll, real (kind=c_double), intent(in) dY_ll, real (kind=c_double), intent(in) dGridCellSize) private
Definition at line 321 of file model_domain.F90.
References grid::grid_createsimple(), grid::grid_datatype_real, and grid::nc_fill_float.
subroutine model_domain::initialize_arrays_sub (class (model_domain_t), intent(inout) this) private
Definition at line 364 of file model_domain.F90.
References exceptions::die(), constants_and_conversions::lfalse, and exceptions::warn().
subroutine model_domain::initialize_row_column_indices_sub (class (model_domain_t), intent(inout) this) private
Definition at line 499 of file model_domain.F90.
integer (kind=c_int) function model_domain::row_column_to_index_fn (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) col_num, integer (kind=c_int), intent(in) row_num) private
Definition at line 525 of file model_domain.F90.
References constants_and_conversions::false, and constants_and_conversions::true.
subroutine model_domain::initialize_methods_sub (class (model_domain_t), intent(inout) this) private
Definition at line 553 of file model_domain.F90.
subroutine model_domain::set_inactive_cells_sub (class (model_domain_t), intent(inout) this) private
Definition at line 591 of file model_domain.F90.
References awc__depth_integrated::available_water_content, data_catalog::dat, exceptions::die(), constants_and_conversions::false, logfiles::logs, and constants_and_conversions::true.
subroutine model_domain::get_climate_data (class (model_domain_t), intent(inout) this)
Definition at line 699 of file model_domain.F90.
References simulation_datetime::sim_dt.
subroutine model_domain::preflight_check_method_pointers (class (model_domain_t), intent(inout) this) private
Definition at line 732 of file model_domain.F90.
subroutine model_domain::set_method_pointers_sub (class (model_domain_t), intent(inout) this, character (len=*), intent(in) sCmdText, type (string_list_t), intent(in) argv_list) private
Definition at line 797 of file model_domain.F90.
References dump, model_calculate_actual_et_fao56(), model_calculate_actual_et_thornthwaite_mather(), model_calculate_actual_et_thornthwaite_mather_eqns(), model_calculate_direct_recharge_gridded(), model_calculate_direct_soil_moisture_gridded(), model_calculate_et_daily_grid(), model_calculate_et_hargreaves(), model_calculate_et_jensen_haise(), model_calculate_et_monthly_grid(), model_calculate_fog_monthly_grid(), model_calculate_fog_none(), model_calculate_gdd(), model_calculate_interception_bucket(), model_calculate_interception_gash(), model_calculate_irrigation(), model_calculate_irrigation_none(), model_calculate_routing_d8(), model_calculate_routing_none(), model_calculate_runoff_curve_number(), model_calculate_runoff_gridded_values(), model_calculate_snowfall_original(), model_calculate_snowfall_prms(), model_dump_variables_by_cell(), model_get_precip_method_of_fragments(), model_get_precip_normal(), model_initialize_actual_et_fao56(), model_initialize_actual_et_thornthwaite_mather(), model_initialize_actual_et_thornthwaite_mather_eqns(), model_initialize_available_water_content_depth_integrated(), model_initialize_available_water_content_gridded(), model_initialize_crop_coefficient_fao56(), model_initialize_crop_coefficient_none(), model_initialize_direct_recharge_gridded(), model_initialize_direct_soil_moisture_gridded(), model_initialize_et_daily_grid(), model_initialize_et_hargreaves(), model_initialize_et_jensen_haise(), model_initialize_et_monthly_grid(), model_initialize_fog_monthly_grid(), model_initialize_fog_none(), model_initialize_gdd(), model_initialize_interception_bucket(), model_initialize_interception_gash(), model_initialize_irrigation(), model_initialize_irrigation_none(), model_initialize_precip_method_of_fragments(), model_initialize_precip_normal(), model_initialize_routing_d8(), model_initialize_routing_none(), model_initialize_runoff_curve_number(), model_initialize_runoff_gridded_values(), model_initialize_snowfall_original(), model_initialize_snowfall_prms(), model_initialize_soil_storage_max_gridded(), model_initialize_soil_storage_max_internally_calculated(), model_read_available_water_content_depth_integrated(), model_read_available_water_content_gridded(), model_update_crop_coefficient_fao56(), and model_update_crop_coefficient_none().
subroutine model_domain::model_initialize_interception_bucket (class (model_domain_t), intent(inout) this) private
Definition at line 1201 of file model_domain.F90.
References interception__bucket::interception_bucket_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_interception_bucket (class (model_domain_t), intent(inout) this)
Definition at line 1213 of file model_domain.F90.
References interception__bucket::interception_bucket_calculate().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_interception_gash (class (model_domain_t), intent(inout) this)
Definition at line 1226 of file model_domain.F90.
References interception__gash::interception_gash_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_interception_gash (class (model_domain_t), intent(inout) this)
Definition at line 1238 of file model_domain.F90.
References interception__gash::evaporation_to_rainfall_ratio, interception__gash::interception_gash_calculate(), interception__gash::p_sat, interception__gash::stemflow_fraction_table_values, and interception__gash::trunk_storage_capacity_table_values.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_routing_none (class (model_domain_t), intent(inout) this)
Definition at line 1266 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_routing_none (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx) private
Definition at line 1276 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_routing_d8 (class (model_domain_t), intent(inout) this) private
Definition at line 1287 of file model_domain.F90.
References routing__d8::routing_d8_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_routing_d8 (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx)
: what about cases where target is outside of grid? what about flow pointing to open water feature?
Definition at line 1299 of file model_domain.F90.
References routing__d8::target_index.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_continuous_frozen_ground_index (class (model_domain_t), intent(inout) this)
Definition at line 1320 of file model_domain.F90.
References continuous_frozen_ground_index::initialize_continuous_frozen_ground_index().
subroutine model_domain::model_calculate_continuous_frozen_ground_index (class (model_domain_t), intent(inout) this)
Definition at line 1332 of file model_domain.F90.
References continuous_frozen_ground_index::update_continuous_frozen_ground_index().
subroutine model_domain::model_initialize_snowfall_original (class (model_domain_t), intent(inout) this)
Definition at line 1345 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_snowfall_original (class (model_domain_t), intent(inout) this) private
Definition at line 1353 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_snowfall_prms (class (model_domain_t), intent(inout) this) private
Definition at line 1363 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_snowfall_prms (class (model_domain_t), intent(inout) this) private
Definition at line 1371 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_snowmelt_original (class (model_domain_t), intent(inout) this) private
Definition at line 1379 of file model_domain.F90.
subroutine model_domain::model_calculate_snowmelt_original (class (model_domain_t), intent(inout) this) private
Definition at line 1387 of file model_domain.F90.
References snowmelt__original::snowmelt_original_calculate().
subroutine model_domain::model_initialize_snowmelt_prms (class (model_domain_t), intent(inout) this)
Definition at line 1400 of file model_domain.F90.
subroutine model_domain::model_calculate_snowmelt_prms (class (model_domain_t), intent(inout) this) private
Definition at line 1408 of file model_domain.F90.
subroutine model_domain::model_initialize_et_hargreaves (class (model_domain_t), intent(inout) this) private
Definition at line 1416 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_et_hargreaves (class (model_domain_t), intent(inout) this)
Definition at line 1426 of file model_domain.F90.
References et__hargreaves_samani::et_hargreaves_calculate().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_et_daily_grid (class (model_domain_t), intent(inout) this)
Definition at line 1439 of file model_domain.F90.
References et__gridded_values::et_gridded_values_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_et_daily_grid (class (model_domain_t), intent(inout) this)
Definition at line 1451 of file model_domain.F90.
References et__gridded_values::et_gridded_values_calculate(), and et__gridded_values::pet_grid.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_et_monthly_grid (class (model_domain_t), intent(inout) this)
Definition at line 1465 of file model_domain.F90.
References et__gridded_values::et_gridded_values_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_et_monthly_grid (class (model_domain_t), intent(inout) this)
Definition at line 1477 of file model_domain.F90.
References et__gridded_values::et_gridded_values_calculate(), and et__gridded_values::pet_grid.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_et_jensen_haise (class (model_domain_t), intent(inout) this)
Definition at line 1492 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_et_jensen_haise (class (model_domain_t), intent(inout) this)
Definition at line 1502 of file model_domain.F90.
References et__jensen_haise::et_jh_calculate().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_runoff_curve_number (class (model_domain_t), intent(inout) this)
Definition at line 1515 of file model_domain.F90.
References runoff__curve_number::runoff_curve_number_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_runoff_curve_number (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx)
: Should interception term be part of this? Initial abstraction should include some of this interception...
Definition at line 1527 of file model_domain.F90.
References runoff__curve_number::runoff_curve_number_calculate(), and runoff__curve_number::update_previous_5_day_rainfall().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_runoff_gridded_values (class (model_domain_t), intent(inout) this)
Definition at line 1562 of file model_domain.F90.
References runoff__gridded_values::runoff_gridded_values_initialize(), and runoff__gridded_values::runoff_gridded_values_update_ratios().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_runoff_gridded_values (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx)
Definition at line 1581 of file model_domain.F90.
References runoff__gridded_values::runoff_gridded_values_update_ratios(), and runoff__gridded_values::runoff_ratios.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_soil_storage_max_internally_calculated (class (model_domain_t), intent(inout) this)
Todo:
this should be in its own routine...
Definition at line 1609 of file model_domain.F90.
References model, and rooting_depth_max.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_soil_storage_max_gridded (class (model_domain_t), intent(inout) this) private
Definition at line 1636 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_irrigation_none (class (model_domain_t), intent(inout) this) private
Definition at line 1693 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_irrigation_none (class (model_domain_t), intent(inout) this) private
Nothing here to see.
Definition at line 1703 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_output_irrigation_none (class (model_domain_t), intent(inout) this) private
Nothing here to see.
Definition at line 1712 of file model_domain.F90.
subroutine model_domain::model_initialize_irrigation (class (model_domain_t), intent(inout) this) private
Definition at line 1721 of file model_domain.F90.
References irrigation::irrigation__initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_irrigation (class (model_domain_t), intent(inout) this)
Definition at line 1740 of file model_domain.F90.
References irrigation::irrigation__calculate(), and irrigation::irrigation_mask.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_growing_season (class (model_domain_t), intent(inout) this)
Definition at line 1784 of file model_domain.F90.
References growing_season::growing_season_initialize().
subroutine model_domain::model_update_growing_season (class (model_domain_t), intent(inout) this)
Definition at line 1796 of file model_domain.F90.
References growing_season::growing_season_update().
subroutine model_domain::model_read_available_water_content_gridded (class (model_domain_t), intent(inout) this)
Definition at line 1811 of file model_domain.F90.
References awc__gridded_values::awc_gridded_values_read().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_available_water_content_gridded (class (model_domain_t), intent(inout) this)
Definition at line 1823 of file model_domain.F90.
References awc__gridded_values::awc_gridded_values_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_read_available_water_content_depth_integrated (class (model_domain_t), intent(inout) this)
Definition at line 1851 of file model_domain.F90.
References awc__depth_integrated::awc_depth_integrated_read(), and rooting_depth_max.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_available_water_content_depth_integrated (class (model_domain_t), intent(inout) this)
Definition at line 1863 of file model_domain.F90.
References awc__depth_integrated::awc_depth_integrated_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_gdd_none (class (model_domain_t), intent(inout) this)
Nothing here to see.
Definition at line 1894 of file model_domain.F90.
subroutine model_domain::model_calculate_gdd_none (class (model_domain_t), intent(inout) this)
Nothing here to see.
Definition at line 1905 of file model_domain.F90.
subroutine model_domain::model_initialize_gdd (class (model_domain_t), intent(inout) this) private
Definition at line 1914 of file model_domain.F90.
References growing_degree_day::growing_degree_day_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_gdd (class (model_domain_t), intent(inout) this)
Definition at line 1935 of file model_domain.F90.
References growing_degree_day::growing_degree_day_calculate().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_dump_variables_none (class (model_domain_t), intent(inout) this)
Nothing here to see.
Definition at line 1949 of file model_domain.F90.
subroutine model_domain::model_dump_variables_by_cell (class (model_domain_t), intent(inout) this) private
Definition at line 1958 of file model_domain.F90.
References dump, and model_dump_variables().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_dump_variables (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) unitnum, integer (kind=c_int), intent(in) indx) private
Definition at line 2004 of file model_domain.F90.
References runoff__curve_number::prev_5_days_rain.
Referenced by model_dump_variables_by_cell().
subroutine model_domain::model_initialize_actual_et_thornthwaite_mather_eqns (class (model_domain_t), intent(inout) this)
Definition at line 2042 of file model_domain.F90.
References actual_et__thornthwaite_mather_eqns::initialize_actual_et_thornthwaite_mather_eqns().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_actual_et_thornthwaite_mather_eqns (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx)
Definition at line 2055 of file model_domain.F90.
References actual_et__thornthwaite_mather_eqns::calculate_actual_et_thornthwaite_mather_eqns().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_actual_et_thornthwaite_mather (class (model_domain_t), intent(inout) this)
Definition at line 2074 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_actual_et_thornthwaite_mather (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx) private
Definition at line 2082 of file model_domain.F90.
References actual_et__thornthwaite_mather::calculate_actual_et_thornthwaite_mather().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_actual_et_fao56 (class (model_domain_t), intent(inout) this)
Definition at line 2099 of file model_domain.F90.
References actual_et__fao56::initialize_actual_et_fao56().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_actual_et_fao56 (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx)
Definition at line 2111 of file model_domain.F90.
References actual_et__fao56::calculate_actual_et_fao56(), and actual_et__fao56::depletion_fraction.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_direct_recharge_none (class (model_domain_t), intent(inout) this)
Definition at line 2135 of file model_domain.F90.
subroutine model_domain::model_calculate_direct_recharge_none (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx) private
Definition at line 2143 of file model_domain.F90.
subroutine model_domain::model_initialize_direct_recharge_gridded (class (model_domain_t), intent(inout) this) private
Definition at line 2152 of file model_domain.F90.
References direct_recharge__gridded_data::direct_recharge_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_direct_recharge_gridded (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx)
Definition at line 2165 of file model_domain.F90.
References direct_recharge__gridded_data::direct_recharge_calculate().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_direct_soil_moisture_none (class (model_domain_t), intent(inout) this)
Definition at line 2181 of file model_domain.F90.
subroutine model_domain::model_calculate_direct_soil_moisture_none (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx) private
Definition at line 2189 of file model_domain.F90.
subroutine model_domain::model_initialize_direct_soil_moisture_gridded (class (model_domain_t), intent(inout) this) private
Definition at line 2198 of file model_domain.F90.
References direct_soil_moisture__gridded_data::direct_soil_moisture_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_direct_soil_moisture_gridded (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx)
Definition at line 2211 of file model_domain.F90.
References direct_soil_moisture__gridded_data::direct_soil_moisture_calculate().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_maximum_potential_recharge_none (class (model_domain_t), intent(inout) this)
Definition at line 2226 of file model_domain.F90.
subroutine model_domain::model_calculate_maximum_potential_recharge_none (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx) private
Definition at line 2234 of file model_domain.F90.
subroutine model_domain::model_initialize_maximum_potential_recharge_gridded (class (model_domain_t), intent(inout) this) private
Definition at line 2243 of file model_domain.F90.
References maximum_potential_recharge__gridded_data::maximum_potential_recharge_initialize().
subroutine model_domain::model_calculate_maximum_potential_recharge_gridded (class (model_domain_t), intent(inout) this, integer (kind=c_int), intent(in) indx)
Definition at line 2256 of file model_domain.F90.
References maximum_potential_recharge__gridded_data::maximum_potential_recharge_calculate().
subroutine model_domain::model_initialize_crop_coefficient_none (class (model_domain_t), intent(inout) this)
Definition at line 2271 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_update_crop_coefficient_none (class (model_domain_t), intent(inout) this) private
Definition at line 2279 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_crop_coefficient_fao56 (class (model_domain_t), intent(inout) this) private
Definition at line 2289 of file model_domain.F90.
References crop_coefficients__fao56::crop_coefficients_fao56_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_update_crop_coefficient_fao56 (class (model_domain_t), intent(inout) this)
Definition at line 2305 of file model_domain.F90.
References crop_coefficients__fao56::crop_coefficients_fao56_calculate(), crop_coefficients__fao56::crop_coefficients_fao56_update_growth_stage_dates(), and crop_coefficients__fao56::growth_stage_date.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_fog_none (class (model_domain_t), intent(inout) this)
Nothing here to see. Initialization not really needed for the "normal" method.
Definition at line 2326 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_fog_monthly_grid (class (model_domain_t), intent(inout) this) private
Definition at line 2337 of file model_domain.F90.
References fog__monthly_grid::fog_monthly_grid_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_precip_normal (class (model_domain_t), intent(inout) this)
Nothing here to see. Initialization not really needed for the "normal" method.
Definition at line 2350 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_fog_none (class (model_domain_t), intent(inout) this) private
Definition at line 2360 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_fog_monthly_grid (class (model_domain_t), intent(inout) this) private
Definition at line 2368 of file model_domain.F90.
References fog__monthly_grid::fog_monthly_grid_calculate().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_calculate_mean_air_temperature (class (model_domain_t), intent(inout) this)
Definition at line 2382 of file model_domain.F90.
subroutine model_domain::model_get_maximum_air_temperature_normal (class (model_domain_t), intent(inout) this) private
Definition at line 2392 of file model_domain.F90.
subroutine model_domain::model_get_minimum_air_temperature_normal (class (model_domain_t), intent(inout) this) private
Definition at line 2428 of file model_domain.F90.
subroutine model_domain::model_get_precip_normal (class (model_domain_t), intent(inout) this) private
Definition at line 2464 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::model_initialize_precip_method_of_fragments (class (model_domain_t), intent(inout) this) private
Definition at line 2500 of file model_domain.F90.
References precipitation__method_of_fragments::precipitation_method_of_fragments_initialize().
Referenced by set_method_pointers_sub().
subroutine model_domain::model_get_precip_method_of_fragments (class (model_domain_t), intent(inout) this)
Definition at line 2519 of file model_domain.F90.
Referenced by set_method_pointers_sub().
subroutine model_domain::minmaxmean_float (real (kind=c_float), dimension(:) variable, character (len=*), intent(in) varname, logical, dimension(:), optional active_cells)
Definition at line 2587 of file model_domain.F90.
subroutine model_domain::minmaxmean_int (integer (kind=c_int), dimension(:) variable, character (len=*), intent(in) varname, logical, dimension(:), optional active_cells) private
Definition at line 2640 of file model_domain.F90.
subroutine model_domain::summarize_state_variables_sub (class (model_domain_t), intent(inout) this) private
Definition at line 2691 of file model_domain.F90.
Variable Documentation
type (cell_col_row_t), dimension(5) model_domain::dump private
Definition at line 262 of file model_domain.F90.
Referenced by model_dump_variables_by_cell(), and set_method_pointers_sub().
type (model_domain_t), public model_domain::model
Definition at line 288 of file model_domain.F90.
Referenced by model_initialize::initialize_all(), model_initialize::initialize_ancillary_values(), model_initialize::initialize_generic_method(), model_initialize::initialize_grid_options(), model_initialize::initialize_hydrologic_soil_groups(), model_initialize::initialize_landuse_codes(), model_initialize::initialize_latitude(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), model_initialize::initialize_snow_storage(), model_initialize::initialize_soil_storage(), model_initialize::initialize_surface_storage_max(), main(), model_initialize_soil_storage_max_internally_calculated(), and model_initialize::read_polygon_id().
real (kind=c_float), dimension(:,:), allocatable, public model_domain::rooting_depth_max
Definition at line 290 of file model_domain.F90.
Referenced by model_initialize::create_rooting_depth_table(), model_initialize::initialize_soils_landuse_awc_flowdir_values(), model_initialize_soil_storage_max_internally_calculated(), and model_read_available_water_content_depth_integrated().
type (general_grid_t), pointer model_domain::prooting_depth private
Definition at line 292 of file model_domain.F90.