SWB 2.0: constants_and_conversions Module Reference
constants_and_conversions Module Reference
This module contains physical constants and convenience functions aimed at performing unit conversions.
Data Types
interface asdouble
interface asfloat
interface asint
interface aslogical
type bounds_t
interface c_to_f
establish generic interfaces to single and double precision functions
interface c_to_k
interface deg_to_rad
interface f_to_c
interface f_to_k
interface in_to_mm
interface mm_to_in
interface operator(.approxequal.)
interface rad_to_deg
Functions/Subroutines
elemental logical(kind=c_bool) function approx_equal_float_float (fValue1, fValue2)
elemental logical(kind=c_bool) function approx_equal_float_double (fValue1, fValue2)
elemental logical(kind=c_bool) function approx_equal_double_double (fValue1, fValue2)
logical(kind=c_bool) elemental function, public is_numeric (value)
Determine if string contains numeric values.
elemental real(kind=c_float) function deg_to_rad_sgl_fn (degrees)
Convert degrees to radians.
elemental real(kind=c_double) function deg_to_rad_dbl_fn (degrees)
Convert degrees to radians.
elemental real(kind=c_float) function rad_to_deg_sgl_fn (radians)
Convert radians to degrees.
elemental real(kind=c_double) function rad_to_deg_dbl_fn (radians)
Convert radians to degrees.
elemental real(kind=c_float) function ftoc_sgl_fn (degrees_F)
Convert degrees Fahrenheit to degrees Celsius.
elemental real(kind=c_double) function ftoc_dbl_fn (degrees_F)
Convert degrees Fahrenheit to degrees Celsius.
elemental real(kind=c_float) function ctof_sgl_fn (degrees_C)
Convert degrees Celsius to degrees Fahrenheit.
elemental real(kind=c_double) function ctof_dbl_fn (degrees_C)
Convert degrees Celsius to degrees Fahrenheit.
elemental real(kind=c_float) function ftok_sgl_fn (degrees_F)
Convert degrees Fahrenheit to Kelvins.
elemental real(kind=c_double) function ftok_dbl_fn (degrees_F)
Convert degrees Fahrenheit to Kelvins.
elemental real(kind=c_float) function ctok_sgl_fn (degrees_C)
Convert degrees Celsius to Kelvins.
elemental real(kind=c_double) function ctok_dbl_fn (degrees_C)
Convert degrees Fahrenheit to Kelvins.
elemental real(kind=c_float) function inches_to_mm_sgl_fn (inches)
Convert inches to mm.
elemental real(kind=c_double) function inches_to_mm_dbl_fn (inches)
Convert inches to mm.
elemental real(kind=c_float) function mm_to_inches_sgl_fn (mm)
Convert millimeters to inches.
elemental real(kind=c_double) function mm_to_inches_dbl_fn (mm)
Convert millimeters to inches.
elemental logical(kind=c_bool) function short2logical (iShortVal)
Convert a short integer to a logical value.
elemental logical(kind=c_bool) function int2logical (iValue)
Convert an integer to a logical value.
elemental logical(kind=c_bool) function real2logical (rValue)
Convert a real to a logical value.
elemental logical(kind=c_bool) function dbl2logical (rValue)
Convert a double to a logical value.
elemental logical(kind=c_bool) function char2logical (sValue)
Convert a character string to a logical value.
elemental integer(kind=c_int) function short2int (iShortVal)
Convert a short integer to an integer.
elemental integer(kind=c_int) function char2int (sValue)
Convert a character value into a integer.
elemental integer(kind=c_int) function real2int (rValue)
Convert a real value into a integer.
elemental integer(kind=c_int) function dbl2int (rValue)
Convert a double-precision value to an integer.
elemental real(kind=c_float) function char2real (sValue)
Convert a character value into a real.
elemental real(kind=c_float) function short2real (iValue)
Convert a short int value into a real.
elemental real(kind=c_float) function int2real (iValue)
Convert an int value into a real.
elemental real(kind=c_float) function dbl2real (dpValue)
Convert a dbl value into a real.
elemental real(kind=c_double) function char2dbl (sValue)
Convert a character value into a double.
elemental real(kind=c_double) function short2dbl (iValue)
Convert a short int value into a double.
elemental real(kind=c_double) function int2dbl (iValue)
Convert an int value into a double.
elemental real(kind=c_double) function real2dbl (fValue)
Convert a real value into a double.
character(len=256) function, public char_ptr_to_fortran_string (cpCharacterPtr)
elemental character(len=len(ccharacterstring)-1) function, public c_to_fortran_string (cCharacterString)
elemental character(len=256) function, public fortran_to_c_string (sText)
elemental character(len=:) function, allocatable keepnumeric (sText1)
Strip everything except numeric characters from a text string.
Variables
integer(kind=c_int), parameter datatype_int = 0
integer(kind=c_int), parameter datatype_float = 1
integer(kind=c_int), parameter datatype_real = 1
integer(kind=c_int), parameter datatype_short = 2
integer(kind=c_int), parameter datatype_double = 3
integer(kind=c_int), parameter datatype_na = -9999
real(kind=c_double), parameter, public pi = 3.1415926535897932384626433_c_double
real(kind=c_double), parameter, public twopi = 3.1415926535897932384626433_c_double * 2.0_c_double
real(kind=c_double), parameter, public halfpi = 3.1415926535897932384626433_c_double / 2.0_c_double
real(kind=c_double), parameter, public degrees_to_radians = TWOPI / 360.0_c_double
real(kind=c_double), parameter, public radians_to_degrees = 360.0_c_double / TWOPI
logical(kind=c_bool), parameter, public ltrue = .true._c_bool
logical(kind=c_bool), parameter, public lfalse = .false._c_bool
logical(kind=c_bool), parameter true = .true._c_bool
logical(kind=c_bool), parameter false = .false._c_bool
real(kind=c_float), parameter, public rbigval = HUGE(0.0_c_float)
real(kind=c_double), parameter, public dbigval = HUGE(0.0_c_double)
integer(kind=c_int), parameter, public ibigval = HUGE(0_c_int)
real(kind=c_float), parameter, public rtinyval = -(HUGE(0.0_c_float) - 1.0)
real(kind=c_double), parameter, public dtinyval = -(HUGE(0.0_c_double) - 1.0)
real(kind=c_float), parameter ftinyval = -(HUGE(0.0_c_float) - 1.0)
integer(kind=c_int), parameter, public itinyval = -(HUGE(0_c_int) - 1)
real(kind=c_float), parameter, public rfreezing = 32.0_c_float
real(kind=c_float), parameter ffreezing = 32.0_c_float
real(kind=c_double), parameter, public dfreezing = 32.0_c_double
integer(kind=c_int), parameter izero = 0_c_int
real(kind=c_float), parameter fzero = 0.0_c_float
real(kind=c_float), parameter, public rzero = 0.0_c_float
real(kind=c_double), parameter dzero = 0.0_c_double
character(len=1), parameter, public stab = achar(9)
character(len=2), parameter, public swhitespace = achar(9)//" "
character(len=1), parameter, public sbackslash = achar(92)
character(len=1), parameter, public sforwardslash = achar(47)
character(len=1), parameter, public sreturn = achar(13)
character(len=3), parameter, public scomment_chars = "#!%"
character(len=1), parameter sdouble_quote = achar(34)
real(kind=c_double), parameter c_per_f = 5.0_c_double / 9.0_c_double
real(kind=c_double), parameter f_per_c = 9.0_c_double / 5.0_c_double
real(kind=c_double), parameter m_per_foot = 0.3048_c_double
character(len=:), allocatable output_directory_name
character(len=:), allocatable output_prefix_name
character(len=:), allocatable data_directory_name
type(bounds_t), public bnds
real(kind=c_float), parameter tolerance_float = 1.0e-6_c_float
real(kind=c_double), parameter tolerance_double = 1.0e-9_c_double
Detailed Description
The functions included in this module perform conversions between various temperature and distance units.
Function/Subroutine Documentation
elemental logical (kind=c_bool) function constants_and_conversions::approx_equal_float_float (real (kind=c_float), intent(in) fValue1, real (kind=c_float), intent(in) fValue2)
Definition at line 192 of file constants_and_conversions.F90.
References lfalse, ltrue, and tolerance_float.
elemental logical (kind=c_bool) function constants_and_conversions::approx_equal_float_double (real (kind=c_float), intent(in) fValue1, real (kind=c_double), intent(in) fValue2)
Definition at line 209 of file constants_and_conversions.F90.
References lfalse, and ltrue.
elemental logical (kind=c_bool) function constants_and_conversions::approx_equal_double_double (real (kind=c_double), intent(in) fValue1, real (kind=c_double), intent(in) fValue2)
Definition at line 227 of file constants_and_conversions.F90.
References lfalse, ltrue, and tolerance_double.
logical (kind=c_bool) elemental function, public constants_and_conversions::is_numeric (character (len=*), intent(in) value)
Parameters
[in] degrees String value.
Return values
is_numeric True if any numeric values are present in the string.
Definition at line 247 of file constants_and_conversions.F90.
References keepnumeric(), lfalse, and ltrue.
elemental real (kind=c_float) function constants_and_conversions::deg_to_rad_sgl_fn (real (kind=c_float), intent(in) degrees)
Parameters
[in] degrees Angle in degrees.
Return values
radians Angle in radians.
Definition at line 270 of file constants_and_conversions.F90.
References degrees_to_radians.
elemental real (kind=c_double) function constants_and_conversions::deg_to_rad_dbl_fn (real (kind=c_double), intent(in) degrees)
Parameters
[in] degrees Angle in degrees.
Return values
radians Angle in radians.
Definition at line 286 of file constants_and_conversions.F90.
References degrees_to_radians.
elemental real (kind=c_float) function constants_and_conversions::rad_to_deg_sgl_fn (real (kind=c_float), intent(in) radians)
Parameters
[in] radians Angle in radians.
Return values
degrees Angle in degrees.
Definition at line 302 of file constants_and_conversions.F90.
References radians_to_degrees.
elemental real (kind=c_double) function constants_and_conversions::rad_to_deg_dbl_fn (real (kind=c_double), intent(in) radians)
Parameters
[in] radians Angle in radians.
Return values
degrees Angle in degrees.
Definition at line 317 of file constants_and_conversions.F90.
References radians_to_degrees.
elemental real (kind=c_float) function constants_and_conversions::ftoc_sgl_fn (real (kind=c_float), intent(in) degrees_F)
Parameters
[in] degrees_F Temperature in degrees Fahrenheit.
Return values
degrees_C Temperature in degrees Celcius.
Definition at line 333 of file constants_and_conversions.F90.
References c_per_f, and rfreezing.
elemental real (kind=c_double) function constants_and_conversions::ftoc_dbl_fn (real (kind=c_double), intent(in) degrees_F)
Parameters
[in] degrees_F Temperature in degrees Fahrenheit.
Return values
degrees_C Temperature in degrees Celcius.
Definition at line 349 of file constants_and_conversions.F90.
References c_per_f, and dfreezing.
elemental real (kind=c_float) function constants_and_conversions::ctof_sgl_fn (real (kind=c_float), intent(in) degrees_C)
Parameters
[in] degrees_C Temperature in degrees Celsius.
Return values
degrees_F Temperature in degrees Fahrenheit.
Definition at line 365 of file constants_and_conversions.F90.
References dfreezing, and f_per_c.
elemental real (kind=c_double) function constants_and_conversions::ctof_dbl_fn (real (kind=c_double), intent(in) degrees_C)
Parameters
[in] degrees_C Temperature in degrees Celsius.
Return values
degrees_F Temperature in degree
Definition at line 381 of file constants_and_conversions.F90.
References dfreezing, and f_per_c.
elemental real (kind=c_float) function constants_and_conversions::ftok_sgl_fn (real (kind=c_float), intent(in) degrees_F)
Parameters
[in] degrees_F Temperature in degrees Fahrenheit.
Return values
degrees_K Temperature in Kelvins.
Definition at line 397 of file constants_and_conversions.F90.
References c_per_f, and dfreezing.
elemental real (kind=c_double) function constants_and_conversions::ftok_dbl_fn (real (kind=c_double), intent(in) degrees_F)
Parameters
[in] degrees_F Temperature in degrees Fahrenheit.
Return values
degrees_K Temperature in Kelvins.
Definition at line 413 of file constants_and_conversions.F90.
References c_per_f, and dfreezing.
elemental real (kind=c_float) function constants_and_conversions::ctok_sgl_fn (real (kind=c_float), intent(in) degrees_C)
Parameters
[in] degrees_C Temperature in degrees Celcius.
Return values
degrees_K Temperature in Kelvins.
Definition at line 429 of file constants_and_conversions.F90.
elemental real (kind=c_double) function constants_and_conversions::ctok_dbl_fn (real (kind=c_double), intent(in) degrees_C)
Parameters
[in] degrees_C Temperature in degrees Celsius.
Return values
degrees_K Temperature in Kelvins.
Definition at line 445 of file constants_and_conversions.F90.
elemental real (kind=c_float) function constants_and_conversions::inches_to_mm_sgl_fn (real (kind=c_float), intent(in) inches)
Parameters
[in] inches Value in inches.
Return values
mm Value in millimeters.
Definition at line 460 of file constants_and_conversions.F90.
elemental real (kind=c_double) function constants_and_conversions::inches_to_mm_dbl_fn (real (kind=c_double), intent(in) inches)
Parameters
[in] inches Value in inches.
Return values
mm Value in millimeters.
Definition at line 475 of file constants_and_conversions.F90.
elemental real (kind=c_float) function constants_and_conversions::mm_to_inches_sgl_fn (real (kind=c_float), intent(in) mm)
Parameters
[in] mm Value in millimeters.
Return values
inches Value in inches.
Definition at line 490 of file constants_and_conversions.F90.
elemental real (kind=c_double) function constants_and_conversions::mm_to_inches_dbl_fn (real (kind=c_double), intent(in) mm)
Parameters
[in] mm Value in millimeters.
Return values
inches Value in inches.
Definition at line 505 of file constants_and_conversions.F90.
elemental logical (kind=c_bool) function constants_and_conversions::short2logical (integer (kind=c_short), intent(in) iShortVal)
Definition at line 518 of file constants_and_conversions.F90.
References lfalse, and ltrue.
elemental logical (kind=c_bool) function constants_and_conversions::int2logical (integer (kind=c_int), intent(in) iValue)
Definition at line 535 of file constants_and_conversions.F90.
References lfalse, and ltrue.
elemental logical (kind=c_bool) function constants_and_conversions::real2logical (real (kind=c_float), intent(in) rValue)
Definition at line 552 of file constants_and_conversions.F90.
References lfalse, and ltrue.
elemental logical (kind=c_bool) function constants_and_conversions::dbl2logical (real (kind=c_double), intent(in) rValue)
Definition at line 572 of file constants_and_conversions.F90.
References lfalse, and ltrue.
elemental logical (kind=c_bool) function constants_and_conversions::char2logical (character (len=*), intent(in) sValue)
Definition at line 592 of file constants_and_conversions.F90.
References lfalse, and ltrue.
elemental integer (kind=c_int) function constants_and_conversions::short2int (integer (kind=c_short), intent(in) iShortVal)
Definition at line 615 of file constants_and_conversions.F90.
elemental integer (kind=c_int) function constants_and_conversions::char2int (character (len=*), intent(in) sValue)
Definition at line 628 of file constants_and_conversions.F90.
References itinyval, and keepnumeric().
elemental integer (kind=c_int) function constants_and_conversions::real2int (real (kind=c_float), intent(in) rValue)
Definition at line 662 of file constants_and_conversions.F90.
elemental integer (kind=c_int) function constants_and_conversions::dbl2int (real (kind=c_double), intent(in) rValue)
Definition at line 675 of file constants_and_conversions.F90.
elemental real (kind=c_float) function constants_and_conversions::char2real (character (len=*), intent(in) sValue)
Definition at line 688 of file constants_and_conversions.F90.
References rtinyval.
elemental real (kind=c_float) function constants_and_conversions::short2real (integer (kind=c_short), intent(in) iValue)
Definition at line 706 of file constants_and_conversions.F90.
elemental real (kind=c_float) function constants_and_conversions::int2real (integer (kind=c_int), intent(in) iValue)
Definition at line 719 of file constants_and_conversions.F90.
elemental real (kind=c_float) function constants_and_conversions::dbl2real (real (kind=c_double), intent(in) dpValue)
Definition at line 732 of file constants_and_conversions.F90.
elemental real (kind=c_double) function constants_and_conversions::char2dbl (character (len=*), intent(in) sValue)
Definition at line 745 of file constants_and_conversions.F90.
References dtinyval.
elemental real (kind=c_double) function constants_and_conversions::short2dbl (integer (kind=c_short), intent(in) iValue)
Definition at line 763 of file constants_and_conversions.F90.
elemental real (kind=c_double) function constants_and_conversions::int2dbl (integer (kind=c_int), intent(in) iValue)
Definition at line 776 of file constants_and_conversions.F90.
elemental real (kind=c_double) function constants_and_conversions::real2dbl (real (kind=c_float), intent(in) fValue)
Definition at line 789 of file constants_and_conversions.F90.
character(len=256) function, public constants_and_conversions::char_ptr_to_fortran_string (type(c_ptr) cpCharacterPtr)
Definition at line 800 of file constants_and_conversions.F90.
Referenced by netcdf4_support::nf_trap().
elemental character(len=len(ccharacterstring) - 1) function, public constants_and_conversions::c_to_fortran_string (character (len=*), intent(in) cCharacterString)
Definition at line 825 of file constants_and_conversions.F90.
Referenced by file_utilities::get_cwd(), file_utilities::getcwd(), netcdf4_support::nf_populate_attribute_struct(), netcdf4_support::nf_populate_dimension_struct(), and netcdf4_support::nf_populate_variable_struct().
elemental character(len=256) function, public constants_and_conversions::fortran_to_c_string (character (len=*), intent(in) sText)
Definition at line 852 of file constants_and_conversions.F90.
Referenced by netcdf4_support::nf_create().
elemental character (len=:) function, allocatable constants_and_conversions::keepnumeric (character (len=*), intent(in) sText1)
Keep only the numeric characters in a text string.
Parameters
[in] sTextIn
Definition at line 875 of file constants_and_conversions.F90.
References sdouble_quote.
Referenced by char2int(), and is_numeric().
Variable Documentation
integer (kind=c_int), parameter constants_and_conversions::datatype_int = 0
Definition at line 14 of file constants_and_conversions.F90.
Referenced by data_catalog_entry::getvalues_constant_sub(), data_catalog_entry::getvalues_sub(), grid::grid_readarcgrid_fn(), grid::grid_readarcgrid_sub(), grid::grid_readsurfergrid_fn(), grid::grid_readsurfergrid_sub(), grid::grid_writearcgrid(), grid::grid_writesurfergrid(), data_catalog_entry::initialize_constant_int_data_object_sub(), model_initialize::initialize_generic_grid(), data_catalog_entry::initialize_gridded_data_object_sub(), and routing__d8::routing_d8_initialize().
integer (kind=c_int), parameter constants_and_conversions::datatype_float = 1
Definition at line 15 of file constants_and_conversions.F90.
Referenced by model_initialize::initialize_generic_grid().
integer (kind=c_int), parameter constants_and_conversions::datatype_real = 1
Definition at line 16 of file constants_and_conversions.F90.
Referenced by data_catalog_entry::getvalues_constant_sub(), data_catalog_entry::getvalues_sub(), grid::grid_readarcgrid_fn(), grid::grid_readarcgrid_sub(), grid::grid_readsurfergrid_fn(), grid::grid_readsurfergrid_sub(), grid::grid_writearcgrid(), grid::grid_writesurfergrid(), data_catalog_entry::initialize_constant_real_data_object_sub(), and data_catalog_entry::initialize_gridded_data_object_sub().
integer (kind=c_int), parameter constants_and_conversions::datatype_short = 2
Definition at line 17 of file constants_and_conversions.F90.
integer (kind=c_int), parameter constants_and_conversions::datatype_double = 3
Definition at line 18 of file constants_and_conversions.F90.
integer (kind=c_int), parameter constants_and_conversions::datatype_na = -9999
Definition at line 19 of file constants_and_conversions.F90.
real (kind=c_double), parameter, public constants_and_conversions::pi = 3.1415926535897932384626433_c_double
Definition at line 23 of file constants_and_conversions.F90.
Referenced by solar_calculations::daylight_hours(), and solar_calculations::extraterrestrial_radiation__ra().
real (kind=c_double), parameter, public constants_and_conversions::twopi = 3.1415926535897932384626433_c_double * 2.0_c_double
Definition at line 24 of file constants_and_conversions.F90.
Referenced by solar_calculations::day_angle__gamma(), solar_calculations::relative_earth_sun_distance__d_r(), and solar_calculations::solar_declination_simple__delta().
real (kind=c_double), parameter, public constants_and_conversions::halfpi = 3.1415926535897932384626433_c_double / 2.0_c_double
Definition at line 25 of file constants_and_conversions.F90.
Referenced by solar_calculations::solar_altitude__alpha(), and solar_calculations::zenith_angle__theta_z().
real (kind=c_double), parameter, public constants_and_conversions::degrees_to_radians = TWOPI / 360.0_c_double
Definition at line 29 of file constants_and_conversions.F90.
Referenced by deg_to_rad_dbl_fn(), deg_to_rad_sgl_fn(), et__hargreaves_samani::et_hargreaves_calculate(), and grid::grid_transform().
real (kind=c_double), parameter, public constants_and_conversions::radians_to_degrees = 360.0_c_double / TWOPI
Definition at line 30 of file constants_and_conversions.F90.
Referenced by grid::grid_transform(), rad_to_deg_dbl_fn(), and rad_to_deg_sgl_fn().
logical (kind=c_bool), parameter, public constants_and_conversions::ltrue = .true._c_bool
Definition at line 37 of file constants_and_conversions.F90.
Referenced by approx_equal_double_double(), approx_equal_float_double(), approx_equal_float_float(), awc__depth_integrated::awc_depth_integrated_read(), char2logical(), dbl2logical(), fog__monthly_grid::fog_monthly_grid_initialize(), data_catalog_entry::getvalues_constant_sub(), data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_gridded_sub(), grid::grid_checkforproj4error(), grid::grid_completelycover(), grid::grid_conform(), grid::grid_getgridcolrownum(), grid::grid_gridtogrid_int(), grid::grid_majorityfilter_int(), grid::grid_readarcgrid_fn(), grid::grid_readarcgrid_sub(), grid::grid_set_output_directory_name(), actual_et__fao56::initialize_actual_et_fao56(), continuous_frozen_ground_index::initialize_continuous_frozen_ground_index(), model_initialize::initialize_generic_grid(), model_initialize::initialize_generic_method(), model_initialize::initialize_grid_options(), data_catalog_entry::initialize_gridded_data_object_sub(), model_initialize::initialize_landuse_codes(), data_catalog_entry::initialize_netcdf_data_object_sub(), model_initialize::initialize_parameter_tables(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), model_initialize::initialize_snow_storage(), model_initialize::initialize_soil_storage(), model_initialize::initialize_start_and_end_dates(), int2logical(), strings::is_char_equal_to_char_fn(), file_operations::is_current_line_a_comment_fn(), datetime::is_date_equal_to(), datetime::is_date_greater_than(), datetime::is_date_gt_or_equal_to(), datetime::is_date_less_than(), datetime::is_date_lt_or_equal_to(), is_numeric(), strings::is_string2_present_in_string1_fn(), string_list::list_is_string_in_list_fn(), data_catalog_entry::make_filename_from_template(), netcdf4_support::netcdf_date_within_range(), netcdf4_support::netcdf_open_and_prepare_as_output(), netcdf4_support::netcdf_update_time_starting_index(), netcdf4_support::nf_get_scale_and_offset(), netcdf4_support::nf_get_time_units(), netcdf4_support::nf_get_x_and_y(), netcdf4_support::nf_get_xyz_units(), netcdf4_support::nf_julian_day_to_index_adj(), netcdf4_support::nf_return_attvalue(), netcdf4_support::nf_return_dimindex(), netcdf4_support::nf_return_dimsize(), netcdf4_support::nf_return_index_double(), netcdf4_support::nf_return_varindex(), file_operations::open_file_read_access_sub(), file_operations::open_file_write_access_sub(), precipitation__method_of_fragments::precipitation_method_of_fragments_calculate(), model_initialize::read_hydrologic_soil_groups(), model_initialize::read_landuse_codes(), file_operations::read_line_of_data_fn(), model_initialize::read_polygon_id(), real2logical(), strings::remove_repeats(), runoff__gridded_values::runoff_gridded_values_update_ratios(), datetime::set_date_format_indices(), data_catalog_entry::set_grid_flip_horizontal_sub(), data_catalog_entry::set_grid_flip_vertical_sub(), datetime::set_time_format_indices(), short2logical(), and data_catalog_entry::test_for_need_to_pad_values_fn().
logical (kind=c_bool), parameter, public constants_and_conversions::lfalse = .false._c_bool
Definition at line 38 of file constants_and_conversions.F90.
Referenced by approx_equal_double_double(), approx_equal_float_double(), approx_equal_float_float(), awc__depth_integrated::awc_depth_integrated_read(), char2logical(), file_operations::close_file_sub(), model_initialize::create_rooting_depth_table(), data_catalog_entry::data_gridhandlemissingdata_int(), data_catalog_entry::data_gridhandlemissingdata_real(), dbl2logical(), dictionary::get_entry_by_index_fn(), dictionary::get_entry_by_key_fn(), dictionary::get_next_entry_by_key_fn(), dictionary::get_next_entry_fn(), parameters::get_parameter_table_float(), parameters::get_parameter_values_float(), parameters::get_parameter_values_int(), parameters::get_parameter_values_logical(), parameters::get_parameter_values_string_list(), data_catalog_entry::get_source_filetype_fn(), dictionary::get_values_as_float_given_list_of_keys_sub(), dictionary::get_values_as_float_sub(), dictionary::get_values_as_int_given_list_of_keys_sub(), dictionary::get_values_as_int_sub(), dictionary::get_values_as_logical_given_list_of_keys_sub(), dictionary::get_values_as_logical_sub(), dictionary::get_values_as_string_list_given_list_of_keys_sub(), dictionary::get_values_as_string_list_sub(), data_catalog_entry::getvalues_constant_sub(), data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_gridded_sub(), data_catalog_entry::getvalues_static_netcdf_sub(), data_catalog_entry::getvalues_sub(), dictionary::grep_dictionary_key_names_fn(), parameters::grep_parameter_name(), grid::grid_checkforproj4error(), grid::grid_completelycover(), grid::grid_conform(), grid::grid_createcomplete(), grid::grid_createsimple(), grid::grid_destroy(), grid::grid_getgridcolrownum(), grid::grid_majorityfilter_int(), grid::grid_read(), grid::grid_readarcgrid_fn(), grid::grid_readarcgrid_sub(), grid::grid_readexisting(), grid::grid_readsurfergrid_fn(), grid::grid_readsurfergrid_sub(), grid::grid_writearcgrid(), grid::grid_writesurfergrid(), model_domain::initialize_arrays_sub(), continuous_frozen_ground_index::initialize_continuous_frozen_ground_index(), model_initialize::initialize_generic_grid(), model_initialize::initialize_generic_method(), data_catalog_entry::initialize_gridded_data_object_sub(), model_initialize::initialize_landuse_codes(), model_initialize::initialize_parameter_tables(), model_initialize::initialize_program_options(), model_initialize::initialize_snow_storage(), model_initialize::initialize_start_and_end_dates(), int2logical(), strings::is_char_equal_to_char_fn(), file_operations::is_current_line_a_comment_fn(), datetime::is_date_equal_to(), datetime::is_date_greater_than(), datetime::is_date_gt_or_equal_to(), datetime::is_date_less_than(), datetime::is_date_lt_or_equal_to(), is_numeric(), strings::is_string2_present_in_string1_fn(), datetime::julian_day(), string_list::list_is_string_in_list_fn(), data_catalog_entry::make_filename_from_template(), maximum_potential_recharge__gridded_data::maximum_potential_recharge_initialize(), netcdf4_support::netcdf_date_within_range(), netcdf4_support::netcdf_open_and_prepare_as_output(), netcdf4_support::netcdf_update_time_starting_index(), netcdf4_support::nf_get_scale_and_offset(), netcdf4_support::nf_get_time_units(), netcdf4_support::nf_get_x_and_y(), netcdf4_support::nf_get_xyz_units(), netcdf4_support::nf_julian_day_to_index_adj(), netcdf4_support::nf_return_attvalue(), netcdf4_support::nf_return_dimindex(), netcdf4_support::nf_return_dimsize(), netcdf4_support::nf_return_index_double(), netcdf4_support::nf_return_varindex(), netcdf4_support::nf_set_standard_variables(), netcdf4_support::nf_trap(), file_operations::open_file_read_access_sub(), file_operations::open_file_write_access_sub(), datetime::parse_text_to_date_sub(), precipitation__method_of_fragments::precipitation_method_of_fragments_calculate(), dictionary::print_all_dictionary_entries_sub(), precipitation__method_of_fragments::process_fragment_sets(), precipitation__method_of_fragments::read_fragments_sequence(), real2logical(), strings::remove_repeats(), runoff__gridded_values::runoff_gridded_values_update_ratios(), short2logical(), data_catalog_entry::test_for_need_to_pad_values_fn(), data_catalog_entry::transform_grid_to_grid_sub(), and precipitation__method_of_fragments::update_fragments().
logical (kind=c_bool), parameter constants_and_conversions::true = .true._c_bool
Definition at line 40 of file constants_and_conversions.F90.
Referenced by model_initialize::create_rooting_depth_table(), direct_recharge__gridded_data::direct_recharge_initialize(), direct_soil_moisture__gridded_data::direct_soil_moisture_initialize(), fog__monthly_grid::fog_monthly_grid_initialize(), growing_season::growing_season_initialize(), growing_season::growing_season_update(), model_initialize::initialize_landuse_codes(), interception__bucket::interception_bucket_initialize(), interception__gash::interception_gash_initialize(), netcdf4_support::netcdf_get_attribute_list_for_variable(), netcdf4_support::netcdf_get_variable_id_for_variable(), netcdf4_support::nf_get_variable_id_and_type(), strings::return_right_part_of_string_fn(), model_domain::row_column_to_index_fn(), runoff__curve_number::runoff_curve_number_initialize(), and model_domain::set_inactive_cells_sub().
logical (kind=c_bool), parameter constants_and_conversions::false = .false._c_bool
Definition at line 41 of file constants_and_conversions.F90.
Referenced by growing_season::growing_season_initialize(), growing_season::growing_season_update(), model_initialize::initialize_surface_storage_max(), interception__bucket::interception_bucket_initialize(), string_list::list_return_all_as_character_fn(), maximum_potential_recharge__gridded_data::maximum_potential_recharge_initialize(), netcdf4_support::netcdf_get_attribute_list_for_variable(), netcdf4_support::netcdf_get_variable_id_for_variable(), netcdf4_support::netcdf_open_and_prepare_as_output(), netcdf4_support::netcdf_open_and_prepare_for_merging(), model_initialize::read_control_file(), runoff__gridded_values::read_runoff_ratio_table(), model_domain::row_column_to_index_fn(), model_domain::set_inactive_cells_sub(), and storm_drain_capture::storm_drain_capture_initialize().
real (kind=c_float), parameter, public constants_and_conversions::rbigval = HUGE(0.0_c_float)
Definition at line 43 of file constants_and_conversions.F90.
Referenced by grid::grid_getgridcolrownum().
real (kind=c_double), parameter, public constants_and_conversions::dbigval = HUGE(0.0_c_double)
Definition at line 44 of file constants_and_conversions.F90.
integer(kind=c_int), parameter, public constants_and_conversions::ibigval = HUGE(0_c_int)
Definition at line 45 of file constants_and_conversions.F90.
Referenced by netcdf4_support::nf_julian_day_to_index_adj().
real (kind=c_float), parameter, public constants_and_conversions::rtinyval = -(HUGE(0.0_c_float) - 1.0)
Definition at line 46 of file constants_and_conversions.F90.
Referenced by char2real().
real (kind=c_double), parameter, public constants_and_conversions::dtinyval = -(HUGE(0.0_c_double) - 1.0)
Definition at line 47 of file constants_and_conversions.F90.
Referenced by char2dbl().
real (kind=c_float), parameter constants_and_conversions::ftinyval = -(HUGE(0.0_c_float) - 1.0)
Definition at line 48 of file constants_and_conversions.F90.
Referenced by direct_recharge__gridded_data::direct_recharge_initialize(), direct_soil_moisture__gridded_data::direct_soil_moisture_initialize(), fog__monthly_grid::fog_monthly_grid_initialize(), parameters::get_parameter_values_float(), dictionary::get_values_as_float_given_list_of_keys_sub(), dictionary::get_values_as_float_sub(), and interception__bucket::interception_bucket_initialize().
integer(kind=c_int), parameter, public constants_and_conversions::itinyval = -(HUGE(0_c_int) - 1)
Definition at line 49 of file constants_and_conversions.F90.
Referenced by char2int(), parameters::get_parameter_values_int(), dictionary::get_values_as_int_given_list_of_keys_sub(), and dictionary::get_values_as_int_sub().
real (kind=c_float), parameter, public constants_and_conversions::rfreezing = 32.0_c_float
Definition at line 50 of file constants_and_conversions.F90.
Referenced by et__jensen_haise::et_jh_calculate(), and ftoc_sgl_fn().
real (kind=c_float), parameter constants_and_conversions::ffreezing = 32.0_c_float
Definition at line 51 of file constants_and_conversions.F90.
real (kind=c_double), parameter, public constants_and_conversions::dfreezing = 32.0_c_double
Definition at line 52 of file constants_and_conversions.F90.
Referenced by ctof_dbl_fn(), ctof_sgl_fn(), ftoc_dbl_fn(), ftok_dbl_fn(), and ftok_sgl_fn().
integer (kind=c_int), parameter constants_and_conversions::izero = 0_c_int
Definition at line 53 of file constants_and_conversions.F90.
Referenced by data_catalog_entry::data_gridhandlemissingdata_int().
real (kind=c_float), parameter constants_and_conversions::fzero = 0.0_c_float
Definition at line 54 of file constants_and_conversions.F90.
Referenced by continuous_frozen_ground_index::initialize_continuous_frozen_ground_index(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), model_initialize::initialize_snow_storage(), and model_initialize::initialize_soil_storage().
real (kind=c_float), parameter, public constants_and_conversions::rzero = 0.0_c_float
Definition at line 55 of file constants_and_conversions.F90.
Referenced by data_catalog_entry::data_gridhandlemissingdata_real(), et__hargreaves_samani::et0_hargreaves(), grid::grid_completelycover(), grid::grid_convolve_sgl(), grid::grid_createcomplete(), grid::grid_lookupcolumn(), and grid::grid_lookuprow().
real (kind=c_double), parameter constants_and_conversions::dzero = 0.0_c_double
Definition at line 56 of file constants_and_conversions.F90.
character (len=1), parameter, public constants_and_conversions::stab = achar(9)
Definition at line 61 of file constants_and_conversions.F90.
Referenced by parameters::add_filename_to_list_sub(), routing__d8::routing_d8_initialize(), and strings::split_and_return_text_sub().
character (len=2), parameter, public constants_and_conversions::swhitespace = achar(9)//" "
Definition at line 62 of file constants_and_conversions.F90.
Referenced by strings::count_number_of_fields_fn(), and strings::split_and_return_text_sub().
character (len=1), parameter, public constants_and_conversions::sbackslash = achar(92)
Definition at line 63 of file constants_and_conversions.F90.
Referenced by data_catalog_entry::make_filename_from_template().
character (len=1), parameter, public constants_and_conversions::sforwardslash = achar(47)
Definition at line 64 of file constants_and_conversions.F90.
Referenced by data_catalog_entry::make_filename_from_template().
character (len=1), parameter, public constants_and_conversions::sreturn = achar(13)
Definition at line 65 of file constants_and_conversions.F90.
character (len=3), parameter, public constants_and_conversions::scomment_chars = "#!%"
Definition at line 66 of file constants_and_conversions.F90.
character (len=1), parameter constants_and_conversions::sdouble_quote = achar(34)
Definition at line 67 of file constants_and_conversions.F90.
Referenced by keepnumeric(), and file_operations::read_header_fn().
real (kind=c_double), parameter constants_and_conversions::c_per_f = 5.0_c_double / 9.0_c_double
Definition at line 70 of file constants_and_conversions.F90.
Referenced by ftoc_dbl_fn(), ftoc_sgl_fn(), ftok_dbl_fn(), and ftok_sgl_fn().
real (kind=c_double), parameter constants_and_conversions::f_per_c = 9.0_c_double / 5.0_c_double
Definition at line 71 of file constants_and_conversions.F90.
Referenced by ctof_dbl_fn(), and ctof_sgl_fn().
real (kind=c_double), parameter constants_and_conversions::m_per_foot = 0.3048_c_double
Definition at line 72 of file constants_and_conversions.F90.
character (len=:), allocatable constants_and_conversions::output_directory_name
Definition at line 74 of file constants_and_conversions.F90.
Referenced by netcdf4_support::netcdf_open_and_prepare_as_output().
character (len=:), allocatable constants_and_conversions::output_prefix_name
Definition at line 75 of file constants_and_conversions.F90.
Referenced by netcdf4_support::netcdf_open_and_prepare_as_output().
character (len=:), allocatable constants_and_conversions::data_directory_name
Definition at line 76 of file constants_and_conversions.F90.
Referenced by file_operations::fully_qualified_filename(), and model_initialize::set_data_directory().
type (bounds_t), public constants_and_conversions::bnds
Definition at line 87 of file constants_and_conversions.F90.
Referenced by data_catalog_entry::initialize_constant_int_data_object_sub(), data_catalog_entry::initialize_constant_real_data_object_sub(), model_initialize::initialize_grid_options(), data_catalog_entry::initialize_gridded_data_object_sub(), data_catalog_entry::initialize_netcdf_data_object_sub(), routing__d8::routing_d8_initialize(), and data_catalog_entry::transform_grid_to_grid_sub().
real (kind=c_float), parameter constants_and_conversions::tolerance_float = 1.0e-6_c_float
Definition at line 185 of file constants_and_conversions.F90.
Referenced by approx_equal_float_float().
real (kind=c_double), parameter constants_and_conversions::tolerance_double = 1.0e-9_c_double
Definition at line 186 of file constants_and_conversions.F90.
Referenced by approx_equal_double_double().