SWB 2.0: routing__d8 Module Reference
routing__d8 Module Reference
Functions/Subroutines
subroutine, public routing_d8_initialize (lActive, cell_order_index)
integer(kind=c_int) function routing_d8_get_index (iCol, iRow)
subroutine routing_d8_assign_downstream_row_col (lActive)
subroutine routing_d8_determine_solution_order (lActive)
Variables
type(data_catalog_entry_t), pointer pd8_flowdir
integer(kind=c_int), dimension(:,:), allocatable itargetrow
integer(kind=c_int), dimension(:,:), allocatable itargetcol
logical(kind=c_bool), dimension(:,:), allocatable ldownhillmarked
integer(kind=c_int), dimension(:,:), allocatable isumofupslopecells
integer(kind=c_int), dimension(:,:), allocatable inumberofupslopeconnections
integer(kind=c_int), dimension(:,:), allocatable row2d
remove redundant data elements; row1d, col1d, etc.
integer(kind=c_int), dimension(:,:), allocatable col2d
integer(kind=c_int), dimension(:), allocatable row1d
integer(kind=c_int), dimension(:), allocatable col1d
integer(kind=c_int), dimension(:), allocatable row_index
integer(kind=c_int), dimension(:), allocatable column_index
integer(kind=c_int), dimension(:), allocatable, public order_index
integer(kind=c_int), dimension(:), allocatable, public target_index
integer(kind=c_int), parameter d8_east = 1
integer(kind=c_int), parameter d8_southeast = 2
integer(kind=c_int), parameter d8_south = 4
integer(kind=c_int), parameter d8_southwest = 8
integer(kind=c_int), parameter d8_west = 16
integer(kind=c_int), parameter d8_northwest = 32
integer(kind=c_int), parameter d8_north = 64
integer(kind=c_int), parameter d8_northeast = 128
integer(kind=c_int), parameter, public d8_undetermined = -999
Function/Subroutine Documentation
subroutine, public routing__d8::routing_d8_initialize (logical (kind=c_bool), dimension(:,:), intent(in) lActive, integer (kind=c_int), dimension(:), intent(inout) cell_order_index)
Definition at line 57 of file routing__D8.F90.
References constants_and_conversions::bnds, col1d, col2d, column_index, data_catalog::dat, constants_and_conversions::datatype_int, exceptions::die(), grid::grid_writearcgrid(), inumberofupslopeconnections, isumofupslopecells, itargetcol, itargetrow, ldownhillmarked, order_index, pd8_flowdir, routing_d8_assign_downstream_row_col(), routing_d8_determine_solution_order(), row1d, row2d, row_index, constants_and_conversions::stab, and target_index.
Referenced by model_domain::model_initialize_routing_d8().
integer (kind=c_int) function routing__d8::routing_d8_get_index (integer (kind=c_int), intent(in) iCol, integer (kind=c_int), intent(in) iRow) private
Definition at line 203 of file routing__D8.F90.
References col1d, and row1d.
Referenced by routing_d8_determine_solution_order().
subroutine routing__d8::routing_d8_assign_downstream_row_col (logical (kind=c_bool), dimension(:,:), intent(in) lActive) private
Definition at line 233 of file routing__D8.F90.
References d8_east, d8_north, d8_northeast, d8_northwest, d8_south, d8_southeast, d8_southwest, d8_undetermined, d8_west, itargetcol, itargetrow, and pd8_flowdir.
Referenced by routing_d8_initialize().
subroutine routing__d8::routing_d8_determine_solution_order (logical (kind=c_bool), dimension(:,:), intent(in) lActive) private
Definition at line 314 of file routing__D8.F90.
References column_index, d8_undetermined, grid::grid_destroy(), grid::grid_writearcgrid(), inumberofupslopeconnections, isumofupslopecells, itargetcol, itargetrow, ldownhillmarked, order_index, pd8_flowdir, routing_d8_get_index(), row_index, and target_index.
Referenced by routing_d8_initialize().
Variable Documentation
type (data_catalog_entry_t), pointer routing__d8::pd8_flowdir private
Definition at line 16 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col(), routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), dimension(:,:), allocatable routing__d8::itargetrow private
Definition at line 18 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col(), routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), dimension(:,:), allocatable routing__d8::itargetcol private
Definition at line 19 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col(), routing_d8_determine_solution_order(), and routing_d8_initialize().
logical (kind=c_bool), dimension(:,:), allocatable routing__d8::ldownhillmarked private
Definition at line 20 of file routing__D8.F90.
Referenced by routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), dimension(:,:), allocatable routing__d8::isumofupslopecells private
Definition at line 21 of file routing__D8.F90.
Referenced by routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), dimension(:,:), allocatable routing__d8::inumberofupslopeconnections private
Definition at line 22 of file routing__D8.F90.
Referenced by routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), dimension(:,:), allocatable routing__d8::row2d private
are now also stored in the model data structure.
Definition at line 26 of file routing__D8.F90.
Referenced by routing_d8_initialize().
integer (kind=c_int), dimension(:,:), allocatable routing__d8::col2d private
Definition at line 27 of file routing__D8.F90.
Referenced by routing_d8_initialize().
integer (kind=c_int), dimension(:), allocatable routing__d8::row1d private
Definition at line 28 of file routing__D8.F90.
Referenced by routing_d8_get_index(), and routing_d8_initialize().
integer (kind=c_int), dimension(:), allocatable routing__d8::col1d private
Definition at line 29 of file routing__D8.F90.
Referenced by routing_d8_get_index(), and routing_d8_initialize().
integer (kind=c_int), dimension(:), allocatable routing__d8::row_index private
Definition at line 31 of file routing__D8.F90.
Referenced by routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), dimension(:), allocatable routing__d8::column_index private
Definition at line 32 of file routing__D8.F90.
Referenced by routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), dimension(:), allocatable, public routing__d8::order_index
Definition at line 33 of file routing__D8.F90.
Referenced by routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), dimension(:), allocatable, public routing__d8::target_index
Definition at line 34 of file routing__D8.F90.
Referenced by model_domain::model_calculate_routing_d8(), routing_d8_determine_solution_order(), and routing_d8_initialize().
integer (kind=c_int), parameter routing__d8::d8_east = 1 private
Definition at line 36 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col().
integer (kind=c_int), parameter routing__d8::d8_southeast = 2 private
Definition at line 37 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col().
integer (kind=c_int), parameter routing__d8::d8_south = 4 private
Definition at line 38 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col().
integer (kind=c_int), parameter routing__d8::d8_southwest = 8 private
Definition at line 39 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col().
integer (kind=c_int), parameter routing__d8::d8_west = 16 private
Definition at line 40 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col().
integer (kind=c_int), parameter routing__d8::d8_northwest = 32 private
Definition at line 41 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col().
integer (kind=c_int), parameter routing__d8::d8_north = 64 private
Definition at line 42 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col().
integer (kind=c_int), parameter routing__d8::d8_northeast = 128 private
Definition at line 43 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col().
integer (kind=c_int), parameter, public routing__d8::d8_undetermined = -999
Definition at line 45 of file routing__D8.F90.
Referenced by routing_d8_assign_downstream_row_col(), and routing_d8_determine_solution_order().