SWB 2.0: parameters Module Reference
parameters Module Reference
Data Types
type parameters_t
Functions/Subroutines
subroutine add_filename_to_list_sub (this, sFilename, sDelimiters, sCommentChars)
subroutine munge_files_and_add_to_param_list_sub (this)
subroutine add_to_param_list_sub (this, sKey, sValues, iValues, fValues, dValues, lValues)
type(string_list_t) function grep_parameter_name (this, sKey, lFatal)
subroutine get_parameter_values_logical (this, lValues, slKeys, sKey, lFatal)
subroutine get_parameter_values_string_list (this, slValues, slKeys, sKey, lFatal)
subroutine get_parameter_values_int (this, iValues, slKeys, sKey, lFatal)
subroutine get_parameter_values_float (this, fValues, slKeys, sKey, lFatal)
subroutine get_parameter_table_float (this, fValues, sPrefix, iNumRows, lFatal)
Variables
type(parameters_t), public params
type(dict_t), public params_dict
integer(kind=c_int), parameter max_table_record_len = 512
Function/Subroutine Documentation
subroutine parameters::add_filename_to_list_sub (class (parameters_t) this, character (len=*), intent(in) sFilename, character (len=*), intent(in), optional sDelimiters, character (len=*), intent(in), optional sCommentChars) private
Definition at line 75 of file parameters.F90.
References constants_and_conversions::stab.
subroutine parameters::munge_files_and_add_to_param_list_sub (class (parameters_t) this) private
Definition at line 108 of file parameters.F90.
References logfiles::logs, params_dict, and exceptions::warn().
subroutine parameters::add_to_param_list_sub (class (parameters_t) this, character (len=*), intent(in) sKey, character (len=*), dimension(:), intent(in), optional sValues, integer (kind=c_int), dimension(:), intent(in), optional iValues, real (kind=c_float), dimension(:), intent(in), optional fValues, real (kind=c_double), dimension(:), intent(in), optional dValues, logical (kind=c_bool), dimension(:), intent(in), optional lValues) private
Definition at line 199 of file parameters.F90.
References params_dict.
type (string_list_t) function parameters::grep_parameter_name (class (parameters_t) this, character (len=*), intent(in) sKey, logical (kind=c_bool), intent(in), optional lFatal) private
Definition at line 280 of file parameters.F90.
References constants_and_conversions::lfalse, params_dict, and exceptions::warn().
subroutine parameters::get_parameter_values_logical (class (parameters_t) this, logical (kind=c_bool), dimension(:), intent(inout), allocatable lValues, type (string_list_t), intent(inout), optional slKeys, character (len=*), intent(in), optional sKey, logical (kind=c_bool), intent(in), optional lFatal) private
Definition at line 310 of file parameters.F90.
References constants_and_conversions::lfalse, and params_dict.
subroutine parameters::get_parameter_values_string_list (class (parameters_t) this, type (string_list_t), intent(inout) slValues, type (string_list_t), intent(inout), optional slKeys, character (len=*), intent(in), optional sKey, logical (kind=c_bool), intent(in), optional lFatal) private
Definition at line 349 of file parameters.F90.
References constants_and_conversions::lfalse, params_dict, and exceptions::warn().
subroutine parameters::get_parameter_values_int (class (parameters_t) this, integer (kind=c_int), dimension(:), intent(inout), allocatable iValues, type (string_list_t), intent(inout), optional slKeys, character (len=*), intent(in), optional sKey, logical (kind=c_bool), intent(in), optional lFatal) private
Definition at line 388 of file parameters.F90.
References constants_and_conversions::itinyval, constants_and_conversions::lfalse, params_dict, and exceptions::warn().
subroutine parameters::get_parameter_values_float (class (parameters_t) this, real (kind=c_float), dimension(:), intent(inout), allocatable fValues, type (string_list_t), intent(inout), optional slKeys, character (len=*), intent(in), optional sKey, logical (kind=c_bool), intent(in), optional lFatal) private
Definition at line 427 of file parameters.F90.
References constants_and_conversions::ftinyval, constants_and_conversions::lfalse, params_dict, and exceptions::warn().
subroutine parameters::get_parameter_table_float (class (parameters_t) this, real (kind=c_float), dimension(:,:), intent(inout), allocatable fValues, character (len=*), intent(in) sPrefix, integer (kind=c_int), intent(in) iNumRows, logical (kind=c_bool), intent(in), optional lFatal) private
Definition at line 466 of file parameters.F90.
References constants_and_conversions::lfalse, params, params_dict, and exceptions::warn().
Variable Documentation
type (parameters_t), public parameters::params
Definition at line 67 of file parameters.F90.
Referenced by awc__depth_integrated::awc_depth_integrated_read(), model_initialize::create_rooting_depth_table(), direct_recharge__gridded_data::direct_recharge_initialize(), direct_soil_moisture__gridded_data::direct_soil_moisture_initialize(), fog__monthly_grid::fog_monthly_grid_initialize(), get_parameter_table_float(), growing_degree_day::growing_degree_day_initialize(), growing_season::growing_season_initialize(), actual_et__fao56::initialize_actual_et_fao56(), model_initialize::initialize_landuse_codes(), model_initialize::initialize_parameter_tables(), model_initialize::initialize_surface_storage_max(), interception__bucket::interception_bucket_initialize(), interception__gash::interception_gash_initialize(), maximum_potential_recharge__gridded_data::maximum_potential_recharge_initialize(), runoff__curve_number::runoff_curve_number_initialize(), and storm_drain_capture::storm_drain_capture_initialize().
type (dict_t), public parameters::params_dict
Definition at line 68 of file parameters.F90.
Referenced by add_to_param_list_sub(), get_parameter_table_float(), get_parameter_values_float(), get_parameter_values_int(), get_parameter_values_logical(), get_parameter_values_string_list(), grep_parameter_name(), model_initialize::initialize_parameter_tables(), and munge_files_and_add_to_param_list_sub().
integer (kind=c_int), parameter parameters::max_table_record_len = 512 private
Definition at line 70 of file parameters.F90.