SWB 2.0: growing_season Module Reference
growing_season Module Reference
Functions/Subroutines
subroutine, public growing_season_initialize ()
elemental subroutine, public growing_season_update (landuse_index, GDD, mean_air_temp, it_is_growing_season)
Variables
integer(kind=c_int), dimension(:), allocatable ilandusecodes
real(kind=c_float), dimension(:), allocatable first_day_of_growing_season
real(kind=c_float), dimension(:), allocatable last_day_of_growing_season
real(kind=c_float), dimension(:), allocatable gdd_first_day_of_growing_season
real(kind=c_float), dimension(:), allocatable killing_frost_temp_last_day_of_growing_season
character(len=2), parameter date_delims = "/-"
real(kind=c_float), parameter nodata_value = -9999._c_float
Function/Subroutine Documentation
growing_season_initialize()
subroutine, public growing_season::growing_season_initialize ()
Determine how many landuse codes are present
retrieve first day of growing season
process first day of growing season. retrieved as a list of strings; must convert the strings from mm/dd to DOY
retrieve last day of growing season
process last day of growing season. retrieved as a list of strings; must convert the strings from mm/dd to DOY
GDD for first day of growing season
Air temperature defining last day of growing season
Definition at line 30 of file growing_season.F90.
References date_delims, constants_and_conversions::false, first_day_of_growing_season, gdd_first_day_of_growing_season, ilandusecodes, killing_frost_temp_last_day_of_growing_season, last_day_of_growing_season, datetime::mmdd2doy(), nodata_value, parameters::params, constants_and_conversions::true, and exceptions::warn().
Referenced by model_domain::model_initialize_growing_season().
growing_season_update()
elemental subroutine, public growing_season::growing_season_update (integer (kind=c_int), intent(in) landuse_index, real (kind=c_float), intent(in) GDD, real (kind=c_float), intent(in) mean_air_temp, logical (kind=c_bool), intent(inout) it_is_growing_season)
Definition at line 191 of file growing_season.F90.
References constants_and_conversions::false, first_day_of_growing_season, gdd_first_day_of_growing_season, killing_frost_temp_last_day_of_growing_season, last_day_of_growing_season, nodata_value, simulation_datetime::sim_dt, and constants_and_conversions::true.
Referenced by model_domain::model_update_growing_season().
Variable Documentation
ilandusecodes
integer (kind=c_int), dimension(:), allocatable growing_season::ilandusecodes private
Definition at line 18 of file growing_season.F90.
Referenced by growing_season_initialize().
first_day_of_growing_season
real (kind=c_float), dimension(:), allocatable growing_season::first_day_of_growing_season private
Definition at line 19 of file growing_season.F90.
Referenced by growing_season_initialize(), and growing_season_update().
last_day_of_growing_season
real (kind=c_float), dimension(:), allocatable growing_season::last_day_of_growing_season private
Definition at line 20 of file growing_season.F90.
Referenced by growing_season_initialize(), and growing_season_update().
gdd_first_day_of_growing_season
real (kind=c_float), dimension(:), allocatable growing_season::gdd_first_day_of_growing_season private
Definition at line 21 of file growing_season.F90.
Referenced by growing_season_initialize(), and growing_season_update().
killing_frost_temp_last_day_of_growing_season
real (kind=c_float), dimension(:), allocatable growing_season::killing_frost_temp_last_day_of_growing_season private
Definition at line 22 of file growing_season.F90.
Referenced by growing_season_initialize(), and growing_season_update().
date_delims
character(len=2), parameter growing_season::date_delims = "/-" private
Definition at line 24 of file growing_season.F90.
Referenced by growing_season_initialize().
nodata_value
real (kind=c_float), parameter growing_season::nodata_value = -9999._c_float private
Definition at line 25 of file growing_season.F90.
Referenced by growing_season_initialize(), and growing_season_update().