SWB 2.0: actual_et__fao56 Module Reference
actual_et__fao56 Module Reference
Functions/Subroutines
subroutine initialize_actual_et_fao56 ()
elemental real(kind=c_float) function adjust_depletion_fraction_p (p_table_22, reference_et0)
Adjust the depletion fraction based on current reference ET0.
elemental subroutine calculate_actual_et_fao56 (actual_et, adjusted_depletion_fraction_p, soil_storage, depletion_fraction_p, soil_storage_max, infiltration, crop_etc)
Variables
real(kind=c_float), dimension(:), allocatable depletion_fraction
real(kind=c_float), parameter near_zero = 3.0_c_float * tiny(0.0_c_float)
Function/Subroutine Documentation
initialize_actual_et_fao56()
subroutine actual_et__fao56::initialize_actual_et_fao56 ()
Definition at line 15 of file actual_et__fao56.F90.
References depletion_fraction, constants_and_conversions::ltrue, and parameters::params.
Referenced by model_domain::model_initialize_actual_et_fao56().
adjust_depletion_fraction_p()
elemental real (kind=c_float) function actual_et__fao56::adjust_depletion_fraction_p (real (kind=c_float), intent(in) p_table_22, real (kind=c_float), intent(in) reference_et0)
From FAO-56: "The fraction p is a function of the evaporation power of the atmosphere. At low rates of ETc, the p values listed in Table 22 are higher than at high rates of ETc. For hot dry weather conditions, where ETc is high, p is 10-25% less than the values presented in Table 22, and the soil is still relatively wet when the stress starts to occur. When the crop evapotranspiration is low, p will be up to 20% more than the listed values.
Parameters
[in] p_table_22 This is the unadjusted depletion fraction value; FAO-56 table 22 gives values of the depletion fraction relative to a reference ET0 value of 5mm.
[in] reference_et0 The reference ET0 to which the depletion fraction will be adjusted.
Note
Discussed as a footnote to Table 22, FAO-56, Allen and others. See http://www.fao.org/docrep/x0490e/x0490e0e.htm::TopOfPage for details.
Definition at line 36 of file actual_et__fao56.F90.
Referenced by calculate_actual_et_fao56().
calculate_actual_et_fao56()
elemental subroutine actual_et__fao56::calculate_actual_et_fao56 (real (kind=c_float), intent(inout) actual_et, real (kind=c_float), intent(inout) adjusted_depletion_fraction_p, real (kind=c_float), intent(in) soil_storage, real (kind=c_float), intent(in) depletion_fraction_p, real (kind=c_float), intent(in) soil_storage_max, real (kind=c_float), intent(in) infiltration, real (kind=c_float), intent(in) crop_etc)
Definition at line 57 of file actual_et__fao56.F90.
References adjust_depletion_fraction_p(), and near_zero.
Referenced by model_domain::model_calculate_actual_et_fao56().
Variable Documentation
depletion_fraction
real (kind=c_float), dimension(:), allocatable actual_et__fao56::depletion_fraction
Definition at line 9 of file actual_et__fao56.F90.
Referenced by initialize_actual_et_fao56(), and model_domain::model_calculate_actual_et_fao56().
near_zero
real (kind=c_float), parameter actual_et__fao56::near_zero = 3.0_c_float * tiny(0.0_c_float)
Definition at line 10 of file actual_et__fao56.F90.
Referenced by calculate_actual_et_fao56().