SWB 2.0: direct_soil_moisture__gridded_data Module Reference
direct_soil_moisture__gridded_data Module Reference
Module direct_soil_moisture__gridded_data provides support for adding miscellaneous source and sink terms.
Functions/Subroutines
subroutine, public direct_soil_moisture_initialize (is_cell_active, landuse_index)
Initialize the routine to enable input/output of arbitrary sources/sink terms to be added directly to SOIL MOISTURE.
subroutine, public direct_soil_moisture_calculate (direct_soil_moisture, is_cell_active, indx)
Variables
type(data_catalog_entry_t), pointer pseptic_discharge
type(data_catalog_entry_t), pointer pannual_septic_discharge
real(kind=c_float), dimension(:), allocatable fseptic_discharge
real(kind=c_float), dimension(:), allocatable fannual_septic_discharge
real(kind=c_float), dimension(:), allocatable fseptic_discharge_table
real(kind=c_float), dimension(:), allocatable fannual_septic_discharge_table
type(t_netcdf4_file), pointer pncfile
type(datetime_t), pointer date_of_last_retrieval
Detailed Description
Function/Subroutine Documentation
direct_soil_moisture_initialize()
subroutine, public direct_soil_moisture__gridded_data::direct_soil_moisture_initialize (logical (kind=c_bool), dimension(:,:), intent(in) is_cell_active, integer (kind=c_int), dimension(:), intent(in) landuse_index)
Open gridded data file. Open a NetCDF output file to hold variable output.
Parameters
[in] lActive 2D array of active cells within the model domain.
[in] iLanduseIndex 1D vector of indices corresponding to rows of the landuse lookup table(s).
[in] dX 1D vector of X coordinates associated with the model domain.
[in] dY 1D vector of Y coordinates.
[in] dX_lon 2D array of longitude values.
[in] dY_lat 2D array of latitude values.
Determine how many landuse codes are present
Definition at line 60 of file direct_soil_moisture__gridded_data.F90.
References data_catalog::dat, date_of_last_retrieval, fannual_septic_discharge, fannual_septic_discharge_table, fseptic_discharge, fseptic_discharge_table, constants_and_conversions::ftinyval, pannual_septic_discharge, parameters::params, pseptic_discharge, constants_and_conversions::true, and exceptions::warn().
Referenced by model_domain::model_initialize_direct_soil_moisture_gridded().
direct_soil_moisture_calculate()
subroutine, public direct_soil_moisture__gridded_data::direct_soil_moisture_calculate (real (kind=c_float), intent(inout) direct_soil_moisture, logical (kind=c_bool), dimension(:,:), intent(in) is_cell_active, integer (kind=c_int), intent(in) indx)
Definition at line 163 of file direct_soil_moisture__gridded_data.F90.
References date_of_last_retrieval, fannual_septic_discharge, fseptic_discharge, pannual_septic_discharge, pseptic_discharge, and simulation_datetime::sim_dt.
Referenced by model_domain::model_calculate_direct_soil_moisture_gridded().
Variable Documentation
pseptic_discharge
type (data_catalog_entry_t), pointer direct_soil_moisture__gridded_data::pseptic_discharge private
Definition at line 30 of file direct_soil_moisture__gridded_data.F90.
Referenced by direct_soil_moisture_calculate(), and direct_soil_moisture_initialize().
pannual_septic_discharge
type (data_catalog_entry_t), pointer direct_soil_moisture__gridded_data::pannual_septic_discharge private
Definition at line 31 of file direct_soil_moisture__gridded_data.F90.
Referenced by direct_soil_moisture_calculate(), and direct_soil_moisture_initialize().
fseptic_discharge
real (kind=c_float), dimension(:), allocatable direct_soil_moisture__gridded_data::fseptic_discharge private
Definition at line 33 of file direct_soil_moisture__gridded_data.F90.
Referenced by direct_soil_moisture_calculate(), and direct_soil_moisture_initialize().
fannual_septic_discharge
real (kind=c_float), dimension(:), allocatable direct_soil_moisture__gridded_data::fannual_septic_discharge private
Definition at line 34 of file direct_soil_moisture__gridded_data.F90.
Referenced by direct_soil_moisture_calculate(), and direct_soil_moisture_initialize().
fseptic_discharge_table
real (kind=c_float), dimension(:), allocatable direct_soil_moisture__gridded_data::fseptic_discharge_table private
Definition at line 36 of file direct_soil_moisture__gridded_data.F90.
Referenced by direct_soil_moisture_initialize().
fannual_septic_discharge_table
real (kind=c_float), dimension(:), allocatable direct_soil_moisture__gridded_data::fannual_septic_discharge_table private
Definition at line 37 of file direct_soil_moisture__gridded_data.F90.
Referenced by direct_soil_moisture_initialize().
pncfile
type (t_netcdf4_file), pointer direct_soil_moisture__gridded_data::pncfile private
Definition at line 39 of file direct_soil_moisture__gridded_data.F90.
date_of_last_retrieval
type (datetime_t), pointer direct_soil_moisture__gridded_data::date_of_last_retrieval private
Definition at line 41 of file direct_soil_moisture__gridded_data.F90.
Referenced by direct_soil_moisture_calculate(), and direct_soil_moisture_initialize().