SWB 2.0: data_catalog_entry Module Reference
data_catalog_entry Module Reference
Data Types
interface apply_scale_and_offset
type data_catalog_entry_t
Functions/Subroutines
subroutine nullify_pointers_sub (this)
subroutine set_keyword_sub (this, sKeyword)
subroutine get_value_int_sub (this, iCol, iRow, iValue)
subroutine get_value_float_sub (this, iCol, iRow, fValue)
subroutine initialize_constant_real_data_object_sub (this, sDescription, rConstant)
subroutine initialize_constant_int_data_object_sub (this, sDescription, iConstant)
subroutine initialize_gridded_data_object_sub (this, sDescription, sFileType, iDataType, sFilename, sPROJ4_string)
subroutine initialize_netcdf_data_object_sub (this, sDescription, iDataType, sFilename, sPROJ4_string)
subroutine getvalues_sub (this, iMonth, iDay, iYear, iJulianDay)
elemental subroutine apply_scale_and_offset_float (fResult, fValue, dUserScaleFactor, dUserAddOffset)
elemental subroutine apply_scale_and_offset_int (iResult, iValue, dUserScaleFactor, dUserAddOffset)
subroutine getvalues_constant_sub (this)
subroutine dump_data_structure_sub (this)
subroutine getvalues_gridded_sub (this, iMonth, iDay, iYear)
subroutine transform_grid_to_grid_sub (this)
subroutine set_constant_value_int (this, iValue)
subroutine set_constant_value_real (this, rValue)
subroutine set_filecount (this, iValue, iYear)
subroutine increment_filecount (this)
subroutine reset_filecount (this)
subroutine reset_at_yearend_filecount (this, iYear)
subroutine make_filename_from_template (this, iMonth, iDay, iYear)
logical(kind=c_bool) function test_for_need_to_pad_values_fn (this, iMonth, iDay, iYear)
subroutine getvalues_dynamic_netcdf_sub (this, iMonth, iDay, iYear, iJulianDay)
subroutine minmaxmean_float (variable, varname, nodata_value)
subroutine getvalues_static_netcdf_sub (this)
subroutine put_values_to_local_netcdf_sub (this, iMonth, iDay, iYear)
integer(kind=c_int) function get_source_filetype_fn (this)
subroutine set_proj4_string_sub (this, sPROJ4_string)
subroutine set_grid_flip_horizontal_sub (this)
subroutine set_grid_flip_vertical_sub (this)
subroutine set_variable_order_sub (this, sVariableOrder)
subroutine set_scale_sub (this, rScaleFactor)
subroutine set_archive_local_sub (this, lValue)
subroutine set_offset_sub (this, rAddOffset)
subroutine set_majority_filter_flag_sub (this, lUseMajorityFilter)
subroutine set_missing_value_int_sub (this, iMissingVal)
subroutine set_missing_value_real_sub (this, rMissingVal)
subroutine set_complete_spatial_coverage_flag_sub (this, lRequireCompleteSpatialCoverage)
subroutine set_minimum_allowable_value_int_sub (this, iMinVal)
subroutine set_maximum_allowable_value_int_sub (this, iMaxVal)
subroutine set_minimum_allowable_value_real_sub (this, rMinVal)
subroutine set_maximum_allowable_value_real_sub (this, rMaxVal)
subroutine calc_project_boundaries_sub (this, pGrdBase)
subroutine data_gridenforcelimits_int (this, iValues)
subroutine data_gridenforcelimits_real (this, rValues)
subroutine data_gridhandlemissingdata_real (this, rValues)
subroutine data_gridhandlemissingdata_int (this, iValues)
Variables
integer(kind=c_int), parameter, public netcdf_file_open = 27
integer(kind=c_int), parameter, public netcdf_file_closed = 42
integer(kind=c_int), parameter, public file_template_capitalized_monthname = 0
integer(kind=c_int), parameter, public file_template_lowercase_monthname = 1
integer(kind=c_int), parameter, public file_template_uppercase_monthname = 2
integer(kind=c_int), parameter, public missing_values_zero_out = 0
integer(kind=c_int), parameter, public missing_values_replace_with_mean = 1
integer(kind=c_int), parameter constant_grid = 0
integer(kind=c_int), parameter static_grid = 1
integer(kind=c_int), parameter static_netcdf_grid = 2
integer(kind=c_int), parameter dynamic_grid = 3
integer(kind=c_int), parameter dynamic_netcdf_grid = 4
integer(kind=c_int), parameter filetype_arc_ascii = 0
integer(kind=c_int), parameter filetype_surfer = 1
integer(kind=c_int), parameter filetype_netcdf = 2
integer(kind=c_int), parameter filetype_none = 3
type(general_grid_t), pointer, public pgrd => null()
Function/Subroutine Documentation
subroutine data_catalog_entry::nullify_pointers_sub (class (data_catalog_entry_t) this) private
Definition at line 220 of file data_catalog_entry.F90.
References netcdf4_support::netcdf_nullify_data_struct(), and pgrd.
subroutine data_catalog_entry::set_keyword_sub (class (data_catalog_entry_t) this, character (len=*), intent(in) sKeyword) private
Definition at line 235 of file data_catalog_entry.F90.
subroutine data_catalog_entry::get_value_int_sub (class (data_catalog_entry_t), intent(in) this, integer (kind=c_int), intent(in) iCol, integer (kind=c_int), intent(in) iRow, integer (kind=c_int), intent(out) iValue) private
Definition at line 244 of file data_catalog_entry.F90.
References exceptions::die().
subroutine data_catalog_entry::get_value_float_sub (class (data_catalog_entry_t), intent(in) this, integer (kind=c_int), intent(in) iCol, integer (kind=c_int), intent(in) iRow, real (kind=c_float), intent(out) fValue) private
Definition at line 264 of file data_catalog_entry.F90.
References exceptions::die().
subroutine data_catalog_entry::initialize_constant_real_data_object_sub (class (data_catalog_entry_t) this, character (len=*), intent(in) sDescription, real (kind=c_float), intent(in) rConstant) private
Definition at line 287 of file data_catalog_entry.F90.
References constants_and_conversions::bnds, constant_grid, constants_and_conversions::datatype_real, and filetype_none.
subroutine data_catalog_entry::initialize_constant_int_data_object_sub (class (data_catalog_entry_t) this, character (len=*) sDescription, integer (kind=c_int), intent(in) iConstant) private
Definition at line 314 of file data_catalog_entry.F90.
References constants_and_conversions::bnds, constant_grid, constants_and_conversions::datatype_int, and filetype_none.
subroutine data_catalog_entry::initialize_gridded_data_object_sub (class (data_catalog_entry_t) this, character (len=*), intent(in) sDescription, character (len=*), intent(in) sFileType, integer (kind=c_int) iDataType, character (len=*), intent(in) sFilename, character (len=*), intent(in), optional sPROJ4_string) private
if either a '' or '#' character is present in the filename treat it as a template, not as a normal filename.
Definition at line 344 of file data_catalog_entry.F90.
References constants_and_conversions::bnds, constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, dynamic_grid, filetype_arc_ascii, filetype_surfer, file_operations::fully_qualified_filename(), constants_and_conversions::lfalse, constants_and_conversions::ltrue, and static_grid.
subroutine data_catalog_entry::initialize_netcdf_data_object_sub (class (data_catalog_entry_t) this, character (len=*), intent(in) sDescription, integer (kind=c_int), intent(in) iDataType, character (len=*), intent(in) sFilename, character (len=*), intent(in), optional sPROJ4_string) private
if either a '' or '#' character is present in the filename, treat it as a template, not as a normal filename. if there is a template, the implication is that there is a series of files that will be read in successively, thus "dynamic" NetCDF
Implement a way to read variables in via "static" NetCDF grid. In other words, a NetCDF grid having no "time" dimension or variable.
Definition at line 412 of file data_catalog_entry.F90.
References constants_and_conversions::bnds, dynamic_netcdf_grid, file_operations::fully_qualified_filename(), constants_and_conversions::ltrue, and netcdf_file_closed.
subroutine data_catalog_entry::getvalues_sub (class (data_catalog_entry_t) this, integer (kind=c_int), intent(in), optional iMonth, integer (kind=c_int), intent(in), optional iDay, integer (kind=c_int), intent(in), optional iYear, integer (kind=c_int), intent(in), optional iJulianDay) private
Now apply the user scale and offset amounts
Definition at line 475 of file data_catalog_entry.F90.
References constant_grid, constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, exceptions::die(), dynamic_grid, dynamic_netcdf_grid, getvalues_constant_sub(), getvalues_dynamic_netcdf_sub(), getvalues_gridded_sub(), getvalues_static_netcdf_sub(), constants_and_conversions::lfalse, static_grid, and static_netcdf_grid.
elemental subroutine data_catalog_entry::apply_scale_and_offset_float (real (kind=c_float), intent(out) fResult, real (kind=c_float), intent(in) fValue, real (kind=c_double), intent(in) dUserScaleFactor, real (kind=c_double), intent(in) dUserAddOffset) private
Definition at line 541 of file data_catalog_entry.F90.
elemental subroutine data_catalog_entry::apply_scale_and_offset_int (integer (kind=c_int), intent(out) iResult, integer (kind=c_int), intent(in) iValue, real (kind=c_double), intent(in) dUserScaleFactor, real (kind=c_double), intent(in) dUserAddOffset) private
Definition at line 554 of file data_catalog_entry.F90.
subroutine data_catalog_entry::getvalues_constant_sub (class (data_catalog_entry_t) this) private
Definition at line 567 of file data_catalog_entry.F90.
References constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, exceptions::die(), dump_data_structure_sub(), constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
Referenced by getvalues_sub().
subroutine data_catalog_entry::dump_data_structure_sub (class (data_catalog_entry_t) this) private
Definition at line 603 of file data_catalog_entry.F90.
References grid::grid_dumpgridextent(), and logfiles::logs.
Referenced by getvalues_constant_sub().
subroutine data_catalog_entry::getvalues_gridded_sub (class (data_catalog_entry_t) this, integer (kind=c_int), optional iMonth, integer (kind=c_int), optional iDay, integer (kind=c_int), optional iYear) private
Definition at line 629 of file data_catalog_entry.F90.
References dynamic_grid, filetype_arc_ascii, filetype_surfer, grid::grid_datatype_int, grid::grid_datatype_real, grid::grid_destroy(), grid::grid_read(), grid::grid_readexisting(), constants_and_conversions::lfalse, logfiles::logs, constants_and_conversions::ltrue, and pgrd.
Referenced by getvalues_sub().
subroutine data_catalog_entry::transform_grid_to_grid_sub (class (data_catalog_entry_t) this) private
Definition at line 730 of file data_catalog_entry.F90.
References constants_and_conversions::bnds, exceptions::die(), grid::grid_completelycover(), grid::grid_datatype_int, grid::grid_datatype_real, grid::grid_gridtogrid_int(), grid::grid_gridtogrid_sgl(), grid::grid_transform(), constants_and_conversions::lfalse, logfiles::logs, and pgrd.
subroutine data_catalog_entry::set_constant_value_int (class (data_catalog_entry_t) this, integer (kind=c_int) iValue) private
Definition at line 788 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_constant_value_real (class (data_catalog_entry_t) this, real (kind=c_float) rValue) private
Definition at line 799 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_filecount (class (data_catalog_entry_t) this, integer (kind=c_int) iValue, integer (kind=c_int), optional iYear) private
Definition at line 810 of file data_catalog_entry.F90.
subroutine data_catalog_entry::increment_filecount (class (data_catalog_entry_t) this) private
Definition at line 824 of file data_catalog_entry.F90.
subroutine data_catalog_entry::reset_filecount (class (data_catalog_entry_t) this) private
Definition at line 834 of file data_catalog_entry.F90.
subroutine data_catalog_entry::reset_at_yearend_filecount (class (data_catalog_entry_t) this, integer (kind=c_int) iYear) private
Definition at line 844 of file data_catalog_entry.F90.
subroutine data_catalog_entry::make_filename_from_template (class (data_catalog_entry_t) this, integer (kind=c_int), optional iMonth, integer (kind=c_int), optional iDay, integer (kind=c_int), optional iYear) private
Definition at line 858 of file data_catalog_entry.F90.
References file_template_lowercase_monthname, file_template_uppercase_monthname, constants_and_conversions::lfalse, constants_and_conversions::ltrue, datetime::months, constants_and_conversions::sbackslash, and constants_and_conversions::sforwardslash.
logical (kind=c_bool) function data_catalog_entry::test_for_need_to_pad_values_fn (class (data_catalog_entry_t) this, integer (kind=c_int) iMonth, integer (kind=c_int) iDay, integer (kind=c_int) iYear) private
Definition at line 1068 of file data_catalog_entry.F90.
References datetime::isleap(), constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
subroutine data_catalog_entry::getvalues_dynamic_netcdf_sub (class (data_catalog_entry_t) this, integer (kind=c_int) iMonth, integer (kind=c_int) iDay, integer (kind=c_int) iYear, integer (kind=c_int) iJulianDay) private
Definition at line 1144 of file data_catalog_entry.F90.
References exceptions::die(), grid::grid_destroy(), constants_and_conversions::lfalse, logfiles::logs, constants_and_conversions::ltrue, netcdf4_support::nc_bottom, netcdf4_support::nc_left, netcdf4_support::nc_right, netcdf4_support::nc_top, netcdf4_support::nc_z, netcdf4_support::netcdf_close_file(), netcdf4_support::netcdf_date_within_range(), netcdf_file_closed, netcdf_file_open, netcdf4_support::netcdf_get_variable_slice(), netcdf4_support::netcdf_open_and_prepare_as_input(), netcdf4_support::netcdf_open_file(), and netcdf4_support::netcdf_update_time_starting_index().
Referenced by getvalues_sub().
subroutine data_catalog_entry::minmaxmean_float (real (kind=c_float), dimension(:,:) variable, character (len=*), intent(in) varname, real (kind=c_float), intent(in) nodata_value) private
Definition at line 1390 of file data_catalog_entry.F90.
subroutine data_catalog_entry::getvalues_static_netcdf_sub (class (data_catalog_entry_t) this) private
Definition at line 1427 of file data_catalog_entry.F90.
References exceptions::die(), grid::grid_destroy(), constants_and_conversions::lfalse, netcdf4_support::nc_bottom, netcdf4_support::nc_left, netcdf4_support::nc_right, netcdf4_support::nc_top, netcdf4_support::nc_z, netcdf_file_closed, netcdf_file_open, netcdf4_support::netcdf_get_variable_slice(), netcdf4_support::netcdf_open_and_prepare_as_input(), and netcdf4_support::netcdf_open_file().
Referenced by getvalues_sub().
subroutine data_catalog_entry::put_values_to_local_netcdf_sub (class (data_catalog_entry_t) this, integer (kind=c_int) iMonth, integer (kind=c_int) iDay, integer (kind=c_int) iYear) private
Definition at line 1557 of file data_catalog_entry.F90.
References netcdf4_support::nc_time, netcdf4_support::nc_z, netcdf_file_closed, netcdf_file_open, netcdf4_support::netcdf_open_and_prepare_as_output_archive(), netcdf4_support::netcdf_put_variable_array(), and netcdf4_support::netcdf_put_variable_vector().
integer (kind=c_int) function data_catalog_entry::get_source_filetype_fn (class (data_catalog_entry_t) this) private
Definition at line 1602 of file data_catalog_entry.F90.
References filetype_arc_ascii, filetype_netcdf, filetype_surfer, and constants_and_conversions::lfalse.
subroutine data_catalog_entry::set_proj4_string_sub (class (data_catalog_entry_t) this, character (len=*), optional sPROJ4_string) private
Definition at line 1633 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_grid_flip_horizontal_sub (class (data_catalog_entry_t) this) private
Definition at line 1644 of file data_catalog_entry.F90.
References constants_and_conversions::ltrue.
subroutine data_catalog_entry::set_grid_flip_vertical_sub (class (data_catalog_entry_t) this) private
Definition at line 1654 of file data_catalog_entry.F90.
References constants_and_conversions::ltrue.
subroutine data_catalog_entry::set_variable_order_sub (class (data_catalog_entry_t) this, character (len=*) sVariableOrder) private
Definition at line 1664 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_scale_sub (class (data_catalog_entry_t) this, real (kind=c_float) rScaleFactor) private
Definition at line 1675 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_archive_local_sub (class (data_catalog_entry_t) this, logical (kind=c_bool) lValue) private
Definition at line 1686 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_offset_sub (class (data_catalog_entry_t) this, real (kind=c_float) rAddOffset) private
Definition at line 1697 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_majority_filter_flag_sub (class (data_catalog_entry_t) this, logical (kind=c_bool) lUseMajorityFilter) private
Definition at line 1708 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_missing_value_int_sub (class (data_catalog_entry_t) this, integer (kind=c_int) iMissingVal) private
Definition at line 1719 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_missing_value_real_sub (class (data_catalog_entry_t) this, integer (kind=c_int) rMissingVal) private
Definition at line 1730 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_complete_spatial_coverage_flag_sub (class (data_catalog_entry_t) this, logical (kind=c_bool), intent(in) lRequireCompleteSpatialCoverage) private
Definition at line 1741 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_minimum_allowable_value_int_sub (class (data_catalog_entry_t) this, integer (kind=c_int) iMinVal) private
Definition at line 1752 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_maximum_allowable_value_int_sub (class (data_catalog_entry_t) this, integer (kind=c_int) iMaxVal) private
Definition at line 1763 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_minimum_allowable_value_real_sub (class (data_catalog_entry_t) this, real (kind=c_float) rMinVal) private
Definition at line 1774 of file data_catalog_entry.F90.
subroutine data_catalog_entry::set_maximum_allowable_value_real_sub (class (data_catalog_entry_t) this, real (kind=c_float) rMaxVal) private
Definition at line 1785 of file data_catalog_entry.F90.
subroutine data_catalog_entry::calc_project_boundaries_sub (class (data_catalog_entry_t) this, type (general_grid_t), pointer pGrdBase) private
Definition at line 1796 of file data_catalog_entry.F90.
References grid::grid_checkforproj4error().
subroutine data_catalog_entry::data_gridenforcelimits_int (class (data_catalog_entry_t) this, integer (kind=c_int), dimension(:,:) iValues) private
Definition at line 1863 of file data_catalog_entry.F90.
subroutine data_catalog_entry::data_gridenforcelimits_real (class (data_catalog_entry_t) this, real (kind=c_float), dimension(:,:) rValues) private
Definition at line 1881 of file data_catalog_entry.F90.
subroutine data_catalog_entry::data_gridhandlemissingdata_real (class (data_catalog_entry_t) this, real (kind=c_float), dimension(:,:), intent(inout) rValues) private
Definition at line 1899 of file data_catalog_entry.F90.
References constants_and_conversions::lfalse, missing_values_replace_with_mean, missing_values_zero_out, and constants_and_conversions::rzero.
subroutine data_catalog_entry::data_gridhandlemissingdata_int (class (data_catalog_entry_t) this, integer (kind=c_int), dimension(:,:), intent(inout) iValues) private
Definition at line 1996 of file data_catalog_entry.F90.
References constants_and_conversions::izero, constants_and_conversions::lfalse, missing_values_replace_with_mean, and missing_values_zero_out.
Variable Documentation
integer (kind=c_int), parameter, public data_catalog_entry::netcdf_file_open = 27
Definition at line 23 of file data_catalog_entry.F90.
Referenced by getvalues_dynamic_netcdf_sub(), getvalues_static_netcdf_sub(), and put_values_to_local_netcdf_sub().
integer (kind=c_int), parameter, public data_catalog_entry::netcdf_file_closed = 42
Definition at line 24 of file data_catalog_entry.F90.
Referenced by getvalues_dynamic_netcdf_sub(), getvalues_static_netcdf_sub(), initialize_netcdf_data_object_sub(), and put_values_to_local_netcdf_sub().
integer (kind=c_int), parameter, public data_catalog_entry::file_template_capitalized_monthname = 0
Definition at line 26 of file data_catalog_entry.F90.
Referenced by model_initialize::initialize_generic_grid().
integer (kind=c_int), parameter, public data_catalog_entry::file_template_lowercase_monthname = 1
Definition at line 27 of file data_catalog_entry.F90.
Referenced by model_initialize::initialize_generic_grid(), and make_filename_from_template().
integer (kind=c_int), parameter, public data_catalog_entry::file_template_uppercase_monthname = 2
Definition at line 28 of file data_catalog_entry.F90.
Referenced by model_initialize::initialize_generic_grid(), and make_filename_from_template().
integer (kind=c_int), parameter, public data_catalog_entry::missing_values_zero_out = 0
Definition at line 196 of file data_catalog_entry.F90.
Referenced by data_gridhandlemissingdata_int(), data_gridhandlemissingdata_real(), and model_initialize::initialize_generic_grid().
integer (kind=c_int), parameter, public data_catalog_entry::missing_values_replace_with_mean = 1
Definition at line 197 of file data_catalog_entry.F90.
Referenced by data_gridhandlemissingdata_int(), data_gridhandlemissingdata_real(), and model_initialize::initialize_generic_grid().
integer (kind=c_int), parameter data_catalog_entry::constant_grid = 0 private
Definition at line 199 of file data_catalog_entry.F90.
Referenced by getvalues_sub(), initialize_constant_int_data_object_sub(), and initialize_constant_real_data_object_sub().
integer (kind=c_int), parameter data_catalog_entry::static_grid = 1 private
Definition at line 200 of file data_catalog_entry.F90.
Referenced by getvalues_sub(), and initialize_gridded_data_object_sub().
integer (kind=c_int), parameter data_catalog_entry::static_netcdf_grid = 2 private
Definition at line 201 of file data_catalog_entry.F90.
Referenced by getvalues_sub().
integer (kind=c_int), parameter data_catalog_entry::dynamic_grid = 3 private
Definition at line 202 of file data_catalog_entry.F90.
Referenced by getvalues_gridded_sub(), getvalues_sub(), and initialize_gridded_data_object_sub().
integer (kind=c_int), parameter data_catalog_entry::dynamic_netcdf_grid = 4 private
Definition at line 203 of file data_catalog_entry.F90.
Referenced by getvalues_sub(), and initialize_netcdf_data_object_sub().
integer (kind=c_int), parameter data_catalog_entry::filetype_arc_ascii = 0 private
Definition at line 205 of file data_catalog_entry.F90.
Referenced by get_source_filetype_fn(), getvalues_gridded_sub(), and initialize_gridded_data_object_sub().
integer (kind=c_int), parameter data_catalog_entry::filetype_surfer = 1 private
Definition at line 206 of file data_catalog_entry.F90.
Referenced by get_source_filetype_fn(), getvalues_gridded_sub(), and initialize_gridded_data_object_sub().
integer (kind=c_int), parameter data_catalog_entry::filetype_netcdf = 2 private
Definition at line 207 of file data_catalog_entry.F90.
Referenced by get_source_filetype_fn().
integer (kind=c_int), parameter data_catalog_entry::filetype_none = 3 private
Definition at line 208 of file data_catalog_entry.F90.
Referenced by initialize_constant_int_data_object_sub(), and initialize_constant_real_data_object_sub().
type (general_grid_t), pointer, public data_catalog_entry::pgrd => null()
Definition at line 210 of file data_catalog_entry.F90.
Referenced by getvalues_gridded_sub(), model_initialize::initialize_latitude(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), nullify_pointers_sub(), and transform_grid_to_grid_sub().