SWB 2.0: runoff__curve_number Module Reference
runoff__curve_number Module Reference
Functions/Subroutines
subroutine, public runoff_curve_number_initialize (cell_is_active)
elemental integer(kind=c_int) function return_landuse_index_fn (iLanduseCode)
elemental real(kind=c_float) function prob_runoff_enhancement (fCFGI)
subroutine, public update_previous_5_day_rainfall (infil, indx)
elemental real(kind=c_float) function, public update_curve_number_fn (iLanduseIndex, iSoilsIndex, cell_index, it_is_growing_season, fSoilStorage_Max, fCFGI)
elemental real(kind=c_float) function cn_ii_to_cn_iii (CN_II)
elemental real(kind=c_float) function cn_ii_to_cn_i (CN_II)
elemental subroutine, public runoff_curve_number_calculate (runoff, curve_num_adj, cell_index, landuse_index, soil_group, it_is_growing_season, soil_storage_max, inflow, continuous_frozen_ground_index)
Calculate the runoff by means of the curve number method.
Variables
real(kind=c_float), dimension(:,:), allocatable, public cn_arciii
real(kind=c_float), dimension(:,:), allocatable, public cn_arcii
real(kind=c_float), dimension(:,:), allocatable, public cn_arci
real(kind=c_float), dimension(:,:), allocatable, public prev_5_days_rain
integer(kind=c_int), dimension(:), allocatable ilandusecodes
integer(kind=c_int) daycount
integer(kind=c_int), parameter, public five_day_sum = 6
real(kind=c_float), parameter amc_dry_growing = 1.40_c_float
real(kind=c_float), parameter amc_dry_dormant = 0.50_c_float
real(kind=c_float), parameter amc_wet_growing = 2.10_c_float
real(kind=c_float), parameter amc_wet_dormant = 1.10_c_float
type(datetime_t) date_last_updated
Function/Subroutine Documentation
subroutine, public runoff__curve_number::runoff_curve_number_initialize (logical (kind=c_bool), dimension(:,:), intent(in) cell_is_active)
Determine how many soil groups are present
Determine how many landuse codes are present
Definition at line 42 of file runoff__curve_number.F90.
References cn_arci, cn_arcii, cn_arciii, cn_ii_to_cn_i(), cn_ii_to_cn_iii(), date_last_updated, daycount, ilandusecodes, parameters::params, prev_5_days_rain, and constants_and_conversions::true.
Referenced by model_domain::model_initialize_runoff_curve_number().
elemental integer (kind=c_int) function runoff__curve_number::return_landuse_index_fn (integer (kind=c_int), intent(in) iLanduseCode) private
Definition at line 113 of file runoff__curve_number.F90.
References ilandusecodes.
elemental real (kind=c_float) function runoff__curve_number::prob_runoff_enhancement (real (kind=c_float), intent(in) fCFGI) private
Definition at line 132 of file runoff__curve_number.F90.
References continuous_frozen_ground_index::cfgi_ll, and continuous_frozen_ground_index::cfgi_ul.
Referenced by update_curve_number_fn().
subroutine, public runoff__curve_number::update_previous_5_day_rainfall (real (kind=c_float), intent(in) infil, integer (kind=c_int), intent(in) indx)
Definition at line 149 of file runoff__curve_number.F90.
References date_last_updated, daycount, five_day_sum, prev_5_days_rain, and simulation_datetime::sim_dt.
Referenced by model_domain::model_calculate_runoff_curve_number().
elemental real (kind=c_float) function, public runoff__curve_number::update_curve_number_fn (integer (kind=c_int), intent(in) iLanduseIndex, integer (kind=c_int), intent(in) iSoilsIndex, integer (kind=c_int), intent(in) cell_index, logical (kind=c_bool), intent(in) it_is_growing_season, real (kind=c_float), intent(in) fSoilStorage_Max, real (kind=c_float), intent(in) fCFGI)
Definition at line 250 of file runoff__curve_number.F90.
References amc_dry_dormant, amc_dry_growing, amc_wet_dormant, amc_wet_growing, continuous_frozen_ground_index::cfgi_ll, cn_arci, cn_arcii, cn_arciii, five_day_sum, prev_5_days_rain, and prob_runoff_enhancement().
Referenced by runoff_curve_number_calculate().
elemental real (kind=c_float) function runoff__curve_number::cn_ii_to_cn_iii (real (kind=c_float), intent(in) CN_II) private
Definition at line 330 of file runoff__curve_number.F90.
Referenced by runoff_curve_number_initialize().
elemental real (kind=c_float) function runoff__curve_number::cn_ii_to_cn_i (real (kind=c_float), intent(in) CN_II) private
Definition at line 344 of file runoff__curve_number.F90.
Referenced by runoff_curve_number_initialize().
elemental subroutine, public runoff__curve_number::runoff_curve_number_calculate (real (kind=c_float), intent(inout) runoff, real (kind=c_float), intent(inout) curve_num_adj, integer (kind=c_int), intent(in) cell_index, integer (kind=c_int), intent(in) landuse_index, integer (kind=c_int), intent(in) soil_group, logical (kind=c_bool), intent(in) it_is_growing_season, real (kind=c_float), intent(in) soil_storage_max, real (kind=c_float), intent(in) inflow, real (kind=c_float), intent(in) continuous_frozen_ground_index)
Runoff is calculated using a modification of the curve number method. Specifically, the initial abstraction is defined as 0.05 * SMax rather than the standard 0.20 * SMax of the original method. This redefinition of the initial abstraction term was found to be more appropriate for long-term continuous simulations than the standard 0.2 * SMax of the original.
Parameters
[in] iLanduseIndex Pre-configured index number corresponding to a line in the landuse lookup table.
[in] iSoilsGroup The numerical index associated with the soils group of interest.
[in] fInflow The sum of net rainfall, snowmelt, and runon from upslope cells (and possibly irrigation).
[in] fCFGI The current value of the continuous frozen-ground index.
[in] lIsGrowingSeason Logical value indicating whether dormant season or growing season criteria values are to be used when calculating runoff.
Return values
fRunoff Daily runoff calculated by means of the SCS Curve Number method.
Note
Reference: Woodward, D. E., R. H. Hawkins, R. Jiang, A. Hjelmfeldt Jr, J. Van Mullem, and Q. D. Quan. “Runoff Curve Number Method: Examination of the Initial Abstraction Ratio.” In Conference Proceeding Paper, World Water and Environmental Resources Congress, 2003.
Definition at line 384 of file runoff__curve_number.F90.
References update_curve_number_fn().
Referenced by model_domain::model_calculate_runoff_curve_number().
Variable Documentation
real (kind=c_float), dimension(:,:), allocatable, public runoff__curve_number::cn_arciii
Definition at line 16 of file runoff__curve_number.F90.
Referenced by runoff_curve_number_initialize(), and update_curve_number_fn().
real (kind=c_float), dimension(:,:), allocatable, public runoff__curve_number::cn_arcii
Definition at line 17 of file runoff__curve_number.F90.
Referenced by runoff_curve_number_initialize(), and update_curve_number_fn().
real (kind=c_float), dimension(:,:), allocatable, public runoff__curve_number::cn_arci
Definition at line 18 of file runoff__curve_number.F90.
Referenced by runoff_curve_number_initialize(), and update_curve_number_fn().
real (kind=c_float), dimension(:,:), allocatable, public runoff__curve_number::prev_5_days_rain
Definition at line 19 of file runoff__curve_number.F90.
Referenced by model_domain::model_dump_variables(), runoff_curve_number_initialize(), update_curve_number_fn(), and update_previous_5_day_rainfall().
integer (kind=c_int), dimension(:), allocatable runoff__curve_number::ilandusecodes private
Definition at line 20 of file runoff__curve_number.F90.
Referenced by return_landuse_index_fn(), and runoff_curve_number_initialize().
integer (kind=c_int) runoff__curve_number::daycount private
Definition at line 21 of file runoff__curve_number.F90.
Referenced by runoff_curve_number_initialize(), and update_previous_5_day_rainfall().
integer (kind=c_int), parameter, public runoff__curve_number::five_day_sum = 6
Definition at line 22 of file runoff__curve_number.F90.
Referenced by update_curve_number_fn(), and update_previous_5_day_rainfall().
real (kind=c_float), parameter runoff__curve_number::amc_dry_growing = 1.40_c_float private
Definition at line 32 of file runoff__curve_number.F90.
Referenced by update_curve_number_fn().
real (kind=c_float), parameter runoff__curve_number::amc_dry_dormant = 0.50_c_float private
Definition at line 33 of file runoff__curve_number.F90.
Referenced by update_curve_number_fn().
real (kind=c_float), parameter runoff__curve_number::amc_wet_growing = 2.10_c_float private
Definition at line 34 of file runoff__curve_number.F90.
Referenced by update_curve_number_fn().
real (kind=c_float), parameter runoff__curve_number::amc_wet_dormant = 1.10_c_float private
Definition at line 35 of file runoff__curve_number.F90.
Referenced by update_curve_number_fn().
type (datetime_t) runoff__curve_number::date_last_updated private
Definition at line 37 of file runoff__curve_number.F90.
Referenced by runoff_curve_number_initialize(), and update_previous_5_day_rainfall().