SWB 2.0: grid Module Reference
grid Module Reference
Provides support for input and output of gridded ASCII data, as well as for creation and destruction of grid data structures (defined types).
Data Types
type error_message_t
type general_grid_t
type grid_bounds_t
interface grid_create
interface pj_init_and_transform
interface to C code that provides a simplified entry point to PROJ4 capabilities: it has been modified so that all C pointers are kept within the C code; no pointers are returned to fortran
Functions/Subroutines
subroutine, public grid_set_output_directory_name (sDirName)
type(general_grid_t) function, pointer, public grid_createcomplete (iNX, iNY, rX0, rY0, rX1, rY1, iDataType)
Creates a grid of a specified type.
type(general_grid_t) function, pointer, public grid_createsimple (iNX, iNY, rX0, rY0, rGridCellSize, iDataType)
subroutine, public grid_destroy (pGrd)
type(general_grid_t) function, pointer, public grid_read (sFilename, sFileType, iDataType)
subroutine, public grid_readexisting (sFileName, sFileType, pGrd)
type(general_grid_t) function, pointer grid_readarcgrid_fn (sFileName, iDataType)
subroutine grid_readarcgrid_sub (sFileName, pGrd)
type(general_grid_t) function, pointer grid_readsurfergrid_fn (sFileName, iDataType)
subroutine grid_readsurfergrid_sub (sFileName, pGrd)
subroutine, public grid_writegrid (sFilename, pGrd, iOutputFormat)
subroutine, public grid_writearcgrid (sFilename, pGrd)
subroutine, public grid_writesurfergrid (sFilename, pGrd)
logical(kind=c_bool) function, public grid_conform (pGrd1, pGrd2, rTolerance)
logical(kind=c_bool) function, public grid_completelycover (pBaseGrd, pOtherGrd, rTolerance)
subroutine grid_lookupcolumn (pGrd, rXval, iBefore, iAfter, rFrac)
subroutine grid_lookuprow (pGrd, rYval, iBefore, iAfter, rFrac)
subroutine, public grid_transform (pGrd, sFromPROJ4, sToPROJ4)
Call PROJ4 to transform coordinates.
subroutine grid_checkintegergridvalues (pGrd, sFilename)
subroutine, public grid_checkforproj4error (iRetVal, sFromPROJ4, sToPROJ4)
real(kind=c_float) function, public grid_interpolate (pGrd, rXval, rYval)
real(kind=c_float) function grid_searchcolumn (pGrd, rXval, rZval, rNoData)
real(kind=c_float) function grid_lookupreal (pGrd, rXval, rYval)
integer(kind=c_int) function grid_getgridcolnum (pGrd, rX)
integer(kind=c_int) function grid_getgridrownum (pGrd, rY)
integer(kind=c_int) function, dimension(2) grid_getgridcolrownum (pGrd, rX, rY)
subroutine, public grid_set_nodata_value (pGrd, iValue, fValue)
real(kind=c_double) function grid_getgridx (pGrd, iColumnNumber)
real(kind=c_double) function grid_getgridy (pGrd, iRowNumber)
subroutine, public grid_populatexy (pGrd)
subroutine, public grid_dumpgridextent (pGrd)
integer(kind=c_int) function grid_gridtopoint_int (pGrdFrom, pGrdTo, iCol, iRow)
subroutine, public grid_gridtogrid_int (pGrdFrom, pGrdTo, lUseMajorityFilter)
subroutine, public grid_gridtogrid_sgl (pGrdFrom, pGrdTo)
integer(kind=c_int) function grid_majorityfilter_int (pGrdFrom, iTargetCol, iTargetRow, iNoDataValue, iSpread)
real(kind=c_float) function grid_convolve_sgl (pGrdFrom, iTargetCol, iTargetRow, rKernel, rNoDataValue)
Variables
integer(kind=c_int), parameter, public grid_datatype_int = 0
integer(kind=c_int), parameter, public grid_datatype_real = 1
integer(kind=c_int), parameter, public output_surfer = 0
integer(kind=c_int), parameter, public output_arc = 1
integer(kind=c_int), parameter, public grid_active_cell = 1
integer(kind=c_int), parameter nc_fill_int = -2147483647
real(kind=c_float), parameter nc_fill_float = 9.9692099683868690e+36_c_float
type(error_message_t), dimension(49) terrormessage = (/ ERROR_MESSAGE_T("no arguments in initialization list ", -1), ERROR_MESSAGE_T("no options found in 'init' file ", -2), ERROR_MESSAGE_T("no colon in init= string ", -3), ERROR_MESSAGE_T("projection not named ", -4), ERROR_MESSAGE_T("unknown projection id ", -5), ERROR_MESSAGE_T("effective eccentricity = 1. ", -6), ERROR_MESSAGE_T("unknown unit conversion id ", -7), ERROR_MESSAGE_T("invalid boolean param argument ", -8), ERROR_MESSAGE_T("unknown elliptical parameter name ", -9), ERROR_MESSAGE_T("reciprocal flattening (1/f) = 0 ", -10), ERROR_MESSAGE_T("|radius reference latitude| > 90 ", -11), ERROR_MESSAGE_T("squared eccentricity < 0 ", -12), ERROR_MESSAGE_T("major axis or radius = 0 or not given ", -13), ERROR_MESSAGE_T("latitude or longitude exceeded limits ", -14), ERROR_MESSAGE_T("invalid x or y ", -15), ERROR_MESSAGE_T("improperly formed DMS value ", -16), ERROR_MESSAGE_T("non-convergent inverse meridional dist ", -17), ERROR_MESSAGE_T("non-convergent inverse phi2 ", -18), ERROR_MESSAGE_T("acos/asin: |arg| >1.+1e-14 ", -19), ERROR_MESSAGE_T("tolerance condition error ", -20), ERROR_MESSAGE_T("conic lat_1 = -lat_2 ", -21), ERROR_MESSAGE_T("lat_1 >= 90 ", -22), ERROR_MESSAGE_T("lat_1 = 0 ", -23), ERROR_MESSAGE_T("lat_ts >= 90 ", -24), ERROR_MESSAGE_T("no distance between control points ", -25), ERROR_MESSAGE_T("projection not selected to be rotated ", -26), ERROR_MESSAGE_T("W <= 0 or M <= 0 ", -27), ERROR_MESSAGE_T("lsat not in 1-5 range ", -28), ERROR_MESSAGE_T("path not in range ", -29), ERROR_MESSAGE_T("h <= 0 ", -30), ERROR_MESSAGE_T("k <= 0 ", -31), ERROR_MESSAGE_T("lat_0 = 0 or 90 or alpha = 90 ", -32), ERROR_MESSAGE_T("lat_1=lat_2 or lat_1=0 or lat_2=90 ", -33), ERROR_MESSAGE_T("elliptical usage required ", -34), ERROR_MESSAGE_T("invalid UTM zone number ", -35), ERROR_MESSAGE_T("arg(s) out of range for Tcheby eval ", -36), ERROR_MESSAGE_T("failed to find projection to be rotated ", -37), ERROR_MESSAGE_T("failed to load datum shift file ", -38), ERROR_MESSAGE_T("both n), & m must be spec'd and > 0 ", -39), ERROR_MESSAGE_T("n <= 0, n > 1 or not specified ", -40), ERROR_MESSAGE_T("lat_1 or lat_2 not specified ", -41), ERROR_MESSAGE_T("|lat_1| == |lat_2| ", -42), ERROR_MESSAGE_T("lat_0 is pi/2 from mean lat ", -43), ERROR_MESSAGE_T("unparseable coordinate system definition ", -44), ERROR_MESSAGE_T("geocentric transformation missing z or ellps ", -45), ERROR_MESSAGE_T("unknown prime meridian conversion id ", -46), ERROR_MESSAGE_T("illegal axis orientation combination ", -47), ERROR_MESSAGE_T("point not within available datum shift grids ", -48), ERROR_MESSAGE_T("invalid sweep axis, choose x or y ", -49) /)
integer(kind=c_int), parameter four_cells = 1
integer(kind=c_int), parameter eight_cells = 2
integer(kind=c_int), parameter, private column = 1
integer(kind=c_int), parameter, private row = 2
integer(kind=c_int) lu_temp
integer(kind=c_int) lu_grid
character(len=64) output_grid_directory_name = ""
Detailed Description
Function/Subroutine Documentation
grid_set_output_directory_name()
subroutine, public grid::grid_set_output_directory_name (character (len=*), intent(in) sDirName)
Definition at line 171 of file grid.F90.
References logfiles::logs, constants_and_conversions::ltrue, and output_grid_directory_name.
Referenced by model_initialize::initialize_all().
grid_createcomplete()
type (general_grid_t) function, pointer, public grid::grid_createcomplete (integer (kind=c_int), intent(in) iNX, integer (kind=c_int), intent(in) iNY, real (kind=c_double), intent(in) rX0, real (kind=c_double), intent(in) rY0, real (kind=c_double), intent(in) rX1, real (kind=c_double), intent(in) rY1, integer (kind=c_int), intent(in) iDataType)
Creates a grid pointer object and allocates memory for the data associated with the grid (REAL, INTEGER, or T_CELL).
Parameters
iNX Number of grid cells in the x direction
iNY Number of grid cells in the y direction
rX0 X coordinate for the lower left corner of the grid
rY0 Y coordinate for the lower left corner of the grid
rX1 X coordinate for the upper right corner of the grid
rY1 Y coordinate for the upper right corner of the grid
iDataType Integer value corresponding to the type of data contained in the grid
Returns
pGrd Pointer to a grid object
Definition at line 200 of file grid.F90.
References grid_active_cell, grid_datatype_int, grid_datatype_real, constants_and_conversions::lfalse, logfiles::logs, and constants_and_conversions::rzero.
grid_createsimple()
type (general_grid_t) function, pointer, public grid::grid_createsimple (integer (kind=c_int), intent(in) iNX, integer (kind=c_int), intent(in) iNY, real (kind=c_double), intent(in) rX0, real (kind=c_double), intent(in) rY0, real (kind=c_double), intent(in) rGridCellSize, integer (kind=c_int), intent(in) iDataType)
Definition at line 287 of file grid.F90.
References grid_active_cell, grid_datatype_int, grid_datatype_real, and constants_and_conversions::lfalse.
Referenced by model_domain::initialize_grid_sub().
grid_destroy()
subroutine, public grid::grid_destroy (type (general_grid_t), pointer pGrd)
Definition at line 389 of file grid.F90.
References grid_datatype_int, grid_datatype_real, and constants_and_conversions::lfalse.
Referenced by model_initialize::create_rooting_depth_table(), data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_gridded_sub(), data_catalog_entry::getvalues_static_netcdf_sub(), model_initialize::initialize_latitude(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), model_initialize::read_polygon_id(), and routing__d8::routing_d8_determine_solution_order().
grid_read()
type (general_grid_t) function, pointer, public grid::grid_read (character (len=*), intent(in) sFilename, character (len=*), intent(in) sFileType, integer (kind=c_int), intent(in) iDataType)
Definition at line 466 of file grid.F90.
References grid_readarcgrid_fn(), grid_readsurfergrid_fn(), and constants_and_conversions::lfalse.
Referenced by data_catalog_entry::getvalues_gridded_sub().
grid_readexisting()
subroutine, public grid::grid_readexisting (character (len=*), intent(in) sFileName, character (len=*), intent(in) sFileType, type (general_grid_t), pointer pGrd)
Definition at line 489 of file grid.F90.
References grid_readarcgrid_sub(), grid_readsurfergrid_sub(), and constants_and_conversions::lfalse.
Referenced by data_catalog_entry::getvalues_gridded_sub().
grid_readarcgrid_fn()
type (general_grid_t) function, pointer grid::grid_readarcgrid_fn (character (len=*), intent(in) sFileName, integer (kind=c_int), intent(in) iDataType) private
Definition at line 533 of file grid.F90.
References constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, grid_checkintegergridvalues(), constants_and_conversions::lfalse, constants_and_conversions::ltrue, and lu_grid.
Referenced by grid_read().
grid_readarcgrid_sub()
subroutine grid::grid_readarcgrid_sub (character (len=*), intent(in) sFileName, type (general_grid_t), pointer pGrd) private
Definition at line 688 of file grid.F90.
References constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, grid_checkintegergridvalues(), constants_and_conversions::lfalse, constants_and_conversions::ltrue, and lu_grid.
Referenced by grid_readexisting().
grid_readsurfergrid_fn()
type (general_grid_t) function, pointer grid::grid_readsurfergrid_fn (character (len=*), intent(in) sFileName, integer (kind=c_int), intent(in) iDataType) private
Definition at line 852 of file grid.F90.
References constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, grid_checkintegergridvalues(), constants_and_conversions::lfalse, and lu_grid.
Referenced by grid_read().
grid_readsurfergrid_sub()
subroutine grid::grid_readsurfergrid_sub (character (len=*), intent(in) sFileName, type (general_grid_t), pointer pGrd) private
Definition at line 929 of file grid.F90.
References constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, grid_checkintegergridvalues(), constants_and_conversions::lfalse, and lu_grid.
Referenced by grid_readexisting().
grid_writegrid()
subroutine, public grid::grid_writegrid (character (len=*), intent(in) sFilename, type (general_grid_t), pointer pGrd, integer (kind=c_int) iOutputFormat)
Definition at line 1002 of file grid.F90.
References grid_writearcgrid(), grid_writesurfergrid(), output_arc, output_grid_directory_name, and output_surfer.
grid_writearcgrid()
subroutine, public grid::grid_writearcgrid (character (len=*), intent(in) sFilename, type (general_grid_t), pointer pGrd)
Definition at line 1023 of file grid.F90.
References constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, constants_and_conversions::lfalse, lu_temp, and output_grid_directory_name.
Referenced by model_initialize::create_rooting_depth_table(), grid_writegrid(), model_initialize::initialize_latitude(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), interception__gash::interception_gash_initialize(), model_initialize::read_hydrologic_soil_groups(), model_initialize::read_landuse_codes(), model_initialize::read_polygon_id(), routing__d8::routing_d8_determine_solution_order(), and routing__d8::routing_d8_initialize().
grid_writesurfergrid()
subroutine, public grid::grid_writesurfergrid (character (len=*), intent(in) sFilename, type (general_grid_t), pointer pGrd)
Definition at line 1099 of file grid.F90.
References constants_and_conversions::datatype_int, constants_and_conversions::datatype_real, constants_and_conversions::lfalse, lu_temp, and output_grid_directory_name.
Referenced by grid_writegrid().
grid_conform()
logical (kind=c_bool) function, public grid::grid_conform (type (general_grid_t), pointer pGrd1, type (general_grid_t), pointer pGrd2, real (kind=c_float), intent(in), optional rTolerance)
Definition at line 1203 of file grid.F90.
References constants_and_conversions::lfalse, logfiles::logs, and constants_and_conversions::ltrue.
grid_completelycover()
logical (kind=c_bool) function, public grid::grid_completelycover (type (general_grid_t), pointer pBaseGrd, type (general_grid_t), pointer pOtherGrd, real (kind=c_float), intent(in), optional rTolerance)
Definition at line 1267 of file grid.F90.
References constants_and_conversions::lfalse, logfiles::logs, constants_and_conversions::ltrue, and constants_and_conversions::rzero.
Referenced by data_catalog_entry::transform_grid_to_grid_sub().
grid_lookupcolumn()
subroutine grid::grid_lookupcolumn (type (general_grid_t), pointer pGrd, real (kind=c_float), intent(in) rXval, integer (kind=c_int), intent(out) iBefore, integer (kind=c_int), intent(out) iAfter, real (kind=c_float), intent(out) rFrac) private
Definition at line 1357 of file grid.F90.
References constants_and_conversions::rzero.
Referenced by grid_interpolate(), and grid_searchcolumn().
grid_lookuprow()
subroutine grid::grid_lookuprow (type (general_grid_t), pointer pGrd, real (kind=c_float), intent(in) rYval, integer (kind=c_int), intent(out) iBefore, integer (kind=c_int), intent(out) iAfter, real (kind=c_float), intent(out) rFrac) private
Definition at line 1425 of file grid.F90.
References constants_and_conversions::rzero.
Referenced by grid_interpolate().
grid_transform()
subroutine, public grid::grid_transform (type (general_grid_t), pointer pGrd, character (len=*) sFromPROJ4, character (len=*) sToPROJ4)
This subroutine calls a Fortran wrapper to the C library PROJ4. A set of input coordinates is transformed to the base SWB coordinate system.
The idea is to first create a 2D array of the X and Y coordinates in the projection system of the input data set. These coordinate values are then fed to PROJ4, which modifies the values and returns the coordinate values in the projection system of the base grid. Thereafter, mapping source to target is a matter of finding the value of the cell closest to a SWB grid coordinate pair.
Parameters
[in,out] pGrd
[in] sFromPROJ4
[in] sToPROJ4
calculate X and Y for the untransformed data
PROJ4 expects unprojected coordinates (i.e. lat lon) to be provided in RADIANS. Therefore, we convert to radians prior to the call...
If the coordinates have been converted TO latlon, convert back to degrees
Definition at line 1470 of file grid.F90.
References constants_and_conversions::degrees_to_radians, grid_checkforproj4error(), grid_populatexy(), and constants_and_conversions::radians_to_degrees.
Referenced by model_initialize::initialize_latitude(), and data_catalog_entry::transform_grid_to_grid_sub().
grid_checkintegergridvalues()
subroutine grid::grid_checkintegergridvalues (type (general_grid_t), pointer pGrd, character (len=*), intent(in) sFilename) private
Definition at line 1537 of file grid.F90.
Referenced by grid_readarcgrid_fn(), grid_readarcgrid_sub(), grid_readsurfergrid_fn(), and grid_readsurfergrid_sub().
grid_checkforproj4error()
subroutine, public grid::grid_checkforproj4error (integer (kind=c_int) iRetVal, character (len=*) sFromPROJ4, character (len=*) sToPROJ4)
Definition at line 1595 of file grid.F90.
References constants_and_conversions::lfalse, constants_and_conversions::ltrue, and terrormessage.
Referenced by data_catalog_entry::calc_project_boundaries_sub(), and grid_transform().
grid_interpolate()
real (kind=c_float) function, public grid::grid_interpolate (type (general_grid_t), pointer pGrd, real (kind=c_float), intent(in) rXval, real (kind=c_float), intent(in) rYval)
Definition at line 1658 of file grid.F90.
References grid_lookupcolumn(), and grid_lookuprow().
grid_searchcolumn()
real (kind=c_float) function grid::grid_searchcolumn (type (general_grid_t), pointer pGrd, real (kind=c_float), intent(in) rXval, real (kind=c_float), intent(in) rZval, real (kind=c_float), intent(in) rNoData) private
Definition at line 1748 of file grid.F90.
References grid_lookupcolumn().
grid_lookupreal()
real (kind=c_float) function grid::grid_lookupreal (type (general_grid_t), pointer pGrd, real (kind=c_float), intent(in) rXval, real (kind=c_float), intent(in) rYval) private
Definition at line 1884 of file grid.F90.
grid_getgridcolnum()
integer (kind=c_int) function grid::grid_getgridcolnum (type (general_grid_t), pointer pGrd, real (kind=c_double) rX) private
Definition at line 1903 of file grid.F90.
Referenced by grid_getgridcolrownum().
grid_getgridrownum()
integer (kind=c_int) function grid::grid_getgridrownum (type (general_grid_t), pointer pGrd, real (kind=c_double) rY) private
Definition at line 1939 of file grid.F90.
Referenced by grid_getgridcolrownum().
grid_getgridcolrownum()
integer (kind=c_int) function, dimension(2) grid::grid_getgridcolrownum (type (general_grid_t), pointer pGrd, real (kind=c_double) rX, real (kind=c_double) rY) private
need to ensure that whatever bound is calculated is within the declared array bounds or we get a segfault
Definition at line 1960 of file grid.F90.
References column, grid_getgridcolnum(), grid_getgridrownum(), constants_and_conversions::lfalse, constants_and_conversions::ltrue, constants_and_conversions::rbigval, and row.
Referenced by grid_gridtogrid_int(), grid_gridtogrid_sgl(), and grid_gridtopoint_int().
grid_set_nodata_value()
subroutine, public grid::grid_set_nodata_value (type (general_grid_t), pointer pGrd, integer (kind=c_int), intent(in), optional iValue, real (kind=c_float), intent(in), optional fValue)
Definition at line 2064 of file grid.F90.
grid_getgridx()
real (kind=c_double) function grid::grid_getgridx (type (general_grid_t), pointer pGrd, integer (kind=c_int) iColumnNumber) private
Definition at line 2074 of file grid.F90.
Referenced by grid_populatexy().
grid_getgridy()
real (kind=c_double) function grid::grid_getgridy (type (general_grid_t), pointer pGrd, integer (kind=c_int) iRowNumber) private
Definition at line 2086 of file grid.F90.
Referenced by grid_populatexy().
grid_populatexy()
subroutine, public grid::grid_populatexy (type (general_grid_t), pointer pGrd)
Definition at line 2099 of file grid.F90.
References grid_getgridx(), and grid_getgridy().
Referenced by grid_gridtogrid_int(), grid_gridtogrid_sgl(), grid_gridtopoint_int(), grid_transform(), and model_initialize::initialize_latitude().
grid_dumpgridextent()
subroutine, public grid::grid_dumpgridextent (type (general_grid_t), pointer pGrd)
Definition at line 2135 of file grid.F90.
References logfiles::logs.
Referenced by data_catalog_entry::dump_data_structure_sub().
grid_gridtopoint_int()
integer (kind=c_int) function grid::grid_gridtopoint_int (type (general_grid_t), pointer pGrdFrom, type (general_grid_t), pointer pGrdTo, integer (kind=c_int), intent(in) iCol, integer (kind=c_int), intent(in) iRow) private
Todo:
check the logic here...intent is to ensure that the majority filter is searching an area that adequately covers corresponding gridcell areas
Definition at line 2168 of file grid.F90.
References column, exceptions::die(), grid_getgridcolrownum(), grid_majorityfilter_int(), grid_populatexy(), and row.
grid_gridtogrid_int()
subroutine, public grid::grid_gridtogrid_int (type (general_grid_t), pointer pGrdFrom, type (general_grid_t), pointer pGrdTo, logical (kind=c_bool), intent(in) lUseMajorityFilter)
Definition at line 2214 of file grid.F90.
References column, grid_getgridcolrownum(), grid_majorityfilter_int(), grid_populatexy(), logfiles::logs, constants_and_conversions::ltrue, and row.
Referenced by data_catalog_entry::transform_grid_to_grid_sub().
grid_gridtogrid_sgl()
subroutine, public grid::grid_gridtogrid_sgl (type (general_grid_t), pointer pGrdFrom, type (general_grid_t), pointer pGrdTo)
Definition at line 2293 of file grid.F90.
References column, grid_getgridcolrownum(), grid_populatexy(), and row.
Referenced by data_catalog_entry::transform_grid_to_grid_sub().
grid_majorityfilter_int()
integer (kind=c_int) function grid::grid_majorityfilter_int (type (general_grid_t), pointer pGrdFrom, integer (kind=c_int) iTargetCol, integer (kind=c_int) iTargetRow, integer (kind=c_int) iNoDataValue, integer (kind=c_int) iSpread) private
Definition at line 2349 of file grid.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
Referenced by grid_gridtogrid_int(), and grid_gridtopoint_int().
grid_convolve_sgl()
real (kind=c_float) function grid::grid_convolve_sgl (type (general_grid_t), pointer pGrdFrom, integer (kind=c_int) iTargetCol, integer (kind=c_int) iTargetRow, real (kind=c_float), dimension(:,:) rKernel, real (kind=c_float), optional rNoDataValue) private
Definition at line 2408 of file grid.F90.
References constants_and_conversions::rzero.
Variable Documentation
grid_datatype_int
integer (kind=c_int), parameter, public grid::grid_datatype_int = 0
Definition at line 19 of file grid.F90.
Referenced by data_catalog_entry::getvalues_gridded_sub(), grid_createcomplete(), grid_createsimple(), grid_destroy(), and data_catalog_entry::transform_grid_to_grid_sub().
grid_datatype_real
integer (kind=c_int), parameter, public grid::grid_datatype_real = 1
Definition at line 20 of file grid.F90.
Referenced by model_initialize::create_rooting_depth_table(), data_catalog_entry::getvalues_gridded_sub(), grid_createcomplete(), grid_createsimple(), grid_destroy(), model_domain::initialize_grid_sub(), model_initialize::initialize_latitude(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), model_initialize::read_polygon_id(), and data_catalog_entry::transform_grid_to_grid_sub().
output_surfer
integer (kind=c_int), parameter, public grid::output_surfer = 0
Definition at line 24 of file grid.F90.
Referenced by grid_writegrid().
output_arc
integer (kind=c_int), parameter, public grid::output_arc = 1
Definition at line 25 of file grid.F90.
Referenced by grid_writegrid().
grid_active_cell
integer (kind=c_int), parameter, public grid::grid_active_cell = 1
Definition at line 27 of file grid.F90.
Referenced by grid_createcomplete(), and grid_createsimple().
nc_fill_int
integer(kind=c_int), parameter grid::nc_fill_int = -2147483647 private
Definition at line 28 of file grid.F90.
nc_fill_float
real(kind=c_float), parameter grid::nc_fill_float = 9.9692099683868690e+36_c_float private
Definition at line 29 of file grid.F90.
Referenced by model_domain::initialize_grid_sub().
terrormessage
type(error_message_t), dimension(49) grid::terrormessage = (/ ERROR_MESSAGE_T("no arguments in initialization list ", -1), ERROR_MESSAGE_T("no options found in 'init' file ", -2), ERROR_MESSAGE_T("no colon in init= string ", -3), ERROR_MESSAGE_T("projection not named ", -4), ERROR_MESSAGE_T("unknown projection id ", -5), ERROR_MESSAGE_T("effective eccentricity = 1. ", -6), ERROR_MESSAGE_T("unknown unit conversion id ", -7), ERROR_MESSAGE_T("invalid boolean param argument ", -8), ERROR_MESSAGE_T("unknown elliptical parameter name ", -9), ERROR_MESSAGE_T("reciprocal flattening (1/f) = 0 ", -10), ERROR_MESSAGE_T("|radius reference latitude| > 90 ", -11), ERROR_MESSAGE_T("squared eccentricity < 0 ", -12), ERROR_MESSAGE_T("major axis or radius = 0 or not given ", -13), ERROR_MESSAGE_T("latitude or longitude exceeded limits ", -14), ERROR_MESSAGE_T("invalid x or y ", -15), ERROR_MESSAGE_T("improperly formed DMS value ", -16), ERROR_MESSAGE_T("non-convergent inverse meridional dist ", -17), ERROR_MESSAGE_T("non-convergent inverse phi2 ", -18), ERROR_MESSAGE_T("acos/asin: |arg| >1.+1e-14 ", -19), ERROR_MESSAGE_T("tolerance condition error ", -20), ERROR_MESSAGE_T("conic lat_1 = -lat_2 ", -21), ERROR_MESSAGE_T("lat_1 >= 90 ", -22), ERROR_MESSAGE_T("lat_1 = 0 ", -23), ERROR_MESSAGE_T("lat_ts >= 90 ", -24), ERROR_MESSAGE_T("no distance between control points ", -25), ERROR_MESSAGE_T("projection not selected to be rotated ", -26), ERROR_MESSAGE_T("W <= 0 or M <= 0 ", -27), ERROR_MESSAGE_T("lsat not in 1-5 range ", -28), ERROR_MESSAGE_T("path not in range ", -29), ERROR_MESSAGE_T("h <= 0 ", -30), ERROR_MESSAGE_T("k <= 0 ", -31), ERROR_MESSAGE_T("lat_0 = 0 or 90 or alpha = 90 ", -32), ERROR_MESSAGE_T("lat_1=lat_2 or lat_1=0 or lat_2=90 ", -33), ERROR_MESSAGE_T("elliptical usage required ", -34), ERROR_MESSAGE_T("invalid UTM zone number ", -35), ERROR_MESSAGE_T("arg(s) out of range for Tcheby eval ", -36), ERROR_MESSAGE_T("failed to find projection to be rotated ", -37), ERROR_MESSAGE_T("failed to load datum shift file ", -38), ERROR_MESSAGE_T("both n), & m must be spec'd and > 0 ", -39), ERROR_MESSAGE_T("n <= 0, n > 1 or not specified ", -40), ERROR_MESSAGE_T("lat_1 or lat_2 not specified ", -41), ERROR_MESSAGE_T("|lat_1| == |lat_2| ", -42), ERROR_MESSAGE_T("lat_0 is pi/2 from mean lat ", -43), ERROR_MESSAGE_T("unparseable coordinate system definition ", -44), ERROR_MESSAGE_T("geocentric transformation missing z or ellps ", -45), ERROR_MESSAGE_T("unknown prime meridian conversion id ", -46), ERROR_MESSAGE_T("illegal axis orientation combination ", -47), ERROR_MESSAGE_T("point not within available datum shift grids ", -48), ERROR_MESSAGE_T("invalid sweep axis, choose x or y ", -49) /) private
Definition at line 91 of file grid.F90.
Referenced by grid_checkforproj4error().
four_cells
integer (kind=c_int), parameter grid::four_cells = 1 private
Definition at line 156 of file grid.F90.
eight_cells
integer (kind=c_int), parameter grid::eight_cells = 2 private
Definition at line 157 of file grid.F90.
column
integer (kind=c_int), parameter, private grid::column = 1 private
Definition at line 159 of file grid.F90.
Referenced by grid_getgridcolrownum(), grid_gridtogrid_int(), grid_gridtogrid_sgl(), grid_gridtopoint_int(), netcdf4_support::netcdf_coord_to_col_row(), and netcdf4_support::netcdf_open_and_prepare_as_input().
row
integer (kind=c_int), parameter, private grid::row = 2 private
Definition at line 160 of file grid.F90.
Referenced by grid_getgridcolrownum(), grid_gridtogrid_int(), grid_gridtogrid_sgl(), grid_gridtopoint_int(), netcdf4_support::netcdf_coord_to_col_row(), and netcdf4_support::netcdf_open_and_prepare_as_input().
lu_temp
integer (kind=c_int) grid::lu_temp private
Todo:
change these global (module) variables to local variables
Definition at line 163 of file grid.F90.
Referenced by grid_writearcgrid(), and grid_writesurfergrid().
lu_grid
integer (kind=c_int) grid::lu_grid private
Definition at line 163 of file grid.F90.
Referenced by grid_readarcgrid_fn(), grid_readarcgrid_sub(), grid_readsurfergrid_fn(), and grid_readsurfergrid_sub().
output_grid_directory_name
character (len=64) grid::output_grid_directory_name = "" private
Definition at line 165 of file grid.F90.
Referenced by grid_set_output_directory_name(), grid_writearcgrid(), grid_writegrid(), and grid_writesurfergrid().