SWB 2.0: file_utilities Module Reference
file_utilities Module Reference
Data Types
interface c_chdir
interface c_execv
interface c_get_libc_err_string
interface c_get_libc_errno
interface c_getcwd
interface c_mkdir
interface c_remove
interface c_rmdir
interface c_unlink
Functions/Subroutines
subroutine execv (filename, argv, err)
subroutine get_libc_err_string (libc_err_string, libc_err_code)
subroutine mkdir (dirname, err)
subroutine chdir (dirname, err)
subroutine rmdir (dirname, err)
subroutine remove (filename, err)
subroutine get_cwd (dirname)
character(kind=c_char, len=:) function, allocatable getcwd ()
subroutine unlink (filename, err)
integer function get_libc_errno ()
Function/Subroutine Documentation
execv()
subroutine file_utilities::execv (character(*), intent(in) filename, character(len=*), dimension(:), intent(in) argv, integer, intent(out), optional err)
Definition at line 78 of file file_utilities.F90.
get_libc_err_string()
subroutine file_utilities::get_libc_err_string (character (len=:), intent(out), allocatable libc_err_string, integer, intent(in) libc_err_code)
Definition at line 112 of file file_utilities.F90.
Referenced by mkdir().
mkdir()
subroutine file_utilities::mkdir (character(*) dirname, integer, intent(out), optional err)
Definition at line 146 of file file_utilities.F90.
References get_libc_err_string(), and get_libc_errno().
chdir()
subroutine file_utilities::chdir (character(*) dirname, integer, intent(out), optional err)
Definition at line 172 of file file_utilities.F90.
References get_libc_errno().
rmdir()
subroutine file_utilities::rmdir (character(*) dirname, integer, intent(out), optional err)
Definition at line 196 of file file_utilities.F90.
References get_libc_errno().
remove()
subroutine file_utilities::remove (character(*) filename, integer, intent(out), optional err)
Definition at line 220 of file file_utilities.F90.
References get_libc_errno().
get_cwd()
subroutine file_utilities::get_cwd (character(kind=c_char,len=:), intent(out), allocatable dirname)
Definition at line 244 of file file_utilities.F90.
References constants_and_conversions::c_to_fortran_string().
getcwd()
character(kind=c_char,len=:) function, allocatable file_utilities::getcwd ()
Definition at line 262 of file file_utilities.F90.
References constants_and_conversions::c_to_fortran_string().
unlink()
subroutine file_utilities::unlink (character(*) filename, integer, intent(out), optional err)
Definition at line 277 of file file_utilities.F90.
References get_libc_errno().
get_libc_errno()
integer function file_utilities::get_libc_errno ()
Definition at line 301 of file file_utilities.F90.
Referenced by chdir(), mkdir(), remove(), rmdir(), and unlink().