SWB 2.0: runoff__gridded_values Module Reference
runoff__gridded_values Module Reference
Module runoff__gridded_values provides support for estimating fog drip given a gridded map of RUNOFF_ZONE, and a table containing monthly fog factors.
Functions/Subroutines
subroutine, public runoff_gridded_values_initialize (lActive)
Initialize the infiltration grid.
subroutine read_runoff_ratio_table (sFilename)
subroutine, public runoff_gridded_values_update_ratios ()
Variables
real(kind=c_float), dimension(:,:), allocatable runoff_table_values
type(datetime_t), dimension(:), allocatable runoff_table_dates
type(data_catalog_entry_t), pointer prunoff_zone
integer(kind=c_int), dimension(:), allocatable runoff_zone
real(kind=c_float), dimension(:), allocatable, public runoff_ratios
Detailed Description
Function/Subroutine Documentation
subroutine, public runoff__gridded_values::runoff_gridded_values_initialize (logical (kind=c_bool), dimension(:,:), intent(in) lActive)
Read in a runoff zone grid.
Definition at line 44 of file runoff__gridded_values.F90.
References dictionary::cf_dict, data_catalog::dat, exceptions::die(), prunoff_zone, read_runoff_ratio_table(), runoff_ratios, and runoff_zone.
Referenced by model_domain::model_initialize_runoff_gridded_values().
subroutine runoff__gridded_values::read_runoff_ratio_table (character (len=*), intent(in) sFilename) private
Definition at line 79 of file runoff__gridded_values.F90.
References exceptions::die(), constants_and_conversions::false, runoff_table_dates, and runoff_table_values.
Referenced by runoff_gridded_values_initialize().
subroutine, public runoff__gridded_values::runoff_gridded_values_update_ratios ()
Definition at line 160 of file runoff__gridded_values.F90.
References exceptions::die(), constants_and_conversions::lfalse, constants_and_conversions::ltrue, runoff_ratios, runoff_table_dates, runoff_table_values, runoff_zone, and simulation_datetime::sim_dt.
Referenced by model_domain::model_calculate_runoff_gridded_values(), and model_domain::model_initialize_runoff_gridded_values().
Variable Documentation
real (kind=c_float), dimension(:,:), allocatable runoff__gridded_values::runoff_table_values private
Definition at line 29 of file runoff__gridded_values.F90.
Referenced by read_runoff_ratio_table(), and runoff_gridded_values_update_ratios().
type (datetime_t), dimension(:), allocatable runoff__gridded_values::runoff_table_dates private
Definition at line 30 of file runoff__gridded_values.F90.
Referenced by read_runoff_ratio_table(), and runoff_gridded_values_update_ratios().
type (data_catalog_entry_t), pointer runoff__gridded_values::prunoff_zone private
Definition at line 32 of file runoff__gridded_values.F90.
Referenced by runoff_gridded_values_initialize().
integer (kind=c_int), dimension(:), allocatable runoff__gridded_values::runoff_zone private
Definition at line 33 of file runoff__gridded_values.F90.
Referenced by runoff_gridded_values_initialize(), and runoff_gridded_values_update_ratios().
real (kind=c_float), dimension(:), allocatable, public runoff__gridded_values::runoff_ratios
Definition at line 35 of file runoff__gridded_values.F90.
Referenced by model_domain::model_calculate_runoff_gridded_values(), runoff_gridded_values_initialize(), and runoff_gridded_values_update_ratios().