SWB 2.0: awc__depth_integrated Module Reference
awc__depth_integrated Module Reference
Populate the available water content by reading in and depth-averaging soil available water contents over multiple soil horizons.
Functions/Subroutines
subroutine, public awc_depth_integrated_read (fRooting_Depth)
subroutine, public awc_depth_integrated_initialize (lActive, fAWC, iSoils_Code)
Variables
type(data_catalog_entry_t), pointer psoils_code_grid
real(kind=c_float), dimension(:,:), allocatable, public available_water_content
Detailed Description
Function/Subroutine Documentation
awc_depth_integrated_read()
subroutine, public awc__depth_integrated::awc_depth_integrated_read (real (kind=c_float), dimension(:,:), intent(inout) fRooting_Depth)
Todo:
Need a LOT more data validation and guard code here to prevent execution in the case where only some data fields are found, or are only partially populated.
Definition at line 33 of file awc__depth_integrated.F90.
References available_water_content, data_catalog::dat, constants_and_conversions::lfalse, constants_and_conversions::ltrue, parameters::params, and psoils_code_grid.
Referenced by model_domain::model_read_available_water_content_depth_integrated().
awc_depth_integrated_initialize()
subroutine, public awc__depth_integrated::awc_depth_integrated_initialize (logical (kind=c_bool), dimension(:,:), intent(in) lActive, real (kind=c_float), dimension(:), intent(inout) fAWC, integer (kind=c_int), dimension(:), intent(inout) iSoils_Code)
Definition at line 275 of file awc__depth_integrated.F90.
References available_water_content, and psoils_code_grid.
Referenced by model_domain::model_initialize_available_water_content_depth_integrated().
Variable Documentation
psoils_code_grid
type (data_catalog_entry_t), pointer awc__depth_integrated::psoils_code_grid private
Definition at line 27 of file awc__depth_integrated.F90.
Referenced by awc_depth_integrated_initialize(), and awc_depth_integrated_read().
available_water_content
real (kind=c_float), dimension(:,:), allocatable, public awc__depth_integrated::available_water_content
Definition at line 28 of file awc__depth_integrated.F90.
Referenced by awc_depth_integrated_initialize(), awc_depth_integrated_read(), and model_domain::set_inactive_cells_sub().