SWB 2.0: file_operations Module Reference
file_operations Module Reference
Data Types
type ascii_file_t
Functions/Subroutines
integer(kind=c_int) function return_num_lines_fn (this)
integer(kind=c_int) function return_num_records_fn (this)
integer(kind=c_int) function return_current_linenum_fn (this)
logical(kind=c_bool) function have_we_reached_the_eof_fn (this)
logical(kind=c_bool) function is_current_line_a_comment_fn (this)
subroutine open_file_read_access_sub (this, sFilename, sCommentChars, sDelimiters, lHasHeader)
subroutine open_file_write_access_sub (this, sFilename, lQuiet)
subroutine close_file_sub (this)
logical(kind=c_bool) function does_file_exist_fn (this, sFilename)
logical(kind=c_bool) function is_file_open_fn (this)
subroutine count_number_of_lines_sub (this)
type(string_list_t) function read_header_fn (this)
subroutine write_line_of_data_sub (this, sText)
character(len=:) function, allocatable read_line_of_data_fn (this)
character(len=:) function, allocatable, public fully_qualified_filename (filename)
Variables
integer(kind=c_int), parameter max_str_len = 65536
Function/Subroutine Documentation
integer (kind=c_int) function file_operations::return_num_lines_fn (class (ascii_file_t) this)
Definition at line 84 of file file_operations.F90.
integer (kind=c_int) function file_operations::return_num_records_fn (class (ascii_file_t) this) private
Definition at line 95 of file file_operations.F90.
integer (kind=c_int) function file_operations::return_current_linenum_fn (class (ascii_file_t) this) private
Definition at line 106 of file file_operations.F90.
logical (kind=c_bool) function file_operations::have_we_reached_the_eof_fn (class (ascii_file_t) this) private
Definition at line 117 of file file_operations.F90.
logical (kind=c_bool) function file_operations::is_current_line_a_comment_fn (class (ascii_file_t) this) private
Definition at line 128 of file file_operations.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
subroutine file_operations::open_file_read_access_sub (class (ascii_file_t), intent(inout) this, character (len=*), intent(in) sFilename, character (len=*), intent(in) sCommentChars, character (len=*), intent(in) sDelimiters, logical (kind=c_bool), intent(in), optional lHasHeader) private
Definition at line 152 of file file_operations.F90.
References exceptions::die(), fully_qualified_filename(), constants_and_conversions::lfalse, logfiles::logs, and constants_and_conversions::ltrue.
subroutine file_operations::open_file_write_access_sub (class (ascii_file_t), intent(inout) this, character (len=*), intent(in) sFilename, logical (kind=c_bool), intent(in), optional lQuiet) private
Definition at line 195 of file file_operations.F90.
References constants_and_conversions::lfalse, logfiles::logs, and constants_and_conversions::ltrue.
subroutine file_operations::close_file_sub (class (ascii_file_t) this) private
Definition at line 231 of file file_operations.F90.
References constants_and_conversions::lfalse.
logical(kind=c_bool) function file_operations::does_file_exist_fn (class (ascii_file_t) this, character (len=*), intent(in) sFilename) private
Definition at line 242 of file file_operations.F90.
References fully_qualified_filename().
logical(kind=c_bool) function file_operations::is_file_open_fn (class (ascii_file_t) this) private
Definition at line 254 of file file_operations.F90.
subroutine file_operations::count_number_of_lines_sub (class (ascii_file_t), intent(inout) this) private
Definition at line 265 of file file_operations.F90.
type (string_list_t) function file_operations::read_header_fn (class (ascii_file_t), intent(inout) this) private
Definition at line 306 of file file_operations.F90.
References constants_and_conversions::sdouble_quote.
subroutine file_operations::write_line_of_data_sub (class (ascii_file_t), intent(inout) this, character (len=*), intent(in) sText) private
Definition at line 333 of file file_operations.F90.
References fully_qualified_filename().
character (len=:) function, allocatable file_operations::read_line_of_data_fn (class (ascii_file_t), intent(inout) this) private
Definition at line 355 of file file_operations.F90.
References constants_and_conversions::ltrue.
character(len=:) function, allocatable, public file_operations::fully_qualified_filename (character(len=*), intent(in) filename)
Definition at line 391 of file file_operations.F90.
References constants_and_conversions::data_directory_name.
Referenced by does_file_exist_fn(), data_catalog_entry::initialize_gridded_data_object_sub(), data_catalog_entry::initialize_netcdf_data_object_sub(), open_file_read_access_sub(), and write_line_of_data_sub().
Variable Documentation
integer (kind=c_int), parameter file_operations::max_str_len = 65536 private
Definition at line 16 of file file_operations.F90.