SWB 2.0: datetime Module Reference
datetime Module Reference
This module contains the DATETIME_T class and associated time and date-related routines, along with the MONTH_T class which defines month names and three-letter abbreviations.
Data Types
type datetime_t
type month_t
Container for month name and length information.
Functions/Subroutines
subroutine set_default_date_format (sDateFormat)
subroutine set_default_time_format (sTimeFormat)
subroutine set_date_format_indices (this, sDateFormat)
subroutine set_time_format_indices (this, sTimeFormat)
subroutine parse_text_to_date_sub (this, sString, sFilename, iLinenumber)
subroutine parse_text_to_time_sub (this, sString)
subroutine calc_water_year_sub (this)
subroutine calc_julian_day_sub (this, iMonth, iDay, iYear, iHour, iMinute, iSecond)
elemental subroutine calc_gregorian_date_sub (this)
elemental subroutine, public gregorian_date (iJD, iYear, iMonth, iDay, iOrigin)
integer(kind=c_int) function, public julian_day (iYear, iMonth, iDay, iOrigin)
elemental logical(kind=c_bool) function is_date_greater_than (date1, date2)
elemental logical(kind=c_bool) function is_date_less_than (date1, date2)
elemental logical(kind=c_bool) function is_date_lt_or_equal_to (date1, date2)
elemental logical(kind=c_bool) function is_date_gt_or_equal_to (date1, date2)
elemental logical(kind=c_bool) function is_date_equal_to (date1, date2)
elemental real(kind=c_double) function date_minus_date_fn (date1, date2)
elemental type(datetime_t) function, allocatable date_plus_float_fn (date1, fValue)
elemental type(datetime_t) function, allocatable date_minus_float_fn (date1, fValue)
elemental type(datetime_t) function, allocatable date_minus_int_fn (date1, iValue)
character(len=20) function write_pretty_datetime_fn (this)
character(len=10) function write_pretty_date_fn (this)
character(len=10) function write_list_date_fn (this)
character(len=8) function write_list_time_fn (this)
character(len=19) function write_list_datetime_fn (this)
subroutine system_time_to_date_sub (this)
elemental subroutine set_julian_date_sub (this, dValue)
Return the number of days in the given year.
elemental integer(kind=c_int) function get_julian_day_fn (this)
elemental real(kind=c_double) function get_fraction_of_day_fn (this)
integer(kind=c_int) function get_days_in_month_fn (this)
integer(kind=c_int) function get_days_in_year_fn (this)
subroutine date_plus_year_sub (this)
subroutine date_set_day_sub (this, newday)
subroutine date_set_month_sub (this, newmonth)
subroutine date_set_year_sub (this, newyear)
subroutine date_minus_year_sub (this)
subroutine date_plus_day_sub (this)
subroutine date_minus_day_sub (this)
logical(kind=c_bool) function is_leap_year_fn (this)
integer(kind=c_int) function mmddyyyy2julian (sMMDDYYYY)
integer(kind=c_int) function, public mmdd2doy (sMMDD)
integer(kind=c_int) function mmddyyyy2doy (sMMDDYYYY)
integer(kind=c_int) function get_day_of_year_fn (this)
integer(kind=c_int) function, public day_of_year (iJD)
logical(kind=c_bool) function, public isleap (iYear)
Variables
character(len=14), private sdate_format = "MM/DD/YYYY"
character(len=14), public sdefault_date_format = "MM/DD/YYYY"
integer(kind=c_int), private iscanmm1 = 1
integer(kind=c_int), private iscanmm2 = 2
integer(kind=c_int), private iscandelim1 = 3
integer(kind=c_int), private iscandd1 = 4
integer(kind=c_int), private iscandd2 = 5
integer(kind=c_int), private iscandelim2 = 6
integer(kind=c_int), private iscanyyyy1 = 7
integer(kind=c_int), private iscanyyyy2 = 10
character(len=14), private stime_format = "HH:MM:SS"
character(len=14), public sdefault_time_format = "HH:MM:SS"
integer(kind=c_int), private iscanhour1 = 1
integer(kind=c_int), private iscanhour2 = 2
integer(kind=c_int), private iscanmin1 = 4
integer(kind=c_int), private iscanmin2 = 5
integer(kind=c_int), private iscansec1 = 7
integer(kind=c_int), private iscansec2 = 8
type(month_t), dimension(12), target, public months = [ MONTH_T('Jan','January ', 1, 31, 1, 31), MONTH_T('Feb','February ', 32, 59, 2, 29), MONTH_T('Mar','March ', 60, 90, 3, 31), MONTH_T('Apr','April ', 91, 120, 4, 30), MONTH_T('May','May ', 121, 151, 5, 31), MONTH_T('Jun','June ', 152, 181, 6, 30), MONTH_T('Jul','July ', 182, 212, 7, 31), MONTH_T('Aug','August ', 213, 243, 8, 31), MONTH_T('Sep','September', 244, 273, 9, 30), MONTH_T('Oct','October ', 274, 304, 10, 31), MONTH_T('Nov','November ', 305, 334, 11, 30), MONTH_T('Dec','December ', 335, 365, 12, 31) ]
Month information.
Detailed Description
Function/Subroutine Documentation
subroutine datetime::set_default_date_format (character (len=*), intent(in) sDateFormat) private
Definition at line 152 of file datetime.F90.
References sdefault_date_format.
subroutine datetime::set_default_time_format (character (len=*), intent(in) sTimeFormat) private
Definition at line 162 of file datetime.F90.
References sdefault_time_format.
subroutine datetime::set_date_format_indices (class (datetime_t), intent(inout) this, character (len=*), intent(in), optional sDateFormat) private
Definition at line 172 of file datetime.F90.
References iscandd1, iscandd2, iscandelim1, iscandelim2, iscanmm1, iscanmm2, iscanyyyy1, iscanyyyy2, constants_and_conversions::ltrue, sdate_format, and sdefault_date_format.
subroutine datetime::set_time_format_indices (class (datetime_t), intent(inout) this, character (len=*), intent(in), optional sTimeFormat) private
Definition at line 212 of file datetime.F90.
References iscanhour1, iscanhour2, iscanmin1, iscanmin2, iscansec1, iscansec2, constants_and_conversions::ltrue, and stime_format.
subroutine datetime::parse_text_to_date_sub (class (datetime_t), intent(inout) this, character (len=*), intent(in) sString, character (len=*), intent(in), optional sFilename, integer (kind=c_int), intent(in), optional iLinenumber) private
Definition at line 244 of file datetime.F90.
References iscandd1, iscandd2, iscanmm1, iscanmm2, iscanyyyy1, iscanyyyy2, julian_day(), and constants_and_conversions::lfalse.
subroutine datetime::parse_text_to_time_sub (class (datetime_t), intent(inout) this, character (len=*), intent(in) sString) private
Definition at line 334 of file datetime.F90.
References iscanhour1, iscanhour2, iscanmin1, iscanmin2, iscansec1, and iscansec2.
subroutine datetime::calc_water_year_sub (class (datetime_t) this) private
Definition at line 395 of file datetime.F90.
subroutine datetime::calc_julian_day_sub (class (datetime_t) this, integer (kind=c_int), intent(in), optional iMonth, integer (kind=c_int), intent(in), optional iDay, integer (kind=c_int), intent(in), optional iYear, integer (kind=c_int), intent(in), optional iHour, integer (kind=c_int), intent(in), optional iMinute, integer (kind=c_int), intent(in), optional iSecond) private
Definition at line 457 of file datetime.F90.
elemental subroutine datetime::calc_gregorian_date_sub (class (datetime_t), intent(inout) this) private
Definition at line 487 of file datetime.F90.
References gregorian_date().
elemental subroutine, public datetime::gregorian_date (integer (kind=c_int), value iJD, integer (kind=c_int), intent(inout) iYear, integer (kind=c_int), intent(inout) iMonth, integer (kind=c_int), intent(inout) iDay, integer (kind=c_int), intent(in), optional iOrigin)
Definition at line 553 of file datetime.F90.
Referenced by calc_gregorian_date_sub(), and day_of_year().
integer (kind=c_int) function, public datetime::julian_day (integer (kind=c_int), intent(in) iYear, integer (kind=c_int), intent(in) iMonth, integer (kind=c_int), intent(in) iDay, integer (kind=c_int), optional iOrigin)
Definition at line 623 of file datetime.F90.
References constants_and_conversions::lfalse.
Referenced by day_of_year(), mmdd2doy(), mmddyyyy2doy(), mmddyyyy2julian(), netcdf4_support::nf_calculate_time_range(), and parse_text_to_date_sub().
elemental logical(kind=c_bool) function datetime::is_date_greater_than (class(datetime_t), intent(in) date1, class(datetime_t), intent(in) date2) private
Definition at line 664 of file datetime.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
elemental logical(kind=c_bool) function datetime::is_date_less_than (class(datetime_t), intent(in) date1, class(datetime_t), intent(in) date2) private
Definition at line 687 of file datetime.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
elemental logical(kind=c_bool) function datetime::is_date_lt_or_equal_to (class (datetime_t), intent(in) date1, type (datetime_t), intent(in) date2) private
Definition at line 710 of file datetime.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
elemental logical(kind=c_bool) function datetime::is_date_gt_or_equal_to (class (datetime_t), intent(in) date1, type (datetime_t), intent(in) date2) private
Definition at line 726 of file datetime.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
elemental logical(kind=c_bool) function datetime::is_date_equal_to (class(datetime_t), intent(in) date1, class(datetime_t), intent(in) date2) private
Definition at line 742 of file datetime.F90.
References constants_and_conversions::lfalse, and constants_and_conversions::ltrue.
elemental real (kind=c_double) function datetime::date_minus_date_fn (class(datetime_t), intent(in) date1, class(datetime_t), intent(in) date2) private
Definition at line 765 of file datetime.F90.
elemental type(datetime_t) function, allocatable datetime::date_plus_float_fn (class(datetime_t), intent(in) date1, real (kind=c_float), intent(in) fValue) private
Definition at line 777 of file datetime.F90.
elemental type(datetime_t) function, allocatable datetime::date_minus_float_fn (class(datetime_t), intent(in) date1, real (kind=c_float), intent(in) fValue) private
Definition at line 791 of file datetime.F90.
elemental type(datetime_t) function, allocatable datetime::date_minus_int_fn (class(datetime_t), intent(in) date1, integer (kind=c_int), intent(in) iValue) private
Definition at line 805 of file datetime.F90.
character (len=20) function datetime::write_pretty_datetime_fn (class(datetime_t) this) private
Definition at line 819 of file datetime.F90.
References months.
character (len=10) function datetime::write_pretty_date_fn (class(datetime_t) this) private
Definition at line 831 of file datetime.F90.
character (len=10) function datetime::write_list_date_fn (class(datetime_t) this) private
Definition at line 843 of file datetime.F90.
References iscandd1, iscandd2, iscandelim1, iscandelim2, iscanmm1, iscanmm2, iscanyyyy1, iscanyyyy2, and sdate_format.
character (len=8) function datetime::write_list_time_fn (class(datetime_t) this) private
Definition at line 870 of file datetime.F90.
character (len=19) function datetime::write_list_datetime_fn (class(datetime_t) this) private
Definition at line 881 of file datetime.F90.
References iscandd1, iscandd2, iscandelim1, iscandelim2, iscanmm1, iscanmm2, iscanyyyy1, iscanyyyy2, and sdate_format.
subroutine datetime::system_time_to_date_sub (class (datetime_t) this) private
Definition at line 951 of file datetime.F90.
elemental subroutine datetime::set_julian_date_sub (class (datetime_t), intent(inout) this, real (kind=c_double), intent(out) dValue) private
This function simply returns the number of days given the current year.
Definition at line 1057 of file datetime.F90.
elemental integer (kind=c_int) function datetime::get_julian_day_fn (class(datetime_t), intent(in) this) private
Definition at line 1070 of file datetime.F90.
elemental real (kind=c_double) function datetime::get_fraction_of_day_fn (class(datetime_t), intent(in) this) private
Definition at line 1081 of file datetime.F90.
integer (kind=c_int) function datetime::get_days_in_month_fn (class(datetime_t) this) private
Definition at line 1092 of file datetime.F90.
integer (kind=c_int) function datetime::get_days_in_year_fn (class(datetime_t) this) private
Definition at line 1111 of file datetime.F90.
subroutine datetime::date_plus_year_sub (class(datetime_t) this) private
Definition at line 1126 of file datetime.F90.
subroutine datetime::date_set_day_sub (class(datetime_t) this, integer (kind=c_int), intent(in) newday) private
Definition at line 1137 of file datetime.F90.
subroutine datetime::date_set_month_sub (class(datetime_t) this, integer (kind=c_int), intent(in) newmonth) private
Definition at line 1149 of file datetime.F90.
subroutine datetime::date_set_year_sub (class(datetime_t) this, integer (kind=c_int), intent(in) newyear) private
Definition at line 1161 of file datetime.F90.
subroutine datetime::date_minus_year_sub (class(datetime_t) this) private
Definition at line 1173 of file datetime.F90.
subroutine datetime::date_plus_day_sub (class(datetime_t) this) private
Definition at line 1184 of file datetime.F90.
subroutine datetime::date_minus_day_sub (class(datetime_t) this) private
Definition at line 1195 of file datetime.F90.
logical (kind=c_bool) function datetime::is_leap_year_fn (class(datetime_t) this) private
Definition at line 1206 of file datetime.F90.
integer (kind=c_int) function datetime::mmddyyyy2julian (character (len=*) sMMDDYYYY) private
Definition at line 1218 of file datetime.F90.
References julian_day().
integer (kind=c_int) function, public datetime::mmdd2doy (character (len=*) sMMDD)
Definition at line 1256 of file datetime.F90.
References julian_day().
Referenced by growing_degree_day::growing_degree_day_initialize(), and growing_season::growing_season_initialize().
integer (kind=c_int) function datetime::mmddyyyy2doy (character (len=*) sMMDDYYYY) private
Definition at line 1294 of file datetime.F90.
References julian_day().
integer (kind=c_int) function datetime::get_day_of_year_fn (class(datetime_t) this) private
Definition at line 1337 of file datetime.F90.
References day_of_year().
integer (kind=c_int) function, public datetime::day_of_year (integer (kind=c_int), value iJD)
Definition at line 1348 of file datetime.F90.
References gregorian_date(), and julian_day().
Referenced by get_day_of_year_fn(), simulation_datetime::increment_by_one_day_sub(), and model_initialize::initialize_start_and_end_dates().
logical (kind=c_bool) function, public datetime::isleap (integer (kind=c_int), intent(in) iYear)
Definition at line 1366 of file datetime.F90.
Referenced by data_catalog_entry::test_for_need_to_pad_values_fn().
Variable Documentation
character (len=14), private datetime::sdate_format = "MM/DD/YYYY" private
Definition at line 100 of file datetime.F90.
Referenced by set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
character (len=14), public datetime::sdefault_date_format = "MM/DD/YYYY"
Definition at line 101 of file datetime.F90.
Referenced by set_date_format_indices(), and set_default_date_format().
integer (kind=c_int), private datetime::iscanmm1 = 1 private
Definition at line 102 of file datetime.F90.
Referenced by parse_text_to_date_sub(), set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
integer (kind=c_int), private datetime::iscanmm2 = 2 private
Definition at line 103 of file datetime.F90.
Referenced by parse_text_to_date_sub(), set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
integer (kind=c_int), private datetime::iscandelim1 = 3 private
Definition at line 104 of file datetime.F90.
Referenced by set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
integer (kind=c_int), private datetime::iscandd1 = 4 private
Definition at line 105 of file datetime.F90.
Referenced by parse_text_to_date_sub(), set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
integer (kind=c_int), private datetime::iscandd2 = 5 private
Definition at line 106 of file datetime.F90.
Referenced by parse_text_to_date_sub(), set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
integer (kind=c_int), private datetime::iscandelim2 = 6 private
Definition at line 107 of file datetime.F90.
Referenced by set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
integer (kind=c_int), private datetime::iscanyyyy1 = 7 private
Definition at line 108 of file datetime.F90.
Referenced by parse_text_to_date_sub(), set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
integer (kind=c_int), private datetime::iscanyyyy2 = 10 private
Definition at line 109 of file datetime.F90.
Referenced by parse_text_to_date_sub(), set_date_format_indices(), write_list_date_fn(), and write_list_datetime_fn().
character (len=14), private datetime::stime_format = "HH:MM:SS" private
Definition at line 111 of file datetime.F90.
Referenced by set_time_format_indices().
character (len=14), public datetime::sdefault_time_format = "HH:MM:SS"
Definition at line 112 of file datetime.F90.
Referenced by set_default_time_format().
integer (kind=c_int), private datetime::iscanhour1 = 1 private
Definition at line 113 of file datetime.F90.
Referenced by parse_text_to_time_sub(), and set_time_format_indices().
integer (kind=c_int), private datetime::iscanhour2 = 2 private
Definition at line 114 of file datetime.F90.
Referenced by parse_text_to_time_sub(), and set_time_format_indices().
integer (kind=c_int), private datetime::iscanmin1 = 4 private
Definition at line 115 of file datetime.F90.
Referenced by parse_text_to_time_sub(), and set_time_format_indices().
integer (kind=c_int), private datetime::iscanmin2 = 5 private
Definition at line 116 of file datetime.F90.
Referenced by parse_text_to_time_sub(), and set_time_format_indices().
integer (kind=c_int), private datetime::iscansec1 = 7 private
Definition at line 117 of file datetime.F90.
Referenced by parse_text_to_time_sub(), and set_time_format_indices().
integer (kind=c_int), private datetime::iscansec2 = 8 private
Definition at line 118 of file datetime.F90.
Referenced by parse_text_to_time_sub(), and set_time_format_indices().
type (month_t), dimension(12), target, public datetime::months = [ MONTH_T('Jan','January ', 1, 31, 1, 31), MONTH_T('Feb','February ', 32, 59, 2, 29), MONTH_T('Mar','March ', 60, 90, 3, 31), MONTH_T('Apr','April ', 91, 120, 4, 30), MONTH_T('May','May ', 121, 151, 5, 31), MONTH_T('Jun','June ', 152, 181, 6, 30), MONTH_T('Jul','July ', 182, 212, 7, 31), MONTH_T('Aug','August ', 213, 243, 8, 31), MONTH_T('Sep','September', 244, 273, 9, 30), MONTH_T('Oct','October ', 274, 304, 10, 31), MONTH_T('Nov','November ', 305, 334, 11, 30), MONTH_T('Dec','December ', 335, 365, 12, 31) ]
Definition at line 133 of file datetime.F90.
Referenced by data_catalog_entry::make_filename_from_template(), and write_pretty_datetime_fn().