SWB 2.0: solar_calculations Module Reference
solar_calculations Module Reference
Functions/Subroutines
real(kind=c_double) function daylight_hours (dOmega_s)
Calculate the number of daylight hours at a location.
elemental real(kind=c_double) function extraterrestrial_radiation__ra (dLatitude, dDelta, dOmega_s, dDsubR)
Calculate extraterrestrial radiation given latitude and time of year.
real(kind=c_double) function net_shortwave_radiation__rns (dRs, dAlbedo)
Calculate net shortwave radiation.
elemental real(kind=c_double) function solar_declination_simple__delta (iDayOfYear, iNumDaysInYear)
Calculate the solar declination for a given day of the year.
elemental real(kind=c_double) function solar_declination__delta (iDayOfYear, iNumDaysInYear)
Calculate the solar declination for a given day of the year.
elemental real(kind=c_double) function relative_earth_sun_distance__d_r (iDayOfYear, iNumDaysInYear)
Calculate the inverse relative Earth-Sun distance for a given day of the year.
elemental real(kind=c_double) function sunrise_sunset_angle__omega_s (dLatitude, dDelta)
Calculate sunrise/sunset angle, in RADIANS.
real(kind=c_double) function solar_radiation_hargreaves__rs (dRa, fTMin, fTMax)
Calculate shortwave solar radiation.
elemental real(kind=c_float) function estimate_percent_of_possible_sunshine__psun (fTMax, fTMin)
Estimate percent of possible sunshine.
real(kind=c_double) function clear_sky_solar_radiation__rso (dRa, dAs, dBs)
Calculate clear sky solar radiation.
real(kind=c_double) function clear_sky_solar_radiation_noab__rso (dRa, fElevation)
Calculate the clear sky solar radiation.
real(kind=c_double) function solar_radiation__rs (dRa, dAs, dBs, fPctSun)
Calculate solar radiation by means of the Angstrom formula.
real(kind=c_double) function net_longwave_radiation__rnl (fTMin, fTMax, dRs, dRso)
Calculate net longwave radiation flux.
elemental real(kind=c_double) function day_angle__gamma (iDayOfYear, iNumDaysInYear)
Calculate the day angle in RADIANS.
real(kind=c_double) function solar_altitude__alpha (dTheta_z)
Calculate the solar altitude given the zenith angle.
real(kind=c_double) function zenith_angle__theta_z (dLatitude, dDelta, dOmega)
Calculate solar zenith angle given latitude, declination, and (optionally) hour angle.
real(kind=c_double) function azimuth_angle__psi (rAlpha, rLatitude, rDelta)
Calculate solar azimuth angle.
Variables
real(kind=c_float) earth_sun_dist_dr
real(kind=c_float) solar_declination_delta
Function/Subroutine Documentation
real (kind=c_double) function solar_calculations::daylight_hours (real (kind=c_double), intent(in) dOmega_s)
Parameters
[in] dOmega_s Sunset hour angle in Radians.
Return values
rN Number of daylight hours.
Note
Implementation follows equation 34, Allen and others (1998).
Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 25 of file solar_calculations.F90.
References constants_and_conversions::pi.
elemental real (kind=c_double) function solar_calculations::extraterrestrial_radiation__ra (real (kind=c_double), intent(in) dLatitude, real (kind=c_double), intent(in) dDelta, real (kind=c_double), intent(in) dOmega_s, real (kind=c_double), intent(in) dDsubR)
Parameters
[in] dLatitude Latitude of grid cell in RADIANS.
[in] dDelta Solar declination in RADIANS.
[in] dOmega_s Sunset hour angle in RADIANS.
[in] dDsubR Inverse relative distance Earth-Sun.
Return values
rRa Extraterrestrial radiation in MJ / m**2 / day.
Note
1 MJ = 1e6 Joules; 1 Joule = 1 Watt / sec.
Therefore, multiply by 1e6 and divide by 86400 to get W/m*2-day.
Source Equation 21, Allen and others (1998).
Reference Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
See also
http://www.fao.org/docrep/x0490e/x0490e07.htm#solar%20radiation
Definition at line 77 of file solar_calculations.F90.
References constants_and_conversions::pi.
Referenced by et__hargreaves_samani::et_hargreaves_calculate().
real(kind=c_double) function solar_calculations::net_shortwave_radiation__rns (real(kind=c_double), intent(in) dRs, real(kind=c_double), intent(in) dAlbedo)
Parameters
[in] dRs Incoming shortwave solar radiation, in MJ / m**2 / day
[in] dAlbedo Albedo or canopy reflection coefficient; 0.23 for grass reference crop
Return values
dRns Net shortwave radiation, in MJ / m**2 / day
Note
Implementation follows equation 38, Allen and others (1998).
Reference: Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 113 of file solar_calculations.F90.
elemental real (kind=c_double) function solar_calculations::solar_declination_simple__delta (integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iNumDaysInYear)
Parameters
[in] iDayOfYear Integer day of the year (January 1 = 1)
[in] iNumDaysInYear Number of days in the current year
Return values
dDelta Solar declination, in RADIANS
Note
Implementation follows equation XXX? in:
Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 139 of file solar_calculations.F90.
References constants_and_conversions::twopi.
Referenced by et__hargreaves_samani::et_hargreaves_calculate(), and et__jensen_haise::et_jh_calculate().
elemental real (kind=c_double) function solar_calculations::solar_declination__delta (integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iNumDaysInYear)
Parameters
[in] iDayOfYear Integer day of the year (January 1 = 1)
[in] iNumDaysInYear Number of days in the current year
Return values
dDelta Solar declination, in RADIANS
Note
Implementation follows equation 1.3.1 in Iqbal (1983).
Iqbal (1983) reports maximum error of 0.0006 radians; if the last two terms are omitted, the reported accuracy drops to 0.0035 radians.
Reference: Iqbal, Muhammad (1983-09-28). An Introduction To Solar Radiation (p. 10). Elsevier Science. Kindle Edition.
Definition at line 168 of file solar_calculations.F90.
References day_angle__gamma().
elemental real (kind=c_double) function solar_calculations::relative_earth_sun_distance__d_r (integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iNumDaysInYear)
Parameters
[in] iDayOfYear Integer day of the year (January 1 = 1)
[in] iNumDaysInYear Number of days in the current year
Return values
dDsubR Relative Earth-Sun distance
Note
Implementation follows equation 23, Allen and others (1998):
\(d_r = 1 + 0.033 \cos \left(\frac{ 2 \pi }{365} J \right) \)
where:
\(d_r \) is the inverse relative distance between Earth and the Sun
\(J \) is the current day of the year
References: Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Duffie, J.A., Beckman, W.A. Solar Engineering of Thermal Processes.”. New York: Wiley, 1980.
Equation 1.2.3 in Iqbal, Muhammad (1983-09-28). An Introduction To Solar Radiation (p. 28). Elsevier Science. Kindle Edition.
Definition at line 215 of file solar_calculations.F90.
References constants_and_conversions::twopi.
Referenced by et__hargreaves_samani::et_hargreaves_calculate(), and et__jensen_haise::et_jh_calculate().
elemental real (kind=c_double) function solar_calculations::sunrise_sunset_angle__omega_s (real (kind=c_double), intent(in) dLatitude, real (kind=c_double), intent(in) dDelta)
Parameters
[in] dLatitude Latitude, in RADIANS
[in] dDelta Solar declination, in RADIANS
Return values
dOmega_s Sunset angle, in RADIANS
Note
Implementation follows equation 25, Allen and others (1998).
Hour angle is zero at solar noon. Definition in Iqbal (1983) yields positive values before solar noon, and negative values following solar noon.
Reference: Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 246 of file solar_calculations.F90.
Referenced by et__hargreaves_samani::et_hargreaves_calculate().
real (kind=c_double) function solar_calculations::solar_radiation_hargreaves__rs (real (kind=c_double), intent(in) dRa, real (kind=c_float), intent(in) fTMin, real (kind=c_float), intent(in) fTMax)
Calculates the solar radiation using Hargreave's radiation formula. For use when percent possible daily sunshine value is not available.
Parameters
[in] dRa Extraterrestrial radiation, in MJ / m**2 / day
[in] rTMin Minimum daily air temperature, in °C
[in] rTMax Maximum daily air temperature, in °C
Return values
dRa Solar radiation, in MJ / m**2 / day
Note
Implementation follows equation 50, Allen and others (1998).
Reference: Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 275 of file solar_calculations.F90.
elemental real (kind=c_float) function solar_calculations::estimate_percent_of_possible_sunshine__psun (real (kind=c_float), intent(in) fTMax, real (kind=c_float), intent(in) fTMin)
This function follows from equation 5 in "The Rational Use of the FAO Blaney-Criddle substituting the rearranged Hargreaves solar radiation formula into equation 5 results in the formulation below
Parameters
[in] fTMax Maximum daily air temperature, in °C
[in] fTMin Minimum daily air temperature, in °C
Return values
fPsun Percentage of possible sunshine, dimensionless percentage
Todo:
[Need to add reference here...]
Definition at line 303 of file solar_calculations.F90.
Referenced by et__jensen_haise::et_jh_calculate().
real (kind=c_double) function solar_calculations::clear_sky_solar_radiation__rso (real (kind=c_double), intent(in) dRa, real (kind=c_double), intent(in), optional dAs, real (kind=c_double), intent(in), optional dBs)
Calculate the clear sky solar radiation (i.e. when rPctSun = 100, n/N=1. Required for computing net longwave radiation.
Parameters
[in] dRa Extraterrestrial radiation, in MJ / m**2 / day
[in] dAs Solar radiation regression constant, expressing the fraction of extraterrestrial radiation that reaches earth on OVERCAST days.
[in] sBs Solar radiation regression constant. As + Bs express the fraction of extraterrestrial radiation that reaches earth on CLEAR days.
Return values
dRso Clear sky solar radiation, in MJ / m**2 / day
Note
Implementation follows equation 36, Allen and others (1998).
Reference: Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 345 of file solar_calculations.F90.
real (kind=c_double) function solar_calculations::clear_sky_solar_radiation_noab__rso (real (kind=c_double), intent(in) dRa, real (kind=c_float), intent(in) fElevation)
Calculate the clear sky solar radiation (i.e. when rPctSun = 100, n/N=1. Required for computing net longwave radiation. For use when no regression coefficients (A, B) are known.
Parameters
[in] dRa Extraterrestrial radiation, in MJ / m**2 / day
[in] fElevation Elevation, in METERS above sea level
Return values
dRso Clear sky solar radiation, in MJ / m**2 / day
Note
Implementation follows equation 37, Allen and others (1998).
Reference: Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 393 of file solar_calculations.F90.
real (kind=c_double) function solar_calculations::solar_radiation__rs (real (kind=c_double), intent(in) dRa, real (kind=c_double), intent(in) dAs, real (kind=c_double), intent(in) dBs, real (kind=c_double), intent(in) fPctSun)
Parameters
[in] dRa Extraterrestrial radiation in MJ / m**2 / day
[in] dAs Solar radiation regression constant, expressing the fraction of extraterrestrial radiation that reaches earth on OVERCAST days.
[in] dBs Solar radiation regression constant. As + Bs express the fraction of extraterrestrial radiation that reaches earth on CLEAR days.
[in] fPctSun Percent of TOTAL number of sunshine hours during which the sun actually shown.
Return values
fRs Solar radiation in MJ / m**2 / day
Implementation follows equation 35, Allen and others (1998).
Reference: Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 424 of file solar_calculations.F90.
real(kind=c_double) function solar_calculations::net_longwave_radiation__rnl (real(kind=c_float), intent(in) fTMin, real(kind=c_float), intent(in) fTMax, real(kind=c_double), intent(in) dRs, real(kind=c_double), intent(in) dRso)
Parameters
[in] fTMin Minimum daily air temperature, in °C
[in] fTMax Maximum daily air temperature, in °C
[in] dRs Measured or calculated shortwave solar radiation, in MJ / m**2 / day
[in] dRso Calculated clear-sky radiation, in MJ / m**2 / day
Return values
dRnl Net longwave solar radiation flux (incoming minus outgoing), in MJ / m**2 / day
Note
Implementation follows equation 39, Allen and others (1998).
Reference: Allen, R.G., and others, 1998, FAO Irrigation and Drainage Paper No. 56, "Crop Evapotranspiration (Guidelines for computing crop water requirements)", Food and Agriculture Organization, Rome, Italy.
Definition at line 455 of file solar_calculations.F90.
References meteorological_calculations::dewpoint_vapor_pressure__e_a().
elemental real (kind=c_double) function solar_calculations::day_angle__gamma (integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iNumDaysInYear)
This function expresses the integer day number as an angle (in radians). Output values range from 0 (on January 1st) to just less than \(2\pi \) on December 31st.
Parameters
[in] iDayOfYear Current day of the year.
[in] iNumDaysInYear Number of days in the current year.
Return values
dGamma Day angle in RADIANS.
Note
Implementation follows equation 1.2.2 in Iqbal (1983)
Reference: Iqbal, Muhammad (1983-09-28). An Introduction To Solar Radiation (p. 3). Elsevier Science. Kindle Edition.
Definition at line 499 of file solar_calculations.F90.
References constants_and_conversions::twopi.
Referenced by solar_declination__delta().
real (kind=c_double) function solar_calculations::solar_altitude__alpha (real (kind=c_double), intent(in) dTheta_z)
Parameters
[in] rTheta_z Solar zenith angle for given location and time, in RADIANS
Return values
rAlpha Solar altitude angle for given location and time, in RADIANS
Definition at line 518 of file solar_calculations.F90.
References constants_and_conversions::halfpi.
real (kind=c_double) function solar_calculations::zenith_angle__theta_z (real (kind=c_double), intent(in) dLatitude, real (kind=c_double), intent(in) dDelta, real (kind=c_double), intent(in), optional dOmega)
Calculate solar zenith. Solar zenith angle is the angle between a point directly overhead and the center of the sun's disk.
Parameters
[in] rLatitude Latitude of location for which estimate is being made, in RADIANS
[in] rDelta Solar declination angle, in RADIANS
[in] rOmega [OPTIONAL] Hour angle, measured at the celestial pole between the observer's meridian and the solar meridian, in RADIANS.
Return values
rTheta_z Solar zenith angle for given location and time, in RADIANS
Note
Implementation follows equation 9.67, Jacobson, 2005
Reference: Jacobson, M.Z., 2005, Fundamentals of atmospheric modeling, Second Edition: Cambridge University Press.
Definition at line 553 of file solar_calculations.F90.
References constants_and_conversions::halfpi.
real (kind=c_double) function solar_calculations::azimuth_angle__psi (real (kind=c_double), intent(in) rAlpha, real (kind=c_double), intent(in) rLatitude, real (kind=c_double), intent(in) rDelta)
Parameters
[in] rAlpha Solar altitude angle, in RADIANS.
[in] rLatitude Latitude of location for which estimate is being made, in RADIANS.
[in] rDelta Solar declination angle, in RADIANS.
Return values
rPsi Solar azimuth angle, in RADIANS.
Note
Implementation follows equation 1.5.2a in Iqbal (1983).
Reference: Iqbal, Muhammad (1983-09-28). An Introduction To Solar Radiation (p. 15). Elsevier Science. Kindle Edition.
Definition at line 593 of file solar_calculations.F90.
Variable Documentation
real (kind=c_float) solar_calculations::earth_sun_dist_dr
Definition at line 9 of file solar_calculations.F90.
real (kind=c_float) solar_calculations::solar_declination_delta
Definition at line 10 of file solar_calculations.F90.