SWB 2.0: et__jensen_haise Module Reference
et__jensen_haise Module Reference
Calculates potential evapotranspiration by means of the Jensen-Haise (1963) method.
Functions/Subroutines
elemental real(kind=c_float) function, public et_jh_calculate (iDayOfYear, iNumDaysInYear, fLatitude, fTMin, fTMax, fAlbedo, fAs, fBs, fSunPct)
Detailed Description
Function/Subroutine Documentation
et_jh_calculate()
elemental real (kind=c_float) function, public et__jensen_haise::et_jh_calculate (integer (kind=c_int), intent(in) iDayOfYear, integer (kind=c_int), intent(in) iNumDaysInYear, real (kind=c_float), intent(in) fLatitude, real (kind=c_float), intent(in) fTMin, real (kind=c_float), intent(in) fTMax, real (kind=c_float), intent(in), optional fAlbedo, real (kind=c_float), intent(in), optional fAs, real (kind=c_float), intent(in), optional fBs, real (kind=c_float), intent(in), optional fSunPct)
Todo:
Check these equations against original paper.
Definition at line 40 of file et__jensen_haise.F90.
References solar_calculations::estimate_percent_of_possible_sunshine__psun(), solar_calculations::relative_earth_sun_distance__d_r(), constants_and_conversions::rfreezing, and solar_calculations::solar_declination_simple__delta().
Referenced by model_domain::model_calculate_et_jensen_haise().