SWB 2.0: fog__monthly_grid Module Reference
fog__monthly_grid Module Reference
Module fog__monthly_grid provides support for estimating fog drip given a gridded map of FOG_RATIO and FOG_CAPTURE_EFFICIENCY.
Functions/Subroutines
subroutine, public fog_monthly_grid_initialize (lActive, PROJ4_string, dX, dY, dX_lon, dY_lat)
Initialize the fog drip algorithm.
subroutine, public fog_monthly_grid_calculate (fRainfall, fFog, iLanduse_Index, lActive, nodata_fill_value)
Variables
type(data_catalog_entry_t), pointer, public pfog_ratio
real(kind=c_float), dimension(:), allocatable ffog_catch_efficiency
type(t_netcdf4_file), pointer pncfile
Detailed Description
Function/Subroutine Documentation
fog_monthly_grid_initialize()
subroutine, public fog__monthly_grid::fog_monthly_grid_initialize (logical (kind=c_bool), dimension(:,:), intent(in) lActive, character (len=*), intent(inout) PROJ4_string, real (kind=c_double), dimension(:), intent(in) dX, real (kind=c_double), dimension(:), intent(in) dY, real (kind=c_double), dimension(:,:), intent(in) dX_lon, real (kind=c_double), dimension(:,:), intent(in) dY_lat)
Read in a fog ratio grid. Open a NetCDF output file to hold fog variable output.
Parameters
[in] lActive 2-D array of active cells within the model domain.
[in] dX 1D vector of X coordinates associated with the model domain.
[in] dY 1D vector of Y coordinates.
[in] dX_lon 2D array of longitude values.
[in] dY_lat 2D array of latitude values.
Determine how many landuse codes are present
open another netCDF file to hold fog interception
Definition at line 50 of file fog__monthly_grid.F90.
References data_catalog::dat, exceptions::die(), ffog_catch_efficiency, constants_and_conversions::ftinyval, constants_and_conversions::ltrue, netcdf4_support::netcdf_open_and_prepare_as_output(), parameters::params, pfog_ratio, pncfile, simulation_datetime::sim_dt, constants_and_conversions::true, and exceptions::warn().
Referenced by model_domain::model_initialize_fog_monthly_grid().
fog_monthly_grid_calculate()
subroutine, public fog__monthly_grid::fog_monthly_grid_calculate (real (kind=c_float), dimension(:), intent(in) fRainfall, real (kind=c_float), dimension(:), intent(inout) fFog, integer (kind=c_int), dimension(:), intent(in) iLanduse_Index, logical (kind=c_bool), dimension(:,:), intent(in) lActive, real (kind=c_float), dimension(:,:), intent(in) nodata_fill_value)
Definition at line 116 of file fog__monthly_grid.F90.
References exceptions::die(), ffog_catch_efficiency, netcdf4_support::nc_time, netcdf4_support::nc_z, netcdf4_support::netcdf_put_packed_variable_array(), netcdf4_support::netcdf_put_variable_vector(), pfog_ratio, pncfile, and simulation_datetime::sim_dt.
Referenced by model_domain::model_calculate_fog_monthly_grid().
Variable Documentation
pfog_ratio
type (data_catalog_entry_t), pointer, public fog__monthly_grid::pfog_ratio
Definition at line 31 of file fog__monthly_grid.F90.
Referenced by fog_monthly_grid_calculate(), and fog_monthly_grid_initialize().
ffog_catch_efficiency
real (kind=c_float), dimension(:), allocatable fog__monthly_grid::ffog_catch_efficiency private
Definition at line 32 of file fog__monthly_grid.F90.
Referenced by fog_monthly_grid_calculate(), and fog_monthly_grid_initialize().
pncfile
type (t_netcdf4_file), pointer fog__monthly_grid::pncfile private
Definition at line 33 of file fog__monthly_grid.F90.
Referenced by fog_monthly_grid_calculate(), and fog_monthly_grid_initialize().