SWB 2.0: exceptions Module Reference
exceptions Module Reference
Data Types
interface assert
Functions/Subroutines
subroutine, public die (sMessage, sModule, iLine, sHints, sCalledBy, iCalledByLine)
subroutine, public check_for_fatal_warnings ()
subroutine, public warn (sMessage, sModule, iLine, sHints, lFatal, iLogLevel, lEcho)
subroutine assert_1bit (lCondition, sMessage, sModule, iLine, sCalledBy, iCalledByLine)
subroutine assert_4bit (lCondition, sMessage, sModule, iLine, sCalledBy, iCalledByLine)
Variables
integer(kind=c_int), public number_of_fatal_warnings = 0
integer(kind=c_int), parameter max_fatal_warnings = 50
character(len=256), dimension(max_fatal_warnings) warning_text
Function/Subroutine Documentation
die()
subroutine, public exceptions::die (character (len=*), intent(in) sMessage, character (len=*), intent(in), optional sModule, integer (kind=c_int), intent(in), optional iLine, character (len=*), intent(in), optional sHints, character (len=*), intent(in), optional sCalledBy, integer (kind=c_int), intent(in), optional iCalledByLine)
Definition at line 24 of file exceptions.F90.
References logfiles::logs.
Referenced by assert_1bit(), assert_4bit(), check_for_fatal_warnings(), et__gridded_values::et_gridded_values_initialize(), fog__monthly_grid::fog_monthly_grid_calculate(), fog__monthly_grid::fog_monthly_grid_initialize(), data_catalog_entry::get_value_float_sub(), data_catalog_entry::get_value_int_sub(), data_catalog_entry::getvalues_constant_sub(), data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_static_netcdf_sub(), data_catalog_entry::getvalues_sub(), grid::grid_gridtopoint_int(), model_domain::initialize_arrays_sub(), model_initialize::initialize_generic_grid(), model_initialize::initialize_grid_options(), model_initialize::initialize_hydrologic_soil_groups(), model_initialize::initialize_landuse_codes(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), interception__gash::interception_gash_initialize(), string_list::list_append_string_sub(), string_list::list_return_all_as_character_fn(), string_list::list_return_all_as_float_fn(), string_list::list_return_all_as_int_fn(), string_list::list_return_all_as_logical_fn(), string_list::list_return_position_of_matching_string_fn(), netcdf4_support::netcdf_coord_to_col_row(), file_operations::open_file_read_access_sub(), precipitation__method_of_fragments::precipitation_method_of_fragments_calculate(), precipitation__method_of_fragments::precipitation_method_of_fragments_initialize(), precipitation__method_of_fragments::read_daily_fragments(), precipitation__method_of_fragments::read_fragments_sequence(), runoff__gridded_values::read_runoff_ratio_table(), routing__d8::routing_d8_initialize(), runoff__gridded_values::runoff_gridded_values_initialize(), runoff__gridded_values::runoff_gridded_values_update_ratios(), model_domain::set_inactive_cells_sub(), data_catalog_entry::transform_grid_to_grid_sub(), and precipitation__method_of_fragments::update_fragments().
check_for_fatal_warnings()
subroutine, public exceptions::check_for_fatal_warnings ()
Definition at line 71 of file exceptions.F90.
References die(), logfiles::logs, max_fatal_warnings, number_of_fatal_warnings, and warning_text.
Referenced by model_initialize::initialize_all().
warn()
subroutine, public exceptions::warn (character (len=*), intent(in) sMessage, character (len=*), intent(in), optional sModule, integer (kind=c_int), intent(in), optional iLine, character (len=*), intent(in), optional sHints, logical (kind=c_bool), intent(in), optional lFatal, integer (kind=c_int), intent(in), optional iLogLevel, logical (kind=c_bool), intent(in), optional lEcho)
Definition at line 124 of file exceptions.F90.
References logfiles::logs, number_of_fatal_warnings, and warning_text.
Referenced by dictionary::add_entry_to_dict_sub(), awc__gridded_values::awc_gridded_values_read(), direct_recharge__gridded_data::direct_recharge_initialize(), direct_soil_moisture__gridded_data::direct_soil_moisture_initialize(), fog__monthly_grid::fog_monthly_grid_initialize(), dictionary::get_entry_by_index_fn(), dictionary::get_entry_by_key_fn(), dictionary::get_next_entry_by_key_fn(), dictionary::get_next_entry_fn(), parameters::get_parameter_table_float(), parameters::get_parameter_values_float(), parameters::get_parameter_values_int(), parameters::get_parameter_values_string_list(), dictionary::get_values_as_float_given_list_of_keys_sub(), dictionary::get_values_as_float_sub(), dictionary::get_values_as_int_given_list_of_keys_sub(), dictionary::get_values_as_int_sub(), dictionary::get_values_as_logical_given_list_of_keys_sub(), dictionary::get_values_as_logical_sub(), dictionary::get_values_as_string_list_given_list_of_keys_sub(), dictionary::get_values_as_string_list_sub(), dictionary::grep_dictionary_key_names_fn(), parameters::grep_parameter_name(), growing_season::growing_season_initialize(), model_domain::initialize_arrays_sub(), continuous_frozen_ground_index::initialize_continuous_frozen_ground_index(), model_initialize::initialize_generic_grid(), model_initialize::initialize_generic_method(), model_initialize::initialize_grid_options(), model_initialize::initialize_landuse_codes(), model_initialize::initialize_parameter_tables(), model_initialize::initialize_percent_canopy_cover(), model_initialize::initialize_percent_pervious(), model_initialize::initialize_snow_storage(), model_initialize::initialize_soil_storage(), model_initialize::initialize_start_and_end_dates(), interception__bucket::interception_bucket_initialize(), interception__gash::interception_gash_initialize(), parameters::munge_files_and_add_to_param_list_sub(), netcdf4_support::netcdf_get_variable_slice(), netcdf4_support::nf_get_first_and_last(), netcdf4_support::nf_get_variable_id_and_type(), netcdf4_support::nf_get_variable_slice_float(), netcdf4_support::nf_get_variable_slice_int(), netcdf4_support::nf_get_variable_slice_short(), model_initialize::read_hydrologic_soil_groups(), model_initialize::read_landuse_codes(), and storm_drain_capture::storm_drain_capture_initialize().
assert_1bit()
subroutine exceptions::assert_1bit (logical (kind=c_bool), intent(in) lCondition, character (len=*), intent(in) sMessage, character (len=*), intent(in), optional sModule, integer (kind=c_int), intent(in), optional iLine, character (len=*), intent(in), optional sCalledBy, integer (kind=c_int), intent(in), optional iCalledByLine) private
Definition at line 172 of file exceptions.F90.
References die().
assert_4bit()
subroutine exceptions::assert_4bit (logical (kind=4), intent(in) lCondition, character (len=*), intent(in) sMessage, character (len=*), intent(in), optional sModule, integer (kind=c_int), intent(in), optional iLine, character (len=*), intent(in), optional sCalledBy, integer (kind=c_int), intent(in), optional iCalledByLine) private
Definition at line 201 of file exceptions.F90.
References die().
Variable Documentation
number_of_fatal_warnings
integer (kind=c_int), public exceptions::number_of_fatal_warnings = 0
Definition at line 17 of file exceptions.F90.
Referenced by check_for_fatal_warnings(), and warn().
max_fatal_warnings
integer (kind=c_int), parameter exceptions::max_fatal_warnings = 50 private
Definition at line 18 of file exceptions.F90.
Referenced by check_for_fatal_warnings().
warning_text
character (len=256), dimension(max_fatal_warnings) exceptions::warning_text private
Definition at line 19 of file exceptions.F90.
Referenced by check_for_fatal_warnings(), and warn().