SWB 2.0: logfiles Module Reference
logfiles Module Reference
Data Types
type logfile_t
Functions/Subroutines
subroutine set_output_directory_name_sub (this, sDirName)
subroutine set_log_level_sub (this, iLogLevel)
subroutine set_screen_echo_sub (this, lEcho)
subroutine initialize_logfiles_sub (this, iLogLevel, sFilePrefix, lWrite_SWB_Info)
subroutine open_files_write_access_sub (this, lWrite_SWB_Info)
subroutine close_files_sub (this)
subroutine make_prefix_sub (this)
subroutine write_to_logfiles_sub (this, sMessage, iTab, iLinesBefore, iLinesAfter, iLogLevel, lEcho)
subroutine writemultiline (sMessageText, iLU, iTab, iLinesBefore, iLinesAfter)
Write multiple lines of output to Fortran logical unit.
subroutine split (sText1, sText2)
character(len=len_trim(stext1)+2) function dquote (sText1)
character(len=:) function, allocatable make_timestamp ()
Variables
type(logfile_t), public logs
integer(kind=c_int) current_log_level = LOG_GENERAL
logical(kind=c_bool) current_log_echo = .false._c_bool
character(len=64) output_directory_name = ""
Function/Subroutine Documentation
set_output_directory_name_sub()
subroutine logfiles::set_output_directory_name_sub (class (logfile_t) this, character (len=*), intent(in) sDirName) private
Definition at line 70 of file logfiles.F90.
References constants_and_conversions::output_directory_name.
set_log_level_sub()
subroutine logfiles::set_log_level_sub (class (logfile_t) this, integer (kind=c_int), intent(in) iLogLevel) private
Definition at line 81 of file logfiles.F90.
References current_log_level.
set_screen_echo_sub()
subroutine logfiles::set_screen_echo_sub (class (logfile_t) this, logical (kind=c_bool), intent(in) lEcho) private
Definition at line 92 of file logfiles.F90.
References current_log_echo.
initialize_logfiles_sub()
subroutine logfiles::initialize_logfiles_sub (class (logfile_t) this, integer (kind=c_int), intent(in), optional iLogLevel, character (len=*), intent(in), optional sFilePrefix, logical (kind=c_bool), intent(in), optional lWrite_SWB_Info) private
Definition at line 103 of file logfiles.F90.
References constants_and_conversions::true.
open_files_write_access_sub()
subroutine logfiles::open_files_write_access_sub (class (logfile_t), intent(inout) this, logical (kind=c_bool), intent(in), optional lWrite_SWB_Info) private
Definition at line 140 of file logfiles.F90.
References make_timestamp(), constants_and_conversions::output_directory_name, and constants_and_conversions::true.
close_files_sub()
subroutine logfiles::close_files_sub (class (logfile_t) this) private
Definition at line 203 of file logfiles.F90.
make_prefix_sub()
subroutine logfiles::make_prefix_sub (class (logfile_t) this) private
Definition at line 225 of file logfiles.F90.
write_to_logfiles_sub()
subroutine logfiles::write_to_logfiles_sub (class (logfile_t) this, character (len=*), intent(in) sMessage, integer (kind=c_int), intent(in), optional iTab, integer (kind=c_int), intent(in), optional iLinesBefore, integer (kind=c_int), intent(in), optional iLinesAfter, integer (kind=c_int), intent(in), optional iLogLevel, logical (kind=c_bool), intent(in), optional lEcho) private
Definition at line 256 of file logfiles.F90.
References current_log_echo, current_log_level, and writemultiline().
writemultiline()
subroutine logfiles::writemultiline (character (len=*), intent(in) sMessageText, integer (kind=c_int), intent(in) iLU, integer (kind=c_int), intent(in) iTab, integer (kind=c_int), intent(in) iLinesBefore, integer (kind=c_int), intent(in) iLinesAfter) private
Writes one or more lines of an input text string to a Fortran logical unit number. To output multiple lines, insert a tilde (~) at each point in the text string where a carriage return is desired.
Parameters
[in] sMessageText Character string that contains the message to be written.
[in] iLU Integer value of the Fortran logical unit number to write to.
Definition at line 341 of file logfiles.F90.
References split().
Referenced by write_to_logfiles_sub().
split()
subroutine logfiles::split (character (len=*), intent(inout) sText1, character (len=*), intent(inout) sText2) private
Definition at line 392 of file logfiles.F90.
Referenced by writemultiline().
dquote()
character (len=len_trim(stext1)+2) function logfiles::dquote (character (len=*), intent(in) sText1) private
Definition at line 421 of file logfiles.F90.
make_timestamp()
character (len=:) function, allocatable logfiles::make_timestamp () private
Definition at line 432 of file logfiles.F90.
Referenced by open_files_write_access_sub().
Variable Documentation
logs
type (logfile_t), public logfiles::logs
Definition at line 61 of file logfiles.F90.
Referenced by data_catalog::catalog_print_sub(), exceptions::check_for_fatal_warnings(), model_initialize::create_rooting_depth_table(), exceptions::die(), data_catalog_entry::dump_data_structure_sub(), data_catalog_entry::getvalues_dynamic_netcdf_sub(), data_catalog_entry::getvalues_gridded_sub(), grid::grid_completelycover(), grid::grid_conform(), grid::grid_createcomplete(), grid::grid_dumpgridextent(), grid::grid_gridtogrid_int(), grid::grid_set_output_directory_name(), model_initialize::initialize_generic_grid(), model_initialize::initialize_generic_method(), model_initialize::initialize_grid_options(), model_initialize::initialize_hydrologic_soil_groups(), model_initialize::initialize_landuse_codes(), model_initialize::initialize_parameter_tables(), model_initialize::initialize_start_and_end_dates(), model_iterate::iterate_over_simulation_days(), main(), maximum_potential_recharge__gridded_data::maximum_potential_recharge_initialize(), parameters::munge_files_and_add_to_param_list_sub(), netcdf4_support::netcdf_close_file(), netcdf4_support::netcdf_open_and_prepare_as_output(), netcdf4_support::nf_create(), netcdf4_support::nf_open_file(), netcdf4_support::nf_return_index_double(), netcdf4_support::nf_trap(), file_operations::open_file_read_access_sub(), file_operations::open_file_write_access_sub(), daily_calculation::perform_daily_calculation(), dictionary::print_all_dictionary_entries_sub(), precipitation__method_of_fragments::process_fragment_sets(), precipitation__method_of_fragments::read_daily_fragments(), precipitation__method_of_fragments::read_fragments_sequence(), model_domain::set_inactive_cells_sub(), data_catalog_entry::transform_grid_to_grid_sub(), precipitation__method_of_fragments::update_fragments(), and exceptions::warn().
current_log_level
integer (kind=c_int) logfiles::current_log_level = LOG_GENERAL private
Definition at line 63 of file logfiles.F90.
Referenced by set_log_level_sub(), and write_to_logfiles_sub().
current_log_echo
logical (kind=c_bool) logfiles::current_log_echo = .false._c_bool private
Definition at line 64 of file logfiles.F90.
Referenced by set_screen_echo_sub(), and write_to_logfiles_sub().
output_directory_name
character (len=64) logfiles::output_directory_name = "" private
Definition at line 65 of file logfiles.F90.