SWB 2.0: direct_recharge__gridded_data Module Reference
direct_recharge__gridded_data Module Reference
Module direct_recharge__gridded_data provides support for adding miscellaneous source and sink terms.
Functions/Subroutines
subroutine, public direct_recharge_initialize (is_cell_active, landuse_index)
Initialize the routine to enable input/output of arbitrary sources/sink terms.
subroutine, public direct_recharge_calculate (direct_recharge, indx, is_cell_active, nodata_fill_value)
Variables
type(data_catalog_entry_t), pointer pcesspool
type(data_catalog_entry_t), pointer pdisposal_well
type(data_catalog_entry_t), pointer pstorm_drain
type(data_catalog_entry_t), pointer pwater_body_recharge
type(data_catalog_entry_t), pointer pwater_main
type(data_catalog_entry_t), pointer pannual_recharge_rate
real(kind=c_float), dimension(:), allocatable fcesspool
real(kind=c_float), dimension(:), allocatable fdisposal_well
real(kind=c_float), dimension(:), allocatable fstorm_drain
real(kind=c_float), dimension(:), allocatable fwater_body_recharge
real(kind=c_float), dimension(:), allocatable fwater_main
real(kind=c_float), dimension(:), allocatable fannual_recharge_rate
real(kind=c_float), dimension(:), allocatable fcesspool_table
real(kind=c_float), dimension(:), allocatable fdisposal_well_table
real(kind=c_float), dimension(:), allocatable fstorm_drain_table
real(kind=c_float), dimension(:), allocatable fwater_body_recharge_table
real(kind=c_float), dimension(:), allocatable fwater_main_table
real(kind=c_float), dimension(:), allocatable fannual_recharge_rate_table
real(kind=c_float), dimension(:), allocatable direct_recharge_active_fraction_table
real(kind=c_float), dimension(:), allocatable, public direct_recharge_active_fraction
type(t_netcdf4_file), pointer pncfile
type(datetime_t) date_of_last_retrieval
Detailed Description
Function/Subroutine Documentation
subroutine, public direct_recharge__gridded_data::direct_recharge_initialize (logical (kind=c_bool), dimension(:,:), intent(in) is_cell_active, integer (kind=c_int), dimension(:), intent(in) landuse_index)
Open gridded data file. Open a NetCDF output file to hold variable output.
Parameters
[in] is_cell_active 2D array of active cells within the model domain.
[in] iLanduseIndex 1D vector of indices corresponding to rows of the landuse lookup table(s).
[in] dX 1D vector of X coordinates associated with the model domain.
[in] dY 1D vector of Y coordinates.
[in] dX_lon 2D array of longitude values.
[in] dY_lat 2D array of latitude values.
Determine how many landuse codes are present
Definition at line 76 of file direct_recharge__gridded_data.F90.
References data_catalog::dat, date_of_last_retrieval, direct_recharge_active_fraction, direct_recharge_active_fraction_table, fannual_recharge_rate, fannual_recharge_rate_table, fcesspool, fcesspool_table, fdisposal_well, fdisposal_well_table, fstorm_drain, fstorm_drain_table, constants_and_conversions::ftinyval, fwater_body_recharge, fwater_body_recharge_table, fwater_main, fwater_main_table, pannual_recharge_rate, parameters::params, pcesspool, pdisposal_well, pstorm_drain, pwater_body_recharge, pwater_main, constants_and_conversions::true, and exceptions::warn().
Referenced by model_domain::model_initialize_direct_recharge_gridded().
subroutine, public direct_recharge__gridded_data::direct_recharge_calculate (real (kind=c_float), intent(inout) direct_recharge, integer (kind=c_int), intent(in) indx, logical (kind=c_bool), dimension(:,:), intent(in) is_cell_active, real (kind=c_float), dimension(:,:), intent(in) nodata_fill_value)
Definition at line 333 of file direct_recharge__gridded_data.F90.
References date_of_last_retrieval, fannual_recharge_rate, fcesspool, fdisposal_well, fstorm_drain, fwater_body_recharge, fwater_main, pannual_recharge_rate, pcesspool, pdisposal_well, pstorm_drain, pwater_body_recharge, pwater_main, and simulation_datetime::sim_dt.
Referenced by model_domain::model_calculate_direct_recharge_gridded().
Variable Documentation
type (data_catalog_entry_t), pointer direct_recharge__gridded_data::pcesspool private
Definition at line 31 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
type (data_catalog_entry_t), pointer direct_recharge__gridded_data::pdisposal_well private
Definition at line 32 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
type (data_catalog_entry_t), pointer direct_recharge__gridded_data::pstorm_drain private
Definition at line 33 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
type (data_catalog_entry_t), pointer direct_recharge__gridded_data::pwater_body_recharge private
Definition at line 34 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
type (data_catalog_entry_t), pointer direct_recharge__gridded_data::pwater_main private
Definition at line 35 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
type (data_catalog_entry_t), pointer direct_recharge__gridded_data::pannual_recharge_rate private
Definition at line 36 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fcesspool private
Definition at line 38 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fdisposal_well private
Definition at line 39 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fstorm_drain private
Definition at line 40 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fwater_body_recharge private
Definition at line 41 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fwater_main private
Definition at line 42 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fannual_recharge_rate private
Definition at line 43 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fcesspool_table private
Definition at line 46 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fdisposal_well_table private
Definition at line 47 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fstorm_drain_table private
Definition at line 48 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fwater_body_recharge_table private
Definition at line 49 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fwater_main_table private
Definition at line 50 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::fannual_recharge_rate_table private
Definition at line 51 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable direct_recharge__gridded_data::direct_recharge_active_fraction_table private
Definition at line 53 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_initialize().
real (kind=c_float), dimension(:), allocatable, public direct_recharge__gridded_data::direct_recharge_active_fraction
Definition at line 54 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_initialize(), and daily_calculation::perform_daily_calculation().
type (t_netcdf4_file), pointer direct_recharge__gridded_data::pncfile private
Definition at line 56 of file direct_recharge__gridded_data.F90.
type (datetime_t) direct_recharge__gridded_data::date_of_last_retrieval private
Definition at line 58 of file direct_recharge__gridded_data.F90.
Referenced by direct_recharge_calculate(), and direct_recharge_initialize().