message("--------------------------------------------------------------------")
message("   Summary of CMAKE environment variables")
message("--------------------------------------------------------------------")
message("BUILD TYPE: " ${CMAKE_BUILD_TYPE})
message( " ")
message("CMAKE_HOST_WIN32: " ${CMAKE_HOST_WIN32})
message("CMAKE_HOST_APPLE: " ${CMAKE_HOST_APPLE})
message("CMAKE_Fortran_COMPILER full path: " ${CMAKE_Fortran_COMPILER})
message("Fortran compiler: " ${Fortran_COMPILER_NAME})
message("CMAKE Fortran flags (Debug):      " ${CMAKE_Fortran_FLAGS_DEBUG})
message("CMAKE Fortran flags (Profile):      " ${CMAKE_Fortran_FLAGS_PROFILE})
message("CMAKE Fortran flags (Release):      " ${CMAKE_Fortran_FLAGS_RELEASE})
message( " ")
MESSAGE("Install to directory: " ${CMAKE_INSTALL_PREFIX})
message(" ")
message("Include directory: ")
message(" ==> ${INC_PATH}")
message("Library locations for external libraries:")
message(" ==> ${LIB_PATH}")

message(" ")
message("MAIN LIBRARIES:")
message("  GFORTRAN  ${LIBGFORTRAN}")
message("  GCC       ${LIBGCC}")
message(" ")
message("NETCDF-RELATED LIBRARIES:")
message("  NETCDF    ${LIBNETCDF}")
message("  HDF5_HL   ${LIBHDF5_HL}")
message("  HDF5      ${LIBHDF5}")
message("  LIBCURL   ${LIBCURL}")
message("  LIBZ      ${LIBZ}")
#message("  LIBSZ     ${LIBSZ}")
#message(" ")
#message("  DISLIN-RELATED LIBRARIES")
#message("    DISLIN          ${LIBDISLIN}")
#message("    OPENGL32        ${LIBOPENGL}")
#message("    GDI32           ${LIBGDI32}")
message("  LIBWINPTHREAD   ${LIBWINPTHREAD}")
message("  Xm              ${LIBXM}")
message(" ")
message("CURL-RELATED LIBRARIES")
message("  NETTLE            ${LIBNETTLE}")
message("  GNUTLS            ${LIBGNUTLS}")
message("  LIBCRYPTO   ${LIBCRYPTO}")
message("  LIBCRYPT32  ${LIBCRYPT32}")
message("  LIBGNUTLS   ${LIBGNUTLS}")
message("  LIBLDAP     ${LIBLDAP}")
message("  LIBSASL2    ${LIBSASL2}")
message("  LIBLBER     ${LIBLBER}")
message("  LIBSSH2     ${LIBSSH2}")
message("  LIBSSL      ${LIBSSL}")
message(" ")
message("RESULTING LIBRARY LINK DEFINITION")
message( "${EXTERNAL_LIBS}")

message(" ")
message("CMAKE_BINARY_DIR: " ${CMAKE_BINARY_DIR})
message("CMAKE_CURRENT_SOURCE_DIR: " ${CMAKE_CURRENT_SOURCE_DIR})
message("PROJECT_SOURCE_DIR: " ${PROJECT_SOURCE_DIR})
message( " ")
message("--------------------------------------------------------------------")
