message("--------------------------------------------------------------------")
message("   Summary of CMAKE environment variables")
message("--------------------------------------------------------------------")
message("BUILD TYPE: " ${CMAKE_BUILD_TYPE})
message( " ")
message("CMAKE_HOST_WIN32: " ${CMAKE_HOST_WIN32})
message("CMAKE_HOST_APPLE: " ${CMAKE_HOST_APPLE})
message("CMAKE_Fortran_COMPILER full path: " ${CMAKE_Fortran_COMPILER})
message("Fortran compiler: " ${Fortran_COMPILER_NAME})
message("CMAKE Fortran flags (Debug):      " ${CMAKE_Fortran_FLAGS_DEBUG})
message("CMAKE Fortran flags (Profile):      " ${CMAKE_Fortran_FLAGS_PROFILE})
message("CMAKE Fortran flags (Release):      " ${CMAKE_Fortran_FLAGS_RELEASE})
message( " ")
MESSAGE("Install to directory: " ${CMAKE_INSTALL_PREFIX})
message(" ")
message("Include directory: ")
message(" ==> ${INC_PATH}")
message("Library locations for external libraries:")
message(" ==> ${LIB_PATH}")

message(" ")
message("MAIN LIBRARIES:")
message("  GFORTRAN  ${LIB_GFORTRAN}")
message("  GCC       ${LIB_GCC}")
message(" ")
message("NETCDF-RELATED LIBRARIES:")
message("  NETCDF    ${LIB_NETCDF}")
message("  HDF5_HL   ${LIB_HDF5_HL}")
message("  HDF5      ${LIB_HDF5}")
message("  LIBDL     ${LIB_DL}")
message("  LIBZ      ${LIB_Z}")
message("  LIBSZ     ${LIB_SZ}")
message(" ")
message("RESULTING LIBRARY LINK DEFINITION")
message( "${EXTERNAL_LIBS}")

message(" ")
message("CMAKE_BINARY_DIR: " ${CMAKE_BINARY_DIR})
message("CMAKE_CURRENT_SOURCE_DIR: " ${CMAKE_CURRENT_SOURCE_DIR})
message("PROJECT_SOURCE_DIR: " ${PROJECT_SOURCE_DIR})
message( " ")
message("--------------------------------------------------------------------")
